# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Quantum Control — NISQ Quantum Simulation of Coupled Oscillator Networks
"""NISQ quantum simulation of coupled Kuramoto oscillator networks via XY Hamiltonian mapping."""

from importlib.metadata import PackageNotFoundError, version

# Subpackage-level access for new modules
from . import analysis, applications, fep, forecasting, gauge, l16, pgbo, psi_field, ssgf, tcbo
from .applications.eeg_classification import eeg_plv_to_vqe, eeg_quantum_kernel
from .benchmarks.classical_baselines import (
    ClassicalBaselineRun,
    available_baselines,
    mps_tebd_baseline,
    qutip_lindblad_baseline,
    run_documented_classical_baselines,
    scipy_ode_baseline,
)
from .benchmarks.quantum_advantage import (
    AdvantageResult,
    classical_benchmark,
    estimate_crossover,
    quantum_benchmark,
    run_scaling_benchmark,
)
from .bridge.control_plasma_knm import (
    build_knm_plasma,
    build_knm_plasma_from_config,
    build_knm_plasma_spec,
    plasma_omega,
)
from .bridge.knm_hamiltonian import (
    OMEGA_N_16,
    build_knm_paper27,
    build_kuramoto_ring,
    knm_to_ansatz,
    knm_to_hamiltonian,
)
from .bridge.orchestrator_adapter import PhaseOrchestratorAdapter
from .bridge.phase_artifact import LayerStateArtifact, LockSignatureArtifact, UPDEPhaseArtifact
from .bridge.snn_adapter import (
    ArcaneNeuronBridge,
    SNNQuantumBridge,
    quantum_measurement_to_current,
    spike_train_to_rotations,
)
from .bridge.ssgf_adapter import (
    SSGFQuantumLoop,
    quantum_to_ssgf_state,
    ssgf_state_to_quantum,
    ssgf_w_to_hamiltonian,
)
from .compiler.mlir import (
    CompilerADExecutableConfig,
    CompilerADKernelVerification,
    CompilerADTransformPlan,
    DifferentiableMLIRCompileConfig,
    ExecutableCompilerADKernel,
    MLIRCompileConfig,
    MLIRModule,
    PrimitiveLoweringStatus,
    build_compiler_ad_transform_plan,
    compile_compiler_ad_transform_plan_to_mlir,
    compile_custom_derivative_rule_to_executable,
    compile_custom_derivative_rule_to_mlir,
    compile_kuramoto_to_mlir,
    compile_registered_primitive_to_executable,
    compile_whole_program_ad_trace_to_mlir,
)
from .control.hardware_topological_optimizer import HardwareTopologicalOptimizer
from .control.q_disruption import QuantumDisruptionClassifier
from .control.q_disruption_iter import (
    DisruptionBenchmark,
    ITERFeatureSpec,
    from_fusion_core_shot,
    generate_synthetic_iter_data,
    normalize_iter_features,
)
from .control.qaoa_mpc import QAOA_MPC
from .control.qpetri import QuantumPetriCampaignReport, QuantumPetriNet, QuantumPetriStepReport
from .control.realtime_runtime import (
    MonotonicRealtimeClock,
    RealtimeRunResult,
    RealtimeRuntimeConfig,
    RealtimeSLAConfig,
    RealtimeSLAReport,
    RealtimeTickRecord,
    VirtualRealtimeClock,
    enforce_realtime_sla,
    evaluate_realtime_sla,
    run_realtime_control_loop,
)
from .control.topological_optimizer import TopologicalCouplingOptimizer
from .control.vqls_gs import VQLS_GradShafranov
from .deployment.cloud_native import (
    CloudDeploymentSpec,
    CloudManifestBundle,
    ContainerResources,
    generate_cloud_manifests,
)
from .differentiable import (
    DEFAULT_CUSTOM_DERIVATIVE_REGISTRY,
    ArmijoLineSearchResult,
    CustomDerivativeCheckResult,
    CustomDerivativeRegistry,
    CustomDerivativeRule,
    DifferentiableOptimizer,
    DualNumber,
    FisherConjugateGradientResult,
    FisherVectorProductResult,
    FixedPointSensitivityResult,
    GradientCheckResult,
    GradientResult,
    HessianResult,
    HVPResult,
    ImplicitSensitivityResult,
    JacobianResult,
    JVPResult,
    LeastSquaresCovarianceResult,
    LevenbergMarquardtDampingUpdate,
    LevenbergMarquardtOptimizer,
    LevenbergMarquardtResult,
    LevenbergMarquardtStep,
    LevenbergMarquardtTrial,
    NaturalGradientOptimizationResult,
    NaturalGradientOptimizer,
    NaturalGradientResult,
    OptimizationResult,
    Parameter,
    ParameterBounds,
    ParameterShiftRule,
    PrimitiveBatchingRule,
    PrimitiveIdentity,
    PrimitiveLoweringRule,
    PrimitiveTransformRule,
    ReverseNode,
    ShotAllocationResult,
    SparseMatrixResult,
    StochasticGradientResult,
    TraceADScalar,
    VJPResult,
    WeightedGradientResult,
    WholeProgramADResult,
    WholeProgramIRNode,
    WholeProgramTraceEvent,
    allocate_parameter_shift_shots,
    armijo_backtracking_line_search,
    batch_complex_step_gradient,
    batch_custom_jacobian,
    batch_custom_jvp,
    batch_custom_vjp,
    batch_finite_difference_hvp,
    batch_finite_difference_jvp,
    batch_finite_difference_vjp,
    batch_parameter_shift_gradient,
    batch_value_and_complex_step_grad,
    batch_value_and_custom_jacobian,
    batch_value_and_custom_jvp,
    batch_value_and_custom_vjp,
    batch_value_and_finite_difference_grad,
    batch_value_and_finite_difference_hvp,
    batch_value_and_finite_difference_jvp,
    batch_value_and_finite_difference_vjp,
    batch_value_and_parameter_shift_grad,
    batch_vector_jacobian_product,
    check_custom_derivative_consistency,
    check_parameter_shift_consistency,
    complex_step_gradient,
    custom_derivative_rule_for,
    custom_gauss_newton_gradient,
    custom_jacobian,
    custom_jvp,
    custom_levenberg_marquardt_step,
    custom_vjp,
    dense_to_sparse_matrix,
    dual_cos,
    dual_exp,
    dual_log,
    dual_sin,
    empirical_fisher_conjugate_gradient,
    empirical_fisher_metric,
    empirical_fisher_vector_product,
    evaluate_levenberg_marquardt_step,
    finite_difference_gradient,
    finite_difference_hessian,
    finite_difference_hvp,
    finite_difference_jacobian,
    finite_difference_jvp,
    finite_difference_vjp,
    forward_mode_gradient,
    gauss_newton_gradient,
    grad,
    hessian,
    huber_residual_weights,
    implicit_fixed_point_sensitivity,
    implicit_stationary_sensitivity,
    is_jax_autodiff_available,
    jacfwd,
    jacobian,
    jacrev,
    jax_value_and_grad,
    least_squares_covariance,
    levenberg_marquardt_step,
    natural_gradient,
    parameter_shift_gradient,
    parameter_shift_gradient_with_uncertainty,
    register_custom_derivative_rule,
    register_primitive_batching_rule,
    register_primitive_lowering_rule,
    register_primitive_transform_rule,
    registered_custom_jacobian,
    registered_custom_jvp,
    registered_custom_vjp,
    reverse_cos,
    reverse_exp,
    reverse_log,
    reverse_mode_gradient,
    reverse_sin,
    soft_l1_residual_weights,
    sparse_empirical_fisher_metric,
    sparse_hessian,
    sparse_jacobian,
    update_levenberg_marquardt_damping,
    value_and_complex_step_grad,
    value_and_custom_jacobian,
    value_and_custom_jvp,
    value_and_custom_vjp,
    value_and_finite_difference_grad,
    value_and_finite_difference_hessian,
    value_and_finite_difference_hvp,
    value_and_finite_difference_jacobian,
    value_and_finite_difference_jvp,
    value_and_forward_mode_grad,
    value_and_grad,
    value_and_hessian,
    value_and_jacfwd,
    value_and_jacobian,
    value_and_jacrev,
    value_and_parameter_shift_grad,
    value_and_reverse_mode_grad,
    vector_jacobian_product,
    vmap,
    weighted_gradient_sum,
    whole_program_grad,
    whole_program_trace_grad,
    whole_program_trace_value_and_grad,
    whole_program_value_and_grad,
)
from .forecasting import (
    ForecastModelRun,
    SynchronisationForecastBenchmarkResult,
    SynchronisationForecastDataset,
    load_hardware_kuramoto_4osc_trace,
    load_ieee5bus_sync_forecast_case,
    run_real_data_sync_forecast_benchmark,
    run_real_data_sync_forecast_suite,
)
from .hardware.aggregators import (
    AggregatorProviderRoute,
    ResolvedAggregatorProviderRoute,
    aggregator_provider_routes_for,
    built_in_aggregator_provider_routes,
    resolve_aggregator_provider_route,
)
from .hardware.fast_classical import fast_sparse_evolution
from .hardware.hal import (
    BackendCapabilities,
    BackendProfile,
    HardwareAbstractionLayer,
    LocalDeterministicSimulator,
    QuantumBackend,
    QuantumJobRef,
    QuantumJobResult,
    QuantumWorkload,
    built_in_backend_profiles,
)
from .hardware.hal_azure import AzureQuantumHALAdapter, azure_openqasm3_to_workload
from .hardware.hal_braket import (
    BraketAwsHALAdapter,
    BraketLocalHALAdapter,
    braket_circuit_to_workload,
)
from .hardware.hal_cirq import CirqLocalHALAdapter, cirq_circuit_workload
from .hardware.hal_dwave import DWaveLeapHALAdapter, dwave_bqm_workload
from .hardware.hal_ionq import IonQCloudHALAdapter, ionq_qis_workload
from .hardware.hal_iqm import IQMHALAdapter, iqm_qiskit_workload
from .hardware.hal_oqc import OQCHALAdapter, oqc_openqasm3_workload
from .hardware.hal_pasqal import PasqalPulserHALAdapter, pulser_sequence_workload
from .hardware.hal_pennylane import PennyLaneDeviceHALAdapter, pennylane_gate_workload
from .hardware.hal_qbraid import QbraidRuntimeHALAdapter, qbraid_program_to_workload
from .hardware.hal_qiskit import (
    QiskitAerHALAdapter,
    QiskitRuntimeHALAdapter,
    qiskit_circuit_to_qasm3_workload,
    qiskit_circuit_to_workload,
)
from .hardware.hal_quandela import QuandelaPercevalHALAdapter, quandela_perceval_workload
from .hardware.hal_quantinuum import QuantinuumCloudHALAdapter, quantinuum_tket_workload
from .hardware.hal_quera_bloqade import QuEraBloqadeHALAdapter, bloqade_ahs_workload
from .hardware.hal_rigetti import RigettiQCSHALAdapter, rigetti_quil_workload
from .hardware.hal_strangeworks import (
    StrangeworksComputeHALAdapter,
    strangeworks_program_to_workload,
)
from .hardware.provider_capability_discovery import (
    CapabilityDecisionStatus,
    ProviderCapabilityDecision,
    ProviderCapabilitySnapshot,
    ProviderMetadataProbe,
    assess_provider_capability_snapshot,
    probe_aggregator_provider_capability,
    snapshot_from_azure_target,
    snapshot_from_braket_device,
    snapshot_from_dwave_solver,
    snapshot_from_ionq_backend,
    snapshot_from_iqm_backend,
    snapshot_from_oqc_target,
    snapshot_from_pasqal_target,
    snapshot_from_qbraid_device,
    snapshot_from_qiskit_runtime_backend,
    snapshot_from_quandela_processor,
    snapshot_from_quantinuum_backend,
    snapshot_from_quera_bloqade,
    snapshot_from_rigetti_qcs,
    snapshot_from_strangeworks_backend,
)
from .hardware.provider_smoke import (
    AggregatorProviderOptionalDependencyRow,
    ProviderOptionalDependencyRow,
    aggregator_provider_optional_dependency_matrix,
    provider_optional_dependency_matrix,
)
from .hardware.qubit_mapper import (
    ExecutionRegion,
    QubitMappingResult,
    dynq_initial_layout,
)
from .hardware.runner import HardwareRunner, JobResult
from .hardware.trapped_ion import transpile_for_trapped_ion, trapped_ion_noise_model
from .identity.binding_spec import (
    ARCANE_SAPIENCE_SPEC,
    ORCHESTRATOR_MAPPING,
    build_identity_attractor,
    orchestrator_to_quantum_phases,
    quantum_to_orchestrator_phases,
    solve_identity,
)
from .identity.coherence_budget import coherence_budget, fidelity_at_depth
from .identity.entanglement_witness import chsh_from_statevector, disposition_entanglement_map
from .identity.ground_state import IdentityAttractor
from .identity.identity_key import identity_fingerprint, prove_identity, verify_identity
from .kuramoto_core import (
    KuramotoProblem,
    build_kuramoto_problem,
    compile_dense_hamiltonian,
    compile_hamiltonian,
    compile_trotter_circuit,
    measure_order_parameter,
    simulate_variant_trajectory,
    validate_kuramoto_inputs,
)
from .mitigation.compound_mitigation import compound_mitigate_pipeline
from .mitigation.pec import PECResult, pauli_twirl_decompose, pec_sample
from .mitigation.symmetry_decay import (
    GUESSResult,
    SymmetryDecayModel,
    guess_extrapolate,
    learn_symmetry_decay,
)
from .mitigation.zne import ZNEResult, gate_fold_circuit, zne_extrapolate
from .phase.kuramoto_variants import (
    HigherOrderKuramotoSpec,
    KuramotoVariant,
    KuramotoVariantResult,
    MonitoredKuramotoSpec,
    PTSymmetricKuramotoSpec,
    build_triadic_ring_terms,
    simulate_higher_order_kuramoto,
    simulate_monitored_kuramoto,
    simulate_pt_symmetric_kuramoto,
)
from .phase.lindblad_engine import LindbladSyncEngine
from .phase.phase_vqe import PhaseVQE
from .phase.results import TrajectoryResult
from .phase.structured_ansatz import build_structured_ansatz
from .phase.trotter_upde import QuantumUPDESolver
from .phase.xy_kuramoto import QuantumKuramotoSolver, TrotterEvolutionConfig
from .qec.biological_diagnostics import (
    BiologicalSurfaceDiagnostics,
    analyse_biological_surface_code,
)
from .qec.biological_pipeline import (
    BiologicalQecBatchExecution,
    BiologicalQecExecution,
    run_biological_qec_batch_execution,
    run_biological_qec_execution,
)
from .qec.biological_surface_code import BiologicalMWPMDecoder, BiologicalSurfaceCode
from .qec.control_qec import ControlQEC
from .qec.fault_tolerant import FaultTolerantUPDE, LogicalQubit
from .qec.multiscale_qec import (
    MultiscaleQECResult,
    QECLevel,
    build_multiscale_qec,
    concatenated_logical_rate,
)
from .qec.surface_code_upde import SurfaceCodeSpec, SurfaceCodeUPDE
from .qec.syndrome_flow import syndrome_flow_analysis
from .qsnn.dynamic_coupling import DynamicCouplingEngine
from .qsnn.qlayer import QuantumDenseLayer
from .qsnn.qlif import QuantumLIFNeuron
from .qsnn.qstdp import QuantumSTDP
from .qsnn.qsynapse import QuantumSynapse
from .qsnn.quantum_neuromorphic_bridge import (
    CLAIM_BOUNDARY,
    DynamicCouplingConfig,
    NeuromorphicStepResult,
    QuantumLIFConfig,
    QuantumNeuromorphicBridge,
    TraceSTDPConfig,
    TraceSTDPState,
)
from .qsnn.training import QSNNTrainer
from .stable_core import (
    Backend,
    Experiment,
    Problem,
    Result,
    backend_capability_matrix,
    build_backend,
    build_experiment,
    build_problem,
    build_result,
    classical_reference_backend,
    hardware_replay_backend,
    pennylane_backend,
    problem_from_kuramoto,
    problem_to_kuramoto,
    pulser_surrogate_backend,
    qiskit_backend,
    qutip_backend,
    stable_core_capability_markdown,
    stable_core_capability_payload,
    write_stable_core_capability_artifacts,
)
from .stable_core_preflight import (
    StableCorePreflightResult,
    run_stable_core_preflight,
    stable_core_backend_dependencies,
    stable_core_preflight_fixtures_json,
    stable_core_preflight_fixtures_markdown,
    stable_core_preflight_fixtures_payload,
)

try:
    __version__ = version("scpn-quantum-control")
except PackageNotFoundError:
    __version__ = "0.0.0+local"

__all__ = [
    "eeg_plv_to_vqe",
    "eeg_quantum_kernel",
    "KuramotoProblem",
    "Problem",
    "Backend",
    "Experiment",
    "Result",
    "backend_capability_matrix",
    "build_problem",
    "build_backend",
    "build_experiment",
    "build_result",
    "classical_reference_backend",
    "hardware_replay_backend",
    "qiskit_backend",
    "qutip_backend",
    "pennylane_backend",
    "pulser_surrogate_backend",
    "stable_core_capability_payload",
    "stable_core_capability_markdown",
    "StableCorePreflightResult",
    "stable_core_backend_dependencies",
    "stable_core_preflight_fixtures_json",
    "stable_core_preflight_fixtures_markdown",
    "stable_core_preflight_fixtures_payload",
    "run_stable_core_preflight",
    "write_stable_core_capability_artifacts",
    "problem_from_kuramoto",
    "problem_to_kuramoto",
    "build_kuramoto_problem",
    "validate_kuramoto_inputs",
    "compile_hamiltonian",
    "compile_dense_hamiltonian",
    "compile_trotter_circuit",
    "measure_order_parameter",
    "simulate_variant_trajectory",
    "KuramotoVariant",
    "KuramotoVariantResult",
    "HigherOrderKuramotoSpec",
    "MonitoredKuramotoSpec",
    "PTSymmetricKuramotoSpec",
    "build_triadic_ring_terms",
    "simulate_higher_order_kuramoto",
    "simulate_monitored_kuramoto",
    "simulate_pt_symmetric_kuramoto",
    "TopologicalCouplingOptimizer",
    "HardwareTopologicalOptimizer",
    "fast_sparse_evolution",
    "compound_mitigate_pipeline",
    "LindbladSyncEngine",
    "build_structured_ansatz",
    "BiologicalSurfaceCode",
    "BiologicalMWPMDecoder",
    "BiologicalSurfaceDiagnostics",
    "analyse_biological_surface_code",
    "BiologicalQecExecution",
    "BiologicalQecBatchExecution",
    "run_biological_qec_execution",
    "run_biological_qec_batch_execution",
    "DynamicCouplingEngine",
    "OMEGA_N_16",
    "build_knm_paper27",
    "build_kuramoto_ring",
    "build_knm_plasma",
    "build_knm_plasma_spec",
    "build_knm_plasma_from_config",
    "plasma_omega",
    "knm_to_hamiltonian",
    "knm_to_ansatz",
    "LockSignatureArtifact",
    "LayerStateArtifact",
    "UPDEPhaseArtifact",
    "PhaseOrchestratorAdapter",
    "ArcaneNeuronBridge",
    "SNNQuantumBridge",
    "spike_train_to_rotations",
    "quantum_measurement_to_current",
    "SSGFQuantumLoop",
    "ssgf_w_to_hamiltonian",
    "ssgf_state_to_quantum",
    "quantum_to_ssgf_state",
    "QuantumKuramotoSolver",
    "TrajectoryResult",
    "TrotterEvolutionConfig",
    "QuantumUPDESolver",
    "PhaseVQE",
    "HardwareRunner",
    "JobResult",
    "ForecastModelRun",
    "SynchronisationForecastBenchmarkResult",
    "SynchronisationForecastDataset",
    "load_hardware_kuramoto_4osc_trace",
    "load_ieee5bus_sync_forecast_case",
    "run_real_data_sync_forecast_benchmark",
    "run_real_data_sync_forecast_suite",
    "trapped_ion_noise_model",
    "transpile_for_trapped_ion",
    "QuantumDisruptionClassifier",
    "DisruptionBenchmark",
    "ITERFeatureSpec",
    "from_fusion_core_shot",
    "generate_synthetic_iter_data",
    "normalize_iter_features",
    "QAOA_MPC",
    "QuantumPetriNet",
    "QuantumPetriStepReport",
    "QuantumPetriCampaignReport",
    "CompilerADExecutableConfig",
    "CompilerADKernelVerification",
    "CompilerADTransformPlan",
    "DifferentiableMLIRCompileConfig",
    "ExecutableCompilerADKernel",
    "MLIRCompileConfig",
    "PrimitiveLoweringStatus",
    "MLIRModule",
    "build_compiler_ad_transform_plan",
    "compile_compiler_ad_transform_plan_to_mlir",
    "compile_custom_derivative_rule_to_executable",
    "compile_custom_derivative_rule_to_mlir",
    "compile_registered_primitive_to_executable",
    "compile_whole_program_ad_trace_to_mlir",
    "compile_kuramoto_to_mlir",
    "MonotonicRealtimeClock",
    "RealtimeRunResult",
    "RealtimeSLAConfig",
    "RealtimeSLAReport",
    "RealtimeRuntimeConfig",
    "RealtimeTickRecord",
    "VirtualRealtimeClock",
    "enforce_realtime_sla",
    "evaluate_realtime_sla",
    "run_realtime_control_loop",
    "CloudDeploymentSpec",
    "CloudManifestBundle",
    "ContainerResources",
    "generate_cloud_manifests",
    "AggregatorProviderRoute",
    "ResolvedAggregatorProviderRoute",
    "aggregator_provider_routes_for",
    "built_in_aggregator_provider_routes",
    "resolve_aggregator_provider_route",
    "AzureQuantumHALAdapter",
    "azure_openqasm3_to_workload",
    "BraketAwsHALAdapter",
    "BraketLocalHALAdapter",
    "braket_circuit_to_workload",
    "CirqLocalHALAdapter",
    "cirq_circuit_workload",
    "DWaveLeapHALAdapter",
    "dwave_bqm_workload",
    "IonQCloudHALAdapter",
    "ionq_qis_workload",
    "IQMHALAdapter",
    "iqm_qiskit_workload",
    "OQCHALAdapter",
    "oqc_openqasm3_workload",
    "PasqalPulserHALAdapter",
    "pulser_sequence_workload",
    "PennyLaneDeviceHALAdapter",
    "pennylane_gate_workload",
    "CapabilityDecisionStatus",
    "ProviderCapabilityDecision",
    "ProviderCapabilitySnapshot",
    "ProviderMetadataProbe",
    "AggregatorProviderOptionalDependencyRow",
    "ProviderOptionalDependencyRow",
    "assess_provider_capability_snapshot",
    "aggregator_provider_optional_dependency_matrix",
    "probe_aggregator_provider_capability",
    "provider_optional_dependency_matrix",
    "snapshot_from_azure_target",
    "snapshot_from_braket_device",
    "snapshot_from_dwave_solver",
    "snapshot_from_iqm_backend",
    "snapshot_from_ionq_backend",
    "snapshot_from_oqc_target",
    "snapshot_from_pasqal_target",
    "snapshot_from_quandela_processor",
    "snapshot_from_qiskit_runtime_backend",
    "snapshot_from_qbraid_device",
    "snapshot_from_quantinuum_backend",
    "snapshot_from_quera_bloqade",
    "snapshot_from_rigetti_qcs",
    "snapshot_from_strangeworks_backend",
    "QbraidRuntimeHALAdapter",
    "StrangeworksComputeHALAdapter",
    "QuandelaPercevalHALAdapter",
    "quandela_perceval_workload",
    "QuEraBloqadeHALAdapter",
    "QuantinuumCloudHALAdapter",
    "RigettiQCSHALAdapter",
    "bloqade_ahs_workload",
    "qbraid_program_to_workload",
    "quantinuum_tket_workload",
    "rigetti_quil_workload",
    "strangeworks_program_to_workload",
    "BackendCapabilities",
    "BackendProfile",
    "HardwareAbstractionLayer",
    "LocalDeterministicSimulator",
    "QuantumBackend",
    "QuantumJobRef",
    "QuantumJobResult",
    "QuantumWorkload",
    "built_in_backend_profiles",
    "QiskitAerHALAdapter",
    "QiskitRuntimeHALAdapter",
    "qiskit_circuit_to_qasm3_workload",
    "qiskit_circuit_to_workload",
    "VQLS_GradShafranov",
    "ArmijoLineSearchResult",
    "CustomDerivativeCheckResult",
    "CustomDerivativeRule",
    "CustomDerivativeRegistry",
    "DEFAULT_CUSTOM_DERIVATIVE_REGISTRY",
    "DifferentiableOptimizer",
    "FixedPointSensitivityResult",
    "FisherConjugateGradientResult",
    "FisherVectorProductResult",
    "GradientCheckResult",
    "GradientResult",
    "HVPResult",
    "HessianResult",
    "ImplicitSensitivityResult",
    "JVPResult",
    "JacobianResult",
    "LeastSquaresCovarianceResult",
    "LevenbergMarquardtDampingUpdate",
    "LevenbergMarquardtOptimizer",
    "LevenbergMarquardtResult",
    "LevenbergMarquardtStep",
    "LevenbergMarquardtTrial",
    "NaturalGradientOptimizationResult",
    "NaturalGradientOptimizer",
    "NaturalGradientResult",
    "OptimizationResult",
    "Parameter",
    "ParameterBounds",
    "ParameterShiftRule",
    "PrimitiveBatchingRule",
    "PrimitiveIdentity",
    "PrimitiveLoweringRule",
    "PrimitiveTransformRule",
    "ReverseNode",
    "ShotAllocationResult",
    "SparseMatrixResult",
    "StochasticGradientResult",
    "DualNumber",
    "VJPResult",
    "WeightedGradientResult",
    "TraceADScalar",
    "WholeProgramADResult",
    "WholeProgramIRNode",
    "WholeProgramTraceEvent",
    "allocate_parameter_shift_shots",
    "armijo_backtracking_line_search",
    "batch_complex_step_gradient",
    "batch_custom_jacobian",
    "batch_custom_jvp",
    "batch_custom_vjp",
    "batch_finite_difference_hvp",
    "batch_finite_difference_jvp",
    "batch_finite_difference_vjp",
    "batch_parameter_shift_gradient",
    "batch_value_and_finite_difference_grad",
    "batch_value_and_finite_difference_hvp",
    "batch_value_and_finite_difference_jvp",
    "batch_value_and_finite_difference_vjp",
    "batch_value_and_complex_step_grad",
    "batch_value_and_custom_jacobian",
    "batch_value_and_custom_jvp",
    "batch_value_and_custom_vjp",
    "batch_value_and_parameter_shift_grad",
    "batch_vector_jacobian_product",
    "check_custom_derivative_consistency",
    "check_parameter_shift_consistency",
    "complex_step_gradient",
    "custom_derivative_rule_for",
    "custom_gauss_newton_gradient",
    "custom_jacobian",
    "custom_jvp",
    "custom_levenberg_marquardt_step",
    "custom_vjp",
    "dual_cos",
    "dual_exp",
    "dual_log",
    "dual_sin",
    "dense_to_sparse_matrix",
    "empirical_fisher_conjugate_gradient",
    "empirical_fisher_metric",
    "empirical_fisher_vector_product",
    "evaluate_levenberg_marquardt_step",
    "finite_difference_gradient",
    "finite_difference_hessian",
    "finite_difference_hvp",
    "finite_difference_jacobian",
    "finite_difference_jvp",
    "finite_difference_vjp",
    "forward_mode_gradient",
    "gauss_newton_gradient",
    "grad",
    "huber_residual_weights",
    "hessian",
    "implicit_fixed_point_sensitivity",
    "implicit_stationary_sensitivity",
    "is_jax_autodiff_available",
    "jacfwd",
    "jacobian",
    "jacrev",
    "jax_value_and_grad",
    "least_squares_covariance",
    "levenberg_marquardt_step",
    "natural_gradient",
    "registered_custom_jacobian",
    "register_primitive_batching_rule",
    "register_primitive_lowering_rule",
    "register_primitive_transform_rule",
    "registered_custom_jvp",
    "registered_custom_vjp",
    "register_custom_derivative_rule",
    "reverse_cos",
    "reverse_exp",
    "reverse_log",
    "reverse_mode_gradient",
    "reverse_sin",
    "soft_l1_residual_weights",
    "sparse_empirical_fisher_metric",
    "sparse_hessian",
    "sparse_jacobian",
    "update_levenberg_marquardt_damping",
    "weighted_gradient_sum",
    "parameter_shift_gradient",
    "parameter_shift_gradient_with_uncertainty",
    "value_and_complex_step_grad",
    "value_and_custom_jacobian",
    "value_and_custom_jvp",
    "value_and_custom_vjp",
    "value_and_finite_difference_grad",
    "value_and_finite_difference_hessian",
    "value_and_finite_difference_hvp",
    "value_and_finite_difference_jacobian",
    "value_and_finite_difference_jvp",
    "value_and_forward_mode_grad",
    "value_and_grad",
    "whole_program_grad",
    "whole_program_trace_grad",
    "whole_program_trace_value_and_grad",
    "whole_program_value_and_grad",
    "vmap",
    "value_and_hessian",
    "value_and_jacfwd",
    "value_and_jacobian",
    "value_and_jacrev",
    "value_and_parameter_shift_grad",
    "value_and_reverse_mode_grad",
    "vector_jacobian_product",
    "ControlQEC",
    "FaultTolerantUPDE",
    "LogicalQubit",
    "SurfaceCodeSpec",
    "SurfaceCodeUPDE",
    "MultiscaleQECResult",
    "QECLevel",
    "build_multiscale_qec",
    "concatenated_logical_rate",
    "syndrome_flow_analysis",
    "ExecutionRegion",
    "QubitMappingResult",
    "dynq_initial_layout",
    "GUESSResult",
    "SymmetryDecayModel",
    "guess_extrapolate",
    "learn_symmetry_decay",
    "QuantumLIFNeuron",
    "QuantumSynapse",
    "QuantumSTDP",
    "QuantumDenseLayer",
    "QSNNTrainer",
    "CLAIM_BOUNDARY",
    "DynamicCouplingConfig",
    "NeuromorphicStepResult",
    "QuantumLIFConfig",
    "QuantumNeuromorphicBridge",
    "TraceSTDPConfig",
    "TraceSTDPState",
    "ZNEResult",
    "gate_fold_circuit",
    "zne_extrapolate",
    "PECResult",
    "pauli_twirl_decompose",
    "pec_sample",
    "IdentityAttractor",
    "ARCANE_SAPIENCE_SPEC",
    "ORCHESTRATOR_MAPPING",
    "build_identity_attractor",
    "orchestrator_to_quantum_phases",
    "quantum_to_orchestrator_phases",
    "solve_identity",
    "coherence_budget",
    "fidelity_at_depth",
    "chsh_from_statevector",
    "disposition_entanglement_map",
    "identity_fingerprint",
    "prove_identity",
    "verify_identity",
    "ClassicalBaselineRun",
    "available_baselines",
    "scipy_ode_baseline",
    "qutip_lindblad_baseline",
    "mps_tebd_baseline",
    "run_documented_classical_baselines",
    "AdvantageResult",
    "classical_benchmark",
    "quantum_benchmark",
    "estimate_crossover",
    "run_scaling_benchmark",
    "analysis",
    "applications",
    "forecasting",
    "gauge",
    "ssgf",
    "tcbo",
    "pgbo",
    "psi_field",
    "fep",
    "l16",
]
