# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# scpn-quantum-control — Unified Kuramoto toolkit facade
r"""Unified import surface for the Kuramoto toolkit.

Every classical-Kuramoto capability lives in :mod:`scpn_quantum_control.accel` as a focused,
single-responsibility module. This facade re-exports that whole surface under one import so a
caller writes ``from scpn_quantum_control.kuramoto import order_parameter, kuramoto_rk4_trajectory,
chimera_index`` rather than reaching into individual accelerator modules, and it adds a
**capability map** that organises the toolkit into coherent groups for discovery.

The groups are:

``forces``
    The instantaneous coupling forces ``F(θ)`` and their Jacobians — mean-field, networked,
    Sakaguchi, triadic, Daido, higher-order simplex / hyperedge, the heterogeneous mixer and the
    delayed forces.
``integrators``
    Time evolution of the phase flow — fixed-step Euler / RK4 and adaptive Dormand–Prince (each
    with a reverse-mode adjoint), plus the delayed, inertial, noisy and adaptive-coupling
    integrators and their trajectory containers.
``observables``
    The order parameter, mean phase, their network-local variants, the Daido generalised order
    parameter and the interaction energy, each with gradients / Hessians.
``diagnostics``
    Trajectory diagnostics — the frequency-locking indices, the chimera / metastability indices,
    the phase-distribution entropy and mutual information, the pairwise coherence matrices and the
    partial-synchronisation cluster metrics.
``analysis``
    Closed-form and spectral analysis — the synchronisation stability spectrum, the critical
    coupling, the Ott–Antonsen reduction, the Lyapunov spectrum, explosive-transition continuation,
    ring-state basins and the delayed / noisy mean-field theory.
``control_and_design``
    Terminal control objectives and their gradients, optimal-coupling and pinning design, and
    coupling system identification.
``types``
    The callable type aliases shared across the toolkit (forces, Jacobians, plasticity rules, …).
``dispatch``
    The multi-language dispatch core that selects the fastest available backend.
``tier_introspection``
    The ``last_*_tier_used`` helpers reporting which backend served the most recent call.

The facade is a thin re-export: every name resolves to exactly the object in
:mod:`scpn_quantum_control.accel`, so the two surfaces stay in lock-step (a parity guarded by the
test suite). Use :func:`capabilities` for the structured map and :func:`describe` for a readable
summary.
"""

from __future__ import annotations

from collections.abc import Mapping
from types import MappingProxyType

from .accel import (
    AdaptiveGradients,
    AdaptivePhaseForce,
    AdaptiveTrajectory,
    BasinEstimate,
    ChimeraDiagnostics,
    ClusterPartition,
    ContinuationBranch,
    CouplingDesignResult,
    CouplingProjection,
    CouplingTerm,
    DelayedForce,
    DelayedGradients,
    DelayedTrajectory,
    DopriTrajectory,
    FrequencyDensity,
    FrequencyOrder,
    HysteresisLoop,
    InertialGradients,
    InertialTrajectory,
    MeanFieldForce,
    MultiLangDispatcher,
    NoisyGradients,
    NoisyKuramotoRun,
    PhaseForce,
    PhaseJacobian,
    PhasePotential,
    PinningDesignResult,
    PlasticityRule,
    QifMeanFieldGradients,
    QifMeanFieldTrajectory,
    StabilitySpectrum,
    StochasticForce,
    SystemIdentificationResult,
    TerminalObjective,
    WatanabeStrogatzTrajectory,
    adaptive_state_sensitivity,
    adaptive_terminal_value_and_grad,
    adaptive_vector_field,
    available_tiers,
    chimera_diagnostics,
    chimera_index,
    chimera_index_gradient,
    cluster_count,
    cluster_partition,
    coherence_matrix,
    coherence_objective,
    coherence_spectrum,
    community_metastability,
    community_order_parameters,
    continuation_sweep,
    critical_coupling,
    daido_mean_field_force,
    daido_mean_field_jacobian,
    daido_mode_phase,
    daido_mode_phase_gradient,
    daido_mode_phase_hessian,
    daido_order_parameter,
    daido_order_parameter_gradient,
    daido_order_parameter_hessian,
    delayed_mean_field_force,
    delayed_networked_force,
    delayed_phase_sensitivity,
    delayed_terminal_value_and_grad,
    design_pinning,
    design_synchronising_coupling,
    dispatch,
    effective_frequencies,
    estimate_ring_basins,
    frequency_locked_fraction,
    frequency_order_diagnostics,
    frequency_synchronisation_index,
    frequency_synchronisation_index_gradient,
    gaussian_critical_coupling,
    gaussian_density,
    hebbian_adaptive_jacobian,
    hebbian_coupling_equilibrium,
    hebbian_plasticity_rate,
    heterogeneous_force,
    heterogeneous_force_components,
    heterogeneous_jacobian,
    hyperedge_force,
    hyperedge_jacobian,
    hyperedge_term,
    hysteresis_loop,
    inertial_energy,
    inertial_jacobian,
    inertial_state_sensitivity,
    inertial_terminal_value_and_grad,
    inertial_vector_field,
    integrate_adaptive_kuramoto,
    integrate_delayed_kuramoto,
    integrate_inertial,
    integrate_noisy_kuramoto,
    integrate_qif_mean_field,
    integrate_watanabe_strogatz,
    interaction_energy_objective,
    is_synchronisation_stable,
    is_synchronised_branch_stable,
    is_twisted_state_stable,
    kuramoto_dopri_trajectory,
    kuramoto_dopri_vjp,
    kuramoto_euler_trajectory,
    kuramoto_euler_vjp,
    kuramoto_interaction_energy,
    kuramoto_interaction_energy_gradient,
    kuramoto_interaction_energy_hessian,
    kuramoto_order_parameter_from_macro,
    kuramoto_rk4_trajectory,
    kuramoto_rk4_vjp,
    last_daido_gradient_tier_used,
    last_daido_hessian_tier_used,
    last_daido_mean_field_force_tier_used,
    last_daido_mean_field_jacobian_tier_used,
    last_daido_mode_phase_gradient_tier_used,
    last_daido_mode_phase_hessian_tier_used,
    last_daido_mode_phase_tier_used,
    last_daido_tier_used,
    last_gradient_tier_used,
    last_hessian_tier_used,
    last_kuramoto_euler_trajectory_tier_used,
    last_kuramoto_euler_vjp_tier_used,
    last_kuramoto_interaction_energy_gradient_tier_used,
    last_kuramoto_interaction_energy_hessian_tier_used,
    last_kuramoto_interaction_energy_tier_used,
    last_kuramoto_rk4_trajectory_tier_used,
    last_kuramoto_rk4_vjp_tier_used,
    last_local_mean_phase_jacobian_tier_used,
    last_local_mean_phase_tier_used,
    last_local_order_parameter_jacobian_tier_used,
    last_local_order_parameter_tier_used,
    last_mean_field_force_tier_used,
    last_mean_field_jacobian_tier_used,
    last_mean_phase_gradient_tier_used,
    last_mean_phase_hessian_tier_used,
    last_mean_phase_tier_used,
    last_networked_kuramoto_force_tier_used,
    last_networked_kuramoto_jacobian_tier_used,
    last_sakaguchi_force_tier_used,
    last_sakaguchi_jacobian_tier_used,
    last_sakaguchi_mean_field_force_tier_used,
    last_sakaguchi_mean_field_jacobian_tier_used,
    last_tier_used,
    last_triadic_mean_field_force_tier_used,
    last_triadic_mean_field_jacobian_tier_used,
    leading_coherence_eigenvector,
    learn_coupling,
    local_mean_phase,
    local_mean_phase_jacobian,
    local_order_parameter,
    local_order_parameter_jacobian,
    lorentzian_critical_coupling,
    lorentzian_density,
    lorentzian_noisy_critical_coupling,
    lorentzian_order_parameter,
    lyapunov_spectrum,
    macro_from_kuramoto_order_parameter,
    maximal_lyapunov_exponent,
    mean_coherence_matrix,
    mean_field_force,
    mean_field_jacobian,
    mean_phase,
    mean_phase_gradient,
    mean_phase_hessian,
    metastability_index,
    metastability_index_gradient,
    mutual_information_matrix,
    networked_kuramoto_force,
    networked_kuramoto_jacobian,
    noisy_critical_coupling,
    noisy_kuramoto_step,
    noisy_phase_sensitivity,
    noisy_stationary_order_parameter,
    noisy_terminal_value_and_grad,
    normalised_phase_entropy,
    optimise_coupling,
    order_parameter,
    order_parameter_gradient,
    order_parameter_hessian,
    ott_antonsen_field,
    ott_antonsen_order_parameter,
    ott_antonsen_steady_state,
    ott_antonsen_terminal_order_parameter_value_and_grad,
    ott_antonsen_trajectory,
    pairwise_mutual_information,
    pairwise_term,
    phase_clusters,
    phase_entropy,
    phase_entropy_series,
    phase_locking_matrix,
    phase_target_objective,
    pinning_coherence_value,
    pinning_coherence_value_and_grad,
    qif_mean_field_fixed_point,
    qif_mean_field_jacobian,
    qif_mean_field_rates,
    qif_mean_field_terminal_value_and_grad,
    qif_potential_from_theta,
    ring_coupling_matrix,
    sakaguchi_force,
    sakaguchi_jacobian,
    sakaguchi_mean_field_force,
    sakaguchi_mean_field_jacobian,
    simplex_mean_field_force,
    simplex_mean_field_jacobian,
    simplex_mean_field_term,
    stability_spectrum,
    stable_synchronised_frequencies,
    symmetric_nonnegative_projection,
    synchronisation_rate,
    synchronisation_value_and_grad,
    synchronised_branch_stability,
    synchronised_frequency_residual,
    synchronised_frequency_roots,
    synchronised_order_parameter,
    terminal_objective_value,
    terminal_objective_value_and_grad,
    theta_from_qif_potential,
    trajectory_match_value,
    trajectory_match_value_and_grad,
    triadic_hysteresis_loop,
    triadic_mean_field_force,
    triadic_mean_field_jacobian,
    twisted_state,
    twisted_state_eigenvalues,
    watanabe_strogatz_constants,
    watanabe_strogatz_invariant,
    watanabe_strogatz_order_parameter,
    watanabe_strogatz_phases,
    winding_number,
)

# The capability map — each group lists the public symbols (by name) of one coherent part of the
# toolkit. Its union is exactly ``scpn_quantum_control.accel.__all__`` (parity guarded by the
# test suite), so it doubles as the facade's authoritative directory of contents.
_CAPABILITIES: dict[str, tuple[str, ...]] = {
    "forces": (
        "mean_field_force",
        "mean_field_jacobian",
        "networked_kuramoto_force",
        "networked_kuramoto_jacobian",
        "sakaguchi_force",
        "sakaguchi_jacobian",
        "sakaguchi_mean_field_force",
        "sakaguchi_mean_field_jacobian",
        "triadic_mean_field_force",
        "triadic_mean_field_jacobian",
        "daido_mean_field_force",
        "daido_mean_field_jacobian",
        "simplex_mean_field_force",
        "simplex_mean_field_jacobian",
        "hyperedge_force",
        "hyperedge_jacobian",
        "heterogeneous_force",
        "heterogeneous_force_components",
        "heterogeneous_jacobian",
        "CouplingTerm",
        "pairwise_term",
        "hyperedge_term",
        "simplex_mean_field_term",
        "delayed_mean_field_force",
        "delayed_networked_force",
        "qif_mean_field_rates",
        "qif_mean_field_jacobian",
    ),
    "integrators": (
        "kuramoto_euler_trajectory",
        "kuramoto_euler_vjp",
        "kuramoto_rk4_trajectory",
        "kuramoto_rk4_vjp",
        "kuramoto_dopri_trajectory",
        "kuramoto_dopri_vjp",
        "DopriTrajectory",
        "integrate_delayed_kuramoto",
        "delayed_phase_sensitivity",
        "DelayedTrajectory",
        "integrate_inertial",
        "InertialTrajectory",
        "inertial_vector_field",
        "inertial_jacobian",
        "inertial_energy",
        "inertial_state_sensitivity",
        "integrate_noisy_kuramoto",
        "noisy_kuramoto_step",
        "noisy_phase_sensitivity",
        "NoisyKuramotoRun",
        "integrate_adaptive_kuramoto",
        "AdaptiveTrajectory",
        "adaptive_vector_field",
        "hebbian_adaptive_jacobian",
        "hebbian_coupling_equilibrium",
        "hebbian_plasticity_rate",
        "adaptive_state_sensitivity",
        "ott_antonsen_trajectory",
        "integrate_qif_mean_field",
        "QifMeanFieldTrajectory",
        "integrate_watanabe_strogatz",
        "WatanabeStrogatzTrajectory",
    ),
    "observables": (
        "order_parameter",
        "order_parameter_gradient",
        "order_parameter_hessian",
        "mean_phase",
        "mean_phase_gradient",
        "mean_phase_hessian",
        "local_order_parameter",
        "local_order_parameter_jacobian",
        "local_mean_phase",
        "local_mean_phase_jacobian",
        "daido_order_parameter",
        "daido_order_parameter_gradient",
        "daido_order_parameter_hessian",
        "daido_mode_phase",
        "daido_mode_phase_gradient",
        "daido_mode_phase_hessian",
        "kuramoto_interaction_energy",
        "kuramoto_interaction_energy_gradient",
        "kuramoto_interaction_energy_hessian",
    ),
    "diagnostics": (
        "FrequencyOrder",
        "effective_frequencies",
        "frequency_synchronisation_index",
        "frequency_synchronisation_index_gradient",
        "frequency_locked_fraction",
        "frequency_order_diagnostics",
        "ChimeraDiagnostics",
        "chimera_index",
        "chimera_index_gradient",
        "chimera_diagnostics",
        "metastability_index",
        "metastability_index_gradient",
        "community_metastability",
        "community_order_parameters",
        "phase_entropy",
        "normalised_phase_entropy",
        "phase_entropy_series",
        "pairwise_mutual_information",
        "mutual_information_matrix",
        "coherence_matrix",
        "mean_coherence_matrix",
        "phase_locking_matrix",
        "coherence_spectrum",
        "leading_coherence_eigenvector",
        "ClusterPartition",
        "phase_clusters",
        "cluster_count",
        "cluster_partition",
    ),
    "analysis": (
        "StabilitySpectrum",
        "stability_spectrum",
        "is_synchronisation_stable",
        "synchronisation_rate",
        "critical_coupling",
        "gaussian_critical_coupling",
        "lorentzian_critical_coupling",
        "gaussian_density",
        "lorentzian_density",
        "lorentzian_order_parameter",
        "synchronised_order_parameter",
        "ott_antonsen_field",
        "ott_antonsen_order_parameter",
        "ott_antonsen_steady_state",
        "ott_antonsen_terminal_order_parameter_value_and_grad",
        "lyapunov_spectrum",
        "maximal_lyapunov_exponent",
        "ContinuationBranch",
        "HysteresisLoop",
        "continuation_sweep",
        "hysteresis_loop",
        "triadic_hysteresis_loop",
        "BasinEstimate",
        "estimate_ring_basins",
        "ring_coupling_matrix",
        "twisted_state",
        "twisted_state_eigenvalues",
        "is_twisted_state_stable",
        "winding_number",
        "synchronised_frequency_roots",
        "synchronised_frequency_residual",
        "synchronised_branch_stability",
        "is_synchronised_branch_stable",
        "stable_synchronised_frequencies",
        "noisy_critical_coupling",
        "lorentzian_noisy_critical_coupling",
        "noisy_stationary_order_parameter",
        "qif_mean_field_fixed_point",
        "kuramoto_order_parameter_from_macro",
        "macro_from_kuramoto_order_parameter",
        "qif_potential_from_theta",
        "theta_from_qif_potential",
        "watanabe_strogatz_constants",
        "watanabe_strogatz_phases",
        "watanabe_strogatz_order_parameter",
        "watanabe_strogatz_invariant",
    ),
    "control_and_design": (
        "terminal_objective_value",
        "terminal_objective_value_and_grad",
        "coherence_objective",
        "phase_target_objective",
        "interaction_energy_objective",
        "synchronisation_value_and_grad",
        "CouplingDesignResult",
        "optimise_coupling",
        "design_synchronising_coupling",
        "symmetric_nonnegative_projection",
        "PinningDesignResult",
        "design_pinning",
        "pinning_coherence_value",
        "pinning_coherence_value_and_grad",
        "SystemIdentificationResult",
        "learn_coupling",
        "trajectory_match_value",
        "trajectory_match_value_and_grad",
        "InertialGradients",
        "inertial_terminal_value_and_grad",
        "AdaptiveGradients",
        "adaptive_terminal_value_and_grad",
        "NoisyGradients",
        "noisy_terminal_value_and_grad",
        "DelayedGradients",
        "delayed_terminal_value_and_grad",
        "qif_mean_field_terminal_value_and_grad",
        "QifMeanFieldGradients",
    ),
    "types": (
        "PhaseForce",
        "PhaseJacobian",
        "MeanFieldForce",
        "DelayedForce",
        "AdaptivePhaseForce",
        "PlasticityRule",
        "StochasticForce",
        "CouplingProjection",
        "FrequencyDensity",
        "PhasePotential",
        "TerminalObjective",
    ),
    "dispatch": (
        "MultiLangDispatcher",
        "available_tiers",
        "dispatch",
    ),
    "tier_introspection": (
        "last_daido_gradient_tier_used",
        "last_daido_hessian_tier_used",
        "last_daido_mean_field_force_tier_used",
        "last_daido_mean_field_jacobian_tier_used",
        "last_daido_mode_phase_gradient_tier_used",
        "last_daido_mode_phase_hessian_tier_used",
        "last_daido_mode_phase_tier_used",
        "last_daido_tier_used",
        "last_gradient_tier_used",
        "last_hessian_tier_used",
        "last_kuramoto_euler_trajectory_tier_used",
        "last_kuramoto_euler_vjp_tier_used",
        "last_kuramoto_interaction_energy_gradient_tier_used",
        "last_kuramoto_interaction_energy_hessian_tier_used",
        "last_kuramoto_interaction_energy_tier_used",
        "last_kuramoto_rk4_trajectory_tier_used",
        "last_kuramoto_rk4_vjp_tier_used",
        "last_local_mean_phase_jacobian_tier_used",
        "last_local_mean_phase_tier_used",
        "last_local_order_parameter_jacobian_tier_used",
        "last_local_order_parameter_tier_used",
        "last_mean_field_force_tier_used",
        "last_mean_field_jacobian_tier_used",
        "last_mean_phase_gradient_tier_used",
        "last_mean_phase_hessian_tier_used",
        "last_mean_phase_tier_used",
        "last_networked_kuramoto_force_tier_used",
        "last_networked_kuramoto_jacobian_tier_used",
        "last_sakaguchi_force_tier_used",
        "last_sakaguchi_jacobian_tier_used",
        "last_sakaguchi_mean_field_force_tier_used",
        "last_sakaguchi_mean_field_jacobian_tier_used",
        "last_tier_used",
        "last_triadic_mean_field_force_tier_used",
        "last_triadic_mean_field_jacobian_tier_used",
    ),
}

#: The Kuramoto capability map: an immutable view of the coherent groups, each a tuple of the
#: public symbol names that group exposes. Its union is exactly the re-exported toolkit.
KURAMOTO_CAPABILITIES: Mapping[str, tuple[str, ...]] = MappingProxyType(_CAPABILITIES)


def capabilities() -> Mapping[str, tuple[str, ...]]:
    """Return the immutable Kuramoto capability map (group name → public symbol names)."""
    return KURAMOTO_CAPABILITIES


def describe(category: str | None = None) -> str:
    """Return a readable summary of the toolkit's capabilities.

    Parameters
    ----------
    category : str, optional
        A capability group name. When omitted, a one-line-per-group overview with symbol counts
        is returned; when given, the symbols of that group are listed one per line.

    Returns
    -------
    str
        The overview, or the named group's symbols.

    Raises
    ------
    ValueError
        If ``category`` is not one of the capability groups.
    """
    if category is None:
        return "\n".join(
            f"{group}: {len(symbols)} symbols" for group, symbols in KURAMOTO_CAPABILITIES.items()
        )
    if category not in KURAMOTO_CAPABILITIES:
        groups = ", ".join(KURAMOTO_CAPABILITIES)
        raise ValueError(f"unknown capability group {category!r}; choose one of: {groups}")
    return "\n".join(KURAMOTO_CAPABILITIES[category])


__all__ = [
    "WatanabeStrogatzTrajectory",
    "integrate_watanabe_strogatz",
    "watanabe_strogatz_constants",
    "watanabe_strogatz_invariant",
    "watanabe_strogatz_order_parameter",
    "watanabe_strogatz_phases",
    "QifMeanFieldGradients",
    "QifMeanFieldTrajectory",
    "integrate_qif_mean_field",
    "kuramoto_order_parameter_from_macro",
    "macro_from_kuramoto_order_parameter",
    "qif_mean_field_fixed_point",
    "qif_mean_field_jacobian",
    "qif_mean_field_rates",
    "qif_mean_field_terminal_value_and_grad",
    "qif_potential_from_theta",
    "theta_from_qif_potential",
    "AdaptiveGradients",
    "AdaptivePhaseForce",
    "AdaptiveTrajectory",
    "BasinEstimate",
    "ChimeraDiagnostics",
    "ClusterPartition",
    "ContinuationBranch",
    "CouplingDesignResult",
    "CouplingProjection",
    "CouplingTerm",
    "DelayedForce",
    "DelayedGradients",
    "DelayedTrajectory",
    "DopriTrajectory",
    "FrequencyDensity",
    "FrequencyOrder",
    "HysteresisLoop",
    "InertialTrajectory",
    "MeanFieldForce",
    "MultiLangDispatcher",
    "NoisyGradients",
    "NoisyKuramotoRun",
    "PhaseForce",
    "PhaseJacobian",
    "PhasePotential",
    "PinningDesignResult",
    "PlasticityRule",
    "StabilitySpectrum",
    "StochasticForce",
    "SystemIdentificationResult",
    "TerminalObjective",
    "adaptive_state_sensitivity",
    "adaptive_terminal_value_and_grad",
    "adaptive_vector_field",
    "available_tiers",
    "chimera_diagnostics",
    "chimera_index",
    "chimera_index_gradient",
    "cluster_count",
    "cluster_partition",
    "coherence_matrix",
    "coherence_objective",
    "coherence_spectrum",
    "community_metastability",
    "community_order_parameters",
    "continuation_sweep",
    "critical_coupling",
    "daido_mean_field_force",
    "daido_mean_field_jacobian",
    "daido_mode_phase",
    "daido_mode_phase_gradient",
    "daido_mode_phase_hessian",
    "daido_order_parameter",
    "daido_order_parameter_gradient",
    "daido_order_parameter_hessian",
    "delayed_mean_field_force",
    "delayed_networked_force",
    "delayed_phase_sensitivity",
    "delayed_terminal_value_and_grad",
    "design_pinning",
    "design_synchronising_coupling",
    "dispatch",
    "effective_frequencies",
    "estimate_ring_basins",
    "frequency_locked_fraction",
    "frequency_order_diagnostics",
    "frequency_synchronisation_index",
    "frequency_synchronisation_index_gradient",
    "gaussian_critical_coupling",
    "gaussian_density",
    "hebbian_adaptive_jacobian",
    "hebbian_coupling_equilibrium",
    "hebbian_plasticity_rate",
    "heterogeneous_force",
    "heterogeneous_force_components",
    "heterogeneous_jacobian",
    "hyperedge_force",
    "hyperedge_jacobian",
    "hyperedge_term",
    "hysteresis_loop",
    "InertialGradients",
    "inertial_energy",
    "inertial_jacobian",
    "inertial_state_sensitivity",
    "inertial_terminal_value_and_grad",
    "inertial_vector_field",
    "integrate_adaptive_kuramoto",
    "integrate_delayed_kuramoto",
    "integrate_inertial",
    "integrate_noisy_kuramoto",
    "interaction_energy_objective",
    "is_synchronisation_stable",
    "is_synchronised_branch_stable",
    "is_twisted_state_stable",
    "kuramoto_dopri_trajectory",
    "kuramoto_dopri_vjp",
    "kuramoto_euler_trajectory",
    "kuramoto_euler_vjp",
    "kuramoto_interaction_energy",
    "kuramoto_interaction_energy_gradient",
    "kuramoto_interaction_energy_hessian",
    "kuramoto_rk4_trajectory",
    "kuramoto_rk4_vjp",
    "last_daido_gradient_tier_used",
    "last_daido_hessian_tier_used",
    "last_daido_mean_field_force_tier_used",
    "last_daido_mean_field_jacobian_tier_used",
    "last_daido_mode_phase_gradient_tier_used",
    "last_daido_mode_phase_hessian_tier_used",
    "last_daido_mode_phase_tier_used",
    "last_daido_tier_used",
    "last_gradient_tier_used",
    "last_hessian_tier_used",
    "last_kuramoto_euler_trajectory_tier_used",
    "last_kuramoto_euler_vjp_tier_used",
    "last_kuramoto_interaction_energy_gradient_tier_used",
    "last_kuramoto_interaction_energy_hessian_tier_used",
    "last_kuramoto_interaction_energy_tier_used",
    "last_kuramoto_rk4_trajectory_tier_used",
    "last_kuramoto_rk4_vjp_tier_used",
    "last_local_mean_phase_jacobian_tier_used",
    "last_local_mean_phase_tier_used",
    "last_local_order_parameter_jacobian_tier_used",
    "last_local_order_parameter_tier_used",
    "last_mean_field_force_tier_used",
    "last_mean_field_jacobian_tier_used",
    "last_mean_phase_gradient_tier_used",
    "last_mean_phase_hessian_tier_used",
    "last_mean_phase_tier_used",
    "last_networked_kuramoto_force_tier_used",
    "last_networked_kuramoto_jacobian_tier_used",
    "last_sakaguchi_force_tier_used",
    "last_sakaguchi_jacobian_tier_used",
    "last_sakaguchi_mean_field_force_tier_used",
    "last_sakaguchi_mean_field_jacobian_tier_used",
    "last_tier_used",
    "last_triadic_mean_field_force_tier_used",
    "last_triadic_mean_field_jacobian_tier_used",
    "leading_coherence_eigenvector",
    "learn_coupling",
    "local_mean_phase",
    "local_mean_phase_jacobian",
    "local_order_parameter",
    "local_order_parameter_jacobian",
    "lorentzian_critical_coupling",
    "lorentzian_density",
    "lorentzian_noisy_critical_coupling",
    "lorentzian_order_parameter",
    "lyapunov_spectrum",
    "maximal_lyapunov_exponent",
    "mean_coherence_matrix",
    "mean_field_force",
    "mean_field_jacobian",
    "mean_phase",
    "mean_phase_gradient",
    "mean_phase_hessian",
    "metastability_index",
    "metastability_index_gradient",
    "mutual_information_matrix",
    "networked_kuramoto_force",
    "networked_kuramoto_jacobian",
    "noisy_critical_coupling",
    "noisy_kuramoto_step",
    "noisy_phase_sensitivity",
    "noisy_stationary_order_parameter",
    "noisy_terminal_value_and_grad",
    "normalised_phase_entropy",
    "optimise_coupling",
    "order_parameter",
    "order_parameter_gradient",
    "order_parameter_hessian",
    "ott_antonsen_field",
    "ott_antonsen_order_parameter",
    "ott_antonsen_steady_state",
    "ott_antonsen_terminal_order_parameter_value_and_grad",
    "ott_antonsen_trajectory",
    "pairwise_mutual_information",
    "pairwise_term",
    "phase_clusters",
    "phase_entropy",
    "phase_entropy_series",
    "phase_locking_matrix",
    "phase_target_objective",
    "pinning_coherence_value",
    "pinning_coherence_value_and_grad",
    "ring_coupling_matrix",
    "sakaguchi_force",
    "sakaguchi_jacobian",
    "sakaguchi_mean_field_force",
    "sakaguchi_mean_field_jacobian",
    "simplex_mean_field_force",
    "simplex_mean_field_jacobian",
    "simplex_mean_field_term",
    "stability_spectrum",
    "stable_synchronised_frequencies",
    "symmetric_nonnegative_projection",
    "synchronisation_rate",
    "synchronisation_value_and_grad",
    "synchronised_branch_stability",
    "synchronised_frequency_residual",
    "synchronised_frequency_roots",
    "synchronised_order_parameter",
    "terminal_objective_value",
    "terminal_objective_value_and_grad",
    "trajectory_match_value",
    "trajectory_match_value_and_grad",
    "triadic_hysteresis_loop",
    "triadic_mean_field_force",
    "triadic_mean_field_jacobian",
    "twisted_state",
    "twisted_state_eigenvalues",
    "winding_number",
    "KURAMOTO_CAPABILITIES",
    "capabilities",
    "describe",
]
