# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# (c) Concepts 1996-2026 Miroslav Sotek. All rights reserved.
# (c) Code 2020-2026 Miroslav Sotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Quantum Control -- Paper 0 promotion gate tests
"""Tests for Paper 0 promotion artefact acceptance gates."""

from __future__ import annotations

import json
from pathlib import Path

from scripts.gate_paper0_promotion_slice import gate_promotion_slice, write_gate_result


def test_gate_accepts_consistent_generated_artefacts(tmp_path: Path) -> None:
    spec = _write_json(tmp_path / "spec.json", _spec_payload())
    fixture = _write_json(tmp_path / "fixture.json", _fixture_payload())
    reconciliation = _write_json(tmp_path / "reconciliation.json", _reconciliation_payload())
    public_file = tmp_path / "public.py"
    public_file.write_text("# public Arcane Sapience surface\n", encoding="utf-8")

    result = gate_promotion_slice(
        spec_bundle_path=spec,
        fixture_path=fixture,
        reconciliation_path=reconciliation,
        public_paths=(public_file,),
    )

    assert result.passed is True
    assert result.source_start == "P0R10000"
    assert result.source_end == "P0R10002"
    assert result.source_record_count == 3
    assert result.spec_count == 1
    assert result.failures == ()


def test_gate_rejects_span_drift_and_public_agent_terms(tmp_path: Path) -> None:
    payload = _spec_payload()
    payload["summary"]["source_record_count"] = 4
    spec = _write_json(tmp_path / "spec.json", payload)
    public_file = tmp_path / "public.py"
    internal_agent_term = "Co" + "dex"
    public_file.write_text(f"# generated by {internal_agent_term}\n", encoding="utf-8")

    result = gate_promotion_slice(spec_bundle_path=spec, public_paths=(public_file,))

    assert result.passed is False
    assert "spec source_record_count must equal numeric source span length" in result.failures
    assert any(
        f"contains internal agent/vendor term {internal_agent_term}" in failure
        for failure in result.failures
    )


def test_gate_rejects_incomplete_spec_consumption(tmp_path: Path) -> None:
    payload = _spec_payload()
    payload["summary"]["coverage_match"] = False
    payload["summary"]["unconsumed_source_ledger_ids"] = ["P0R10002"]
    payload["specs"][0]["source_ledger_ids"] = ["P0R10000", "P0R10001"]
    spec = _write_json(tmp_path / "spec.json", payload)

    result = gate_promotion_slice(spec_bundle_path=spec)

    assert result.passed is False
    assert "spec coverage_match must be true" in result.failures
    assert "unconsumed_source_ledger_ids must be empty" in result.failures
    assert any("source_ledger_ids must exactly equal" in failure for failure in result.failures)


def _write_json(path: Path, payload: dict[str, object]) -> Path:
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return path


def _spec_payload() -> dict[str, object]:
    return {
        "summary": {
            "source_ledger_span": ["P0R10000", "P0R10002"],
            "source_record_count": 3,
            "consumed_source_record_count": 3,
            "coverage_match": True,
            "unconsumed_source_ledger_ids": [],
            "spec_count": 1,
            "claim_boundary": "source-bounded fixture; not validation evidence",
            "hardware_status": "source_methodology_no_experiment",
            "next_source_boundary": "P0R10003",
        },
        "specs": [
            {
                "key": "example.slice",
                "source_ledger_ids": ["P0R10000", "P0R10001", "P0R10002"],
                "claim_boundary": "source-bounded fixture; not validation evidence",
                "hardware_status": "source_methodology_no_experiment",
                "canonical_statement": "Example source-bounded statement.",
                "null_controls": ["not evidence"],
            }
        ],
    }


def _fixture_payload() -> dict[str, object]:
    return {
        "source_ledger_span": ["P0R10000", "P0R10002"],
        "source_record_count": 3,
        "component_count": 1,
        "hardware_status": "source_methodology_no_experiment",
        "claim_boundary": "source-bounded fixture; not validation evidence",
        "next_source_boundary": "P0R10003",
    }


def _reconciliation_payload() -> dict[str, object]:
    return {
        "summary": {
            "missing_surface_count": 0,
            "overlap_count": 0,
            "promoted_surface_integrity": True,
        }
    }


def test_write_gate_result_persists_audit_json(tmp_path: Path) -> None:
    spec = _write_json(tmp_path / "spec.json", _spec_payload())
    result = gate_promotion_slice(spec_bundle_path=spec)

    output = write_gate_result(result, tmp_path / "gate.json")
    payload = json.loads(output.read_text(encoding="utf-8"))

    assert payload["passed"] is True
    assert payload["source_start"] == "P0R10000"
    assert payload["source_end"] == "P0R10002"
