# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Quantum Control — CI build-environment closure audit tests
"""Tests for the lock-faithful Hatchling build-environment audit."""

from __future__ import annotations

import importlib.metadata
import runpy
import sys
from pathlib import Path
from types import ModuleType

import pytest

from tools import audit_ci_build_environment as build_audit

REPO_ROOT = Path(__file__).resolve().parents[1]


def _project(*, root: bool = False, backend: str = build_audit.BUILD_BACKEND) -> str:
    """Return minimal valid Hatchling project metadata for replay tests."""
    optional = (
        '\n[project.optional-dependencies]\ndev = ["hatchling>=1.27,<2.0"]\n' if root else ""
    )
    return f'[build-system]\nrequires = ["hatchling"]\nbuild-backend = "{backend}"\n{optional}'


def _lock_stanza(expected: build_audit.ExpectedBuildPin) -> str:
    """Render one canonical pip-compile build-tool stanza."""
    digests = sorted(expected.hashes)
    lines = [f"{expected.name}=={expected.version} \\"]
    for index, digest in enumerate(digests):
        suffix = " \\" if index < len(digests) - 1 else ""
        lines.append(f"    --hash=sha256:{digest}{suffix}")
    lines.append("    # via -r requirements-dev.txt")
    return "\n".join(lines)


def _lock(python_version: str, path: str) -> str:
    """Render a complete minimal lock accepted by the policy audit."""
    header = (
        f"# This file is autogenerated by pip-compile with Python {python_version}\n"
        "# by the following command:\n"
        f"#    pip-compile --allow-unsafe --generate-hashes --output-file={path} "
        "requirements-dev.txt\n"
    )
    return header + "\n\n".join(_lock_stanza(pin) for pin in build_audit.EXPECTED_BUILD_PINS)


def _ci() -> str:
    """Render the policy-relevant CI matrix and audit command."""
    mappings = "\n".join(
        f'          - python-version: "{version}"\n            requirements-file: {path}'
        for version, path in build_audit.LOCKS_BY_PYTHON
    )
    return (
        "jobs:\n"
        "  test:\n"
        f"{mappings}\n"
        f"      - run: {build_audit.LOCK_INSTALL_COMMAND}\n"
        f"      - run: {build_audit.AUDIT_COMMAND}\n"
        f"{build_audit.SECURITY_JOB_ENVIRONMENT}\n"
    )


def _write_replay_repository(root: Path) -> None:
    """Write a complete offline repository replay for the public audit."""
    (root / "oscillatools").mkdir()
    (root / ".github" / "workflows").mkdir(parents=True)
    (root / "tests").mkdir()
    (root / "pyproject.toml").write_text(_project(root=True), encoding="utf-8")
    (root / "oscillatools" / "pyproject.toml").write_text(_project(), encoding="utf-8")
    (root / build_audit.DEVELOPMENT_INPUT).write_text(
        "-r requirements.txt\n"
        + "\n".join(f"{pin.name}=={pin.version}" for pin in build_audit.EXPECTED_BUILD_PINS)
        + "\n",
        encoding="utf-8",
    )
    for version, path in build_audit.LOCKS_BY_PYTHON:
        (root / path).write_text(_lock(version, path), encoding="utf-8")
    (root / build_audit.CI_WORKFLOW_PATH).write_text(_ci(), encoding="utf-8")
    (root / build_audit.DOCKERFILE_PATH).write_text(
        f"RUN {build_audit.DOCKER_INSTALL_COMMAND}\n",
        encoding="utf-8",
    )
    (root / build_audit.WHEEL_TEST_PATH).write_text(
        'command = ["--wheel", "--no-isolation"]\n',
        encoding="utf-8",
    )


def test_live_repository_has_a_complete_hatchling_build_environment() -> None:
    """The checkout and active environment must satisfy the full contract."""
    result = build_audit.audit_repository(REPO_ROOT)

    assert result.passed
    assert result.errors == ()


def test_complete_offline_repository_replay_passes(tmp_path: Path) -> None:
    """A minimal complete repository must pass without resolver access."""
    _write_replay_repository(tmp_path)

    result = build_audit.audit_repository(tmp_path)

    assert result == build_audit.BuildEnvironmentAuditResult(errors=())
    assert "CI build-environment audit: PASS" in build_audit.format_result(result)


def test_cli_and_script_entrypoint_report_a_complete_repository(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    """Both CLI entry paths must execute the complete repository audit."""
    _write_replay_repository(tmp_path)

    assert build_audit.main(["--repo-root", str(tmp_path)]) == 0
    assert f"Hatchling {build_audit.HATCHLING_VERSION}" in capsys.readouterr().out

    original_argv = sys.argv
    script = REPO_ROOT / "tools" / "audit_ci_build_environment.py"
    try:
        sys.argv = [str(script), "--repo-root", str(tmp_path)]
        with pytest.raises(SystemExit) as exc_info:
            runpy.run_path(str(script), run_name="__main__")
    finally:
        sys.argv = original_argv
    assert exc_info.value.code == 0


def test_project_metadata_rejects_malformed_and_incomplete_contracts() -> None:
    """Malformed TOML, backend, requirement, and dev-extra drift must fail."""
    assert (
        "not valid TOML"
        in build_audit.audit_project_metadata("pyproject.toml", "[build-system")[0]
    )
    assert build_audit.audit_project_metadata("pyproject.toml", "[project]\n") == (
        "pyproject.toml has no valid [build-system] table",
    )
    wrong = (
        '[build-system]\nrequires = ["hatchling<1", "bad req @"]\n'
        'build-backend = "setuptools.build_meta"\n'
        "[project]\noptional-dependencies = 4\n"
    )
    errors = build_audit.audit_project_metadata("pyproject.toml", wrong)
    assert "build backend must be hatchling.build" in errors[0]
    assert any("invalid requirement" in error for error in errors)
    assert any("does not admit" in error for error in errors)
    assert errors[-1].endswith("dev must be a string array")

    invalid_array = '[build-system]\nrequires = "hatchling"\nbuild-backend = "hatchling.build"\n'
    assert build_audit.audit_project_metadata("oscillatools/pyproject.toml", invalid_array) == (
        "oscillatools/pyproject.toml build-system.requires must be a string array",
    )
    duplicate = (
        '[build-system]\nrequires = ["hatchling", "Hatchling>=1"]\n'
        'build-backend = "hatchling.build"\n'
    )
    assert (
        "found 2"
        in build_audit.audit_project_metadata("oscillatools/pyproject.toml", duplicate)[0]
    )


def test_development_input_requires_unique_exact_build_pins() -> None:
    """Missing, duplicate, ranged, wrong, and malformed direct pins must fail."""
    valid = "# comment\n-r requirements.txt\n\nBuild==1.5.1\nhatchling==1.31.0\n"
    assert build_audit.audit_development_input(valid) == ()
    assert build_audit.parse_direct_requirements(valid)[0].name == "Build"

    errors = build_audit.audit_development_input(
        "build>=1\nhatchling==1.30.0\nhatchling==1.31.0\n"
    )
    assert "build==1.5.1" in errors[0]
    assert "found 2" in errors[1]
    missing = build_audit.audit_development_input("build==1.5.1\n")
    assert "found 0" in missing[0]
    malformed = build_audit.audit_development_input("build==1.5.1\nnot a req @\n")
    assert "invalid direct requirement on line 2" in malformed[0]


def test_lock_parser_preserves_version_hashes_and_direct_owner() -> None:
    """The lock parser must retain every build-tool supply-chain field."""
    expected = build_audit.EXPECTED_BUILD_PINS[1]
    next_stanza = (
        f"cachecontrol[filecache]==0.14.4 \\\n    --hash=sha256:{'0' * 64}\n    # via pip-audit"
    )
    pin = build_audit.parse_lock_pin(f"{_lock_stanza(expected)}\n{next_stanza}", expected.name)

    assert pin == build_audit.LockPin(
        version=expected.version,
        hashes=expected.hashes,
        owners=frozenset({"-r requirements-dev.txt"}),
    )
    block_owner = _lock_stanza(expected).replace(
        "# via -r requirements-dev.txt",
        "# via\n    #   -r requirements-dev.txt",
    )
    assert build_audit.parse_lock_pin(block_owner, expected.name).owners == frozenset(
        {"-r requirements-dev.txt"}
    )


def test_lock_parser_rejects_missing_duplicate_unhashed_and_invalid_pins() -> None:
    """Every missing or ambiguous hash-pinned stanza must fail closed."""
    expected = build_audit.EXPECTED_BUILD_PINS[1]
    stanza = _lock_stanza(expected)
    with pytest.raises(ValueError, match="found 0"):
        build_audit.parse_lock_pin("wheel==0.46.3\n", expected.name)
    with pytest.raises(ValueError, match="found 2"):
        build_audit.parse_lock_pin(f"{stanza}\n{stanza}\n", expected.name)
    with pytest.raises(ValueError, match="has no sha256"):
        build_audit.parse_lock_pin(f"{expected.name}=={expected.version}\n", expected.name)
    invalid = stanza.replace(next(iter(expected.hashes)), "z" * 64)
    with pytest.raises(ValueError, match="invalid sha256"):
        build_audit.parse_lock_pin(invalid, expected.name)


def test_lock_audit_rejects_provenance_pin_hash_and_owner_drift() -> None:
    """All three interpreter locks must retain the same canonical closure."""
    lock_texts = {path: _lock(version, path) for version, path in build_audit.LOCKS_BY_PYTHON}
    assert build_audit.audit_lockfiles(lock_texts) == ()

    first_version, first_path = build_audit.LOCKS_BY_PYTHON[0]
    bad = lock_texts[first_path]
    bad = bad.replace(f"Python {first_version}", "Python 3.10")
    bad = bad.replace(f"--output-file={first_path}", "--output-file=wrong.txt")
    bad = bad.replace("build==1.5.1", "build==1.5.0")
    bad = bad.replace(next(iter(build_audit.EXPECTED_BUILD_PINS[0].hashes)), "0" * 64)
    bad = bad.replace("# via -r requirements-dev.txt", "# via transitive-owner", 1)
    bad = bad.replace(_lock_stanza(build_audit.EXPECTED_BUILD_PINS[1]), "")
    errors = build_audit.audit_lockfiles({first_path: bad})
    assert any("provenance" in error for error in errors)
    assert any("canonical pip-compile command" in error for error in errors)
    assert any("found 1.5.0" in error for error in errors)
    assert any("distribution hashes drifted" in error for error in errors)
    assert any("pin owners drifted" in error for error in errors)
    assert any("expected one hatchling pin, found 0" in error for error in errors)
    assert sum(error.startswith("missing CI lock") for error in errors) == 2


def test_installed_backend_rejects_missing_wrong_and_unimportable_hatchling() -> None:
    """The active interpreter must load the exact backend installed by its lock."""
    module = ModuleType(build_audit.BUILD_BACKEND)
    assert (
        build_audit.audit_installed_backend(
            version_loader=lambda _name: build_audit.HATCHLING_VERSION,
            module_loader=lambda _name: module,
        )
        == ()
    )
    errors = build_audit.audit_installed_backend(
        version_loader=lambda _name: "1.30.0",
        module_loader=lambda _name: (_ for _ in ()).throw(ImportError),
    )
    assert "found 1.30.0" in errors[0]
    assert "cannot import" in errors[1]

    def missing(_name: str) -> str:
        raise importlib.metadata.PackageNotFoundError("hatchling")

    assert build_audit.audit_installed_backend(version_loader=missing) == (
        "active environment does not install Hatchling",
    )


def test_consumer_audit_rejects_matrix_install_gate_docker_and_fixture_drift() -> None:
    """Every consumer must remain wired to the hash-locked no-isolation path."""
    valid_docker = f"RUN {build_audit.DOCKER_INSTALL_COMMAND}\n"
    valid_wheel_test = 'args = ["--no-isolation"]\n'
    assert build_audit.audit_consumers(_ci(), valid_docker, valid_wheel_test) == ()

    broken_ci = _ci().replace('python-version: "3.11"', 'python-version: "3.10"')
    broken_ci = broken_ci.replace(build_audit.LOCK_INSTALL_COMMAND, "pip install unpinned")
    broken_ci = broken_ci.replace(build_audit.AUDIT_COMMAND, "true")
    broken_ci = broken_ci.replace(build_audit.SECURITY_JOB_ENVIRONMENT, "  security:\n")
    errors = build_audit.audit_consumers(broken_ci, "FROM scratch\n", "args = []\n")
    assert any("Python 3.11" in error for error in errors)
    assert any("selected lock" in error for error in errors)
    assert any("execute the build-environment audit" in error for error in errors)
    assert any("security job" in error for error in errors)
    assert any("Docker" in error for error in errors)
    assert any("real wheel tests" in error for error in errors)


def test_incomplete_repository_reports_read_and_policy_failures(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    """Missing files must produce deterministic CLI failures, never exceptions."""
    result = build_audit.audit_repository(tmp_path)

    assert not result.passed
    assert any("cannot read pyproject.toml" in error for error in result.errors)
    assert any("missing CI lock" in error for error in result.errors)
    assert build_audit.main(["--repo-root", str(tmp_path)]) == 1
    output = capsys.readouterr().out
    assert "CI build-environment audit: FAIL" in output
    assert "- cannot read" in output
