# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Quantum Control — differentiable reviewer-evidence page tests
"""Real-surface tests for the generated differentiable reviewer-evidence page."""

from __future__ import annotations

import subprocess
import sys
from collections.abc import Callable
from dataclasses import replace
from pathlib import Path
from typing import cast

import pytest

from tools.differentiable_reviewer_evidence_catalog import (
    GENERATED_BY,
    OPEN_GAPS,
    REQUIRED_ROW_IDS,
    REVIEWER_EVIDENCE_ROWS,
    EvidenceCategory,
    EvidenceStatus,
    OpenEvidenceGap,
    ReviewerEvidenceRow,
    ReviewerEvidenceValidation,
    SupportMatrixSummary,
)
from tools.differentiable_reviewer_evidence_page import (
    DEFAULT_CAPABILITY_MANIFEST_PATH,
    DEFAULT_CHANGELOG_PATH,
    DEFAULT_PAGE_PATH,
    DEFAULT_ROADMAP_PATH,
    DEFAULT_SUPPORT_MATRIX_PATH,
    audit_differentiable_reviewer_evidence_page,
    build_differentiable_reviewer_evidence_payload,
    load_capability_manifest,
    load_support_matrix_summary,
    main,
    render_differentiable_reviewer_evidence_page,
    validate_differentiable_reviewer_evidence_payload,
    validate_reviewer_evidence_capability_manifest,
)

TOOL_PATH = Path("tools/differentiable_reviewer_evidence_page.py")
CATALOG_PATH = Path("tools/differentiable_reviewer_evidence_catalog.py")
SUMMARY = SupportMatrixSummary(118, 118, 5, 5)
ROW_CONSTRUCTOR_MUTATIONS: tuple[
    tuple[Callable[[ReviewerEvidenceRow], ReviewerEvidenceRow], str], ...
] = (
    (lambda row: replace(row, criticism=" "), "criticism must be non-blank"),
    (
        lambda row: replace(row, category=cast(EvidenceCategory, "other")),
        "unsupported.*category",
    ),
    (
        lambda row: replace(row, status=cast(EvidenceStatus, "other")),
        "unsupported.*status",
    ),
    (lambda row: replace(row, row_id="DP-030-99"), "row IDs must start"),
    (
        lambda row: replace(row, commands=("",)),
        "commands must contain only",
    ),
    (
        lambda row: replace(row, commands=("same", "same")),
        "commands must not contain duplicates",
    ),
    (
        lambda row: replace(row, evidence_paths=("",)),
        "evidence paths must contain only",
    ),
    (
        lambda row: replace(row, open_gap_refs=("x", "x")),
        "open-gap references must not",
    ),
    (
        lambda row: replace(row, changelog_markers=("",)),
        "changelog markers must contain only",
    ),
    (
        lambda row: replace(row, commands=(), open_gap_refs=()),
        "must name a command",
    ),
    (
        lambda row: replace(row, status="open", open_gap_refs=()),
        "must name an open-gap pointer",
    ),
    (
        lambda row: replace(
            row,
            status="implemented",
            open_gap_refs=("DIFF-OPEN-01",),
        ),
        "cannot carry",
    ),
    (
        lambda row: replace(row, evidence_paths=()),
        "must name at least one evidence path",
    ),
)


def _payload() -> dict[str, object]:
    """Return a mutable fresh payload without reading the support page."""
    return build_differentiable_reviewer_evidence_payload(support_summary=SUMMARY)


def _rows(payload: dict[str, object]) -> list[dict[str, object]]:
    """Return the mutable evidence-row list from a test payload."""
    value = payload["rows"]
    assert isinstance(value, list)
    assert all(isinstance(row, dict) for row in value)
    return cast(list[dict[str, object]], value)


def _gaps(payload: dict[str, object]) -> list[dict[str, object]]:
    """Return the mutable open-gap list from a test payload."""
    value = payload["open_gaps"]
    assert isinstance(value, list)
    assert all(isinstance(row, dict) for row in value)
    return cast(list[dict[str, object]], value)


def _write_support_page(path: Path, *, registry: str = "118/118", planner: str = "5/5") -> None:
    """Write the minimum valid generated support-page summary fixture."""
    supported, blocked = planner.split("/")
    path.write_text(
        "<!-- Generated by tools/differentiable_support_matrix_page.py; do not edit by hand. -->\n"
        "[Differentiable Reviewer Evidence](differentiable_reviewer_evidence.md)\n"
        f"| Program AD registry | `{registry}` complete | evidence |\n"
        f"| Quantum-gradient planner audit | `{supported}` supported / `{blocked}` fail-closed | evidence |\n",
        encoding="utf-8",
    )


def test_catalogue_is_complete_typed_and_below_godfile_threshold() -> None:
    """The catalogue and page keep complete, disjoint responsibilities below 1,000 LOC."""
    assert {row.row_id for row in REVIEWER_EVIDENCE_ROWS} == REQUIRED_ROW_IDS
    assert (
        len([row for row in REVIEWER_EVIDENCE_ROWS if row.category == "reviewer_criticism"]) == 5
    )
    assert len([row for row in REVIEWER_EVIDENCE_ROWS if row.category == "evidence_package"]) == 7
    assert len(OPEN_GAPS) == 5
    assert all(row.commands or row.open_gap_refs for row in REVIEWER_EVIDENCE_ROWS)
    assert all(row.evidence_paths for row in REVIEWER_EVIDENCE_ROWS)
    assert len(CATALOG_PATH.read_text(encoding="utf-8").splitlines()) < 1_000
    assert len(TOOL_PATH.read_text(encoding="utf-8").splitlines()) < 1_000


def test_catalogue_records_have_deterministic_json_shapes() -> None:
    """Typed catalogue records expose every field required by the generator."""
    assert OPEN_GAPS[0].to_dict()["pointer"] == "DIFF-OPEN-01"
    row = REVIEWER_EVIDENCE_ROWS[0].to_dict()
    assert row["row_id"] == "DP-015-01"
    assert row["commands"]
    assert row["evidence_paths"]
    assert SUMMARY.to_dict() == {
        "registry_covered": 118,
        "registry_total": 118,
        "planner_supported": 5,
        "planner_blocked": 5,
    }


def test_open_gap_constructor_errors_are_fail_closed() -> None:
    """Malformed gap construction raises instead of yielding a partial row."""
    with pytest.raises(ValueError, match="must start"):
        OpenEvidenceGap("OTHER-01", "title", "marker", "detail")
    with pytest.raises(ValueError, match="title must be non-blank"):
        OpenEvidenceGap("DIFF-OPEN-99", " ", "marker", "detail")


@pytest.mark.parametrize(
    ("mutation", "message"),
    ROW_CONSTRUCTOR_MUTATIONS,
)
def test_evidence_row_constructor_rejects_contract_drift(
    mutation: Callable[[ReviewerEvidenceRow], ReviewerEvidenceRow],
    message: str,
) -> None:
    """Typed row construction rejects incomplete or contradictory definitions."""
    with pytest.raises(ValueError, match=message):
        mutation(REVIEWER_EVIDENCE_ROWS[0])


@pytest.mark.parametrize(
    "summary",
    [
        (0, 1, 1, 1),
        (1, 1, 0, 1),
        (1, 1, 1, False),
        (1, 2, 1, 1),
    ],
)
def test_support_summary_rejects_invalid_counts(summary: tuple[int, int, int, int]) -> None:
    """Support synchronization rejects non-positive, boolean, or incomplete counts."""
    with pytest.raises(ValueError):
        SupportMatrixSummary(*summary)


def test_validation_verdict_rejects_contradictions() -> None:
    """Pass/fail verdicts cannot contradict their error list."""
    assert ReviewerEvidenceValidation(True, ()).passed
    assert ReviewerEvidenceValidation(False, ("error",)).errors == ("error",)
    with pytest.raises(ValueError, match="passed validation"):
        ReviewerEvidenceValidation(True, ("error",))
    with pytest.raises(ValueError, match="failed validation"):
        ReviewerEvidenceValidation(False, ())


def test_support_page_parser_requires_generated_link_and_both_rows(tmp_path: Path) -> None:
    """The parser accepts the generated contract and rejects each missing surface."""
    support = tmp_path / "support.md"
    _write_support_page(support)
    assert load_support_matrix_summary(support) == SUMMARY
    variants = (
        ("plain\n", "generated-file marker"),
        (
            "<!-- Generated by tools/differentiable_support_matrix_page.py; do not edit by hand. -->\n",
            "does not link",
        ),
        (
            "<!-- Generated by tools/differentiable_support_matrix_page.py; do not edit by hand. -->\n"
            "[Differentiable Reviewer Evidence]\n",
            "registry summary",
        ),
        (
            "<!-- Generated by tools/differentiable_support_matrix_page.py; do not edit by hand. -->\n"
            "[Differentiable Reviewer Evidence]\n"
            "| Program AD registry | `118/118` complete | evidence |\n",
            "planner summary",
        ),
    )
    for content, message in variants:
        support.write_text(content, encoding="utf-8")
        with pytest.raises(ValueError, match=message):
            load_support_matrix_summary(support)


def test_payload_is_complete_and_valid_against_live_repository() -> None:
    """All twelve catalogue rows resolve to real commands, paths, markers, and gaps."""
    payload = _payload()
    validation = validate_differentiable_reviewer_evidence_payload(payload)
    assert validation == ReviewerEvidenceValidation(True, ())
    assert payload["generated_by"] == GENERATED_BY


def test_capability_manifest_alignment_accepts_current_manifest() -> None:
    """The current capability manifest inventories every reviewer-page owner."""
    result = validate_reviewer_evidence_capability_manifest(
        load_capability_manifest(),
        payload=_payload(),
    )
    assert result == ReviewerEvidenceValidation(True, ())


@pytest.mark.parametrize(
    ("mutation", "expected"),
    [
        ("schema", "schema_version"),
        ("project", "project.name"),
        ("generator", "generator identity"),
        ("exports", "missing required package export"),
        ("models", "models object is missing"),
        ("model_list", "must be a string list"),
        ("quality", "quality_gates object is missing"),
        ("docs", "documentation object is missing"),
        ("counts", "counts object is missing"),
        ("count_value", "does not match its surface length"),
        ("requirements", "requirements object is missing"),
        ("required_shape", "must be a non-blank string list"),
    ],
)
def test_capability_manifest_validation_fails_closed(
    mutation: str,
    expected: str,
) -> None:
    """Manifest identity, shape, count, and required-surface drift is detected."""
    manifest = load_capability_manifest()
    payload = _payload()
    if mutation == "schema":
        manifest["schema_version"] = "foreign"
    elif mutation == "project":
        manifest["project"] = {"name": "foreign"}
    elif mutation == "generator":
        manifest["generated_from"] = {"generator": "foreign"}
    elif mutation == "exports":
        exports = cast(list[str], manifest["package_exports"])
        exports.remove("PhaseVQE")
    elif mutation == "models":
        manifest["models"] = None
    elif mutation == "model_list":
        cast(dict[str, object], manifest["models"])["python_source_modules"] = "bad"
    elif mutation == "quality":
        manifest["quality_gates"] = None
    elif mutation == "docs":
        manifest["documentation"] = None
    elif mutation == "counts":
        manifest["counts"] = None
    elif mutation == "count_value":
        cast(dict[str, object], manifest["counts"])["test_files"] = -1
    elif mutation == "requirements":
        payload["capability_manifest_requirements"] = None
    else:
        requirements = cast(dict[str, object], payload["capability_manifest_requirements"])
        requirements["test_files"] = "bad"
    result = validate_reviewer_evidence_capability_manifest(manifest, payload=payload)
    assert not result.passed
    assert expected in "\n".join(result.errors)


@pytest.mark.parametrize(
    ("mutation", "expected"),
    [
        ("schema", "unexpected schema"),
        ("generator", "unexpected generator"),
        ("rows_shape", "rows must be a list"),
        ("row_shape", "rows[0] must be an object"),
        ("gaps_shape", "open_gaps must be a list"),
        ("support_missing", "support_matrix object is missing"),
        ("support_bool", "must be a positive integer"),
        ("support_incomplete", "registry coverage must be complete"),
        ("duplicate_id", "duplicate reviewer-evidence row_id"),
        ("missing_id", "missing required row"),
        ("unexpected_id", "unexpected row"),
        ("unknown_category", "unsupported category"),
        ("unknown_status", "unsupported status"),
        ("prefix", "does not match category prefix"),
        ("blank_field", "criticism must be a non-blank string"),
        ("commands_shape", "commands must be a non-blank string list"),
        ("duplicate_paths", "evidence_paths must not contain duplicates"),
        ("no_route", "must name a runnable command or open-gap pointer"),
        ("open_no_gap", "open row"),
        ("implemented_gap", "cannot carry open-gap pointers"),
        ("no_paths", "must name at least one evidence path"),
        ("unknown_gap", "unknown public open gap"),
        ("missing_marker", "changelog marker is missing"),
        ("unsafe_path", "parent traversal"),
        ("missing_path", "does not resolve to a file"),
        ("gap_marker", "canonical definition"),
        ("duplicate_gap", "duplicate open-gap pointer"),
        ("missing_gap", "missing required open gap"),
        ("unexpected_gap", "unexpected open gap"),
    ],
)
def test_payload_validation_rejects_row_and_gap_drift(
    mutation: str,
    expected: str,
) -> None:
    """Public validation reports malformed rows, gaps, paths, markers, and counts."""
    payload = _payload()
    rows = _rows(payload)
    gaps = _gaps(payload)
    if mutation == "schema":
        payload["schema"] = "foreign"
    elif mutation == "generator":
        payload["generated_by"] = "foreign"
    elif mutation == "rows_shape":
        payload["rows"] = "bad"
    elif mutation == "row_shape":
        rows[0] = cast(dict[str, object], "bad")
    elif mutation == "gaps_shape":
        payload["open_gaps"] = "bad"
    elif mutation == "support_missing":
        payload["support_matrix"] = None
    elif mutation == "support_bool":
        cast(dict[str, object], payload["support_matrix"])["planner_blocked"] = True
    elif mutation == "support_incomplete":
        cast(dict[str, object], payload["support_matrix"])["registry_covered"] = 117
    elif mutation == "duplicate_id":
        rows[1]["row_id"] = rows[0]["row_id"]
    elif mutation == "missing_id":
        rows.pop()
    elif mutation == "unexpected_id":
        rows[-1]["row_id"] = "DP-030-99"
    elif mutation == "unknown_category":
        rows[0]["category"] = "other"
    elif mutation == "unknown_status":
        rows[0]["status"] = "other"
    elif mutation == "prefix":
        rows[0]["row_id"] = "DP-030-01"
    elif mutation == "blank_field":
        rows[0]["criticism"] = " "
    elif mutation == "commands_shape":
        rows[0]["commands"] = "bad"
    elif mutation == "duplicate_paths":
        paths = cast(list[str], rows[0]["evidence_paths"])
        paths.append(paths[0])
    elif mutation == "no_route":
        rows[0]["commands"] = []
        rows[0]["open_gap_refs"] = []
    elif mutation == "open_no_gap":
        rows[0]["status"] = "open"
        rows[0]["open_gap_refs"] = []
    elif mutation == "implemented_gap":
        rows[0]["open_gap_refs"] = ["DIFF-OPEN-01"]
    elif mutation == "no_paths":
        rows[0]["evidence_paths"] = []
    elif mutation == "unknown_gap":
        rows[1]["open_gap_refs"] = ["DIFF-OPEN-99"]
    elif mutation == "missing_marker":
        rows[0]["changelog_markers"] = ["never-written-marker"]
    elif mutation == "unsafe_path":
        rows[0]["evidence_paths"] = ["../outside"]
    elif mutation == "missing_path":
        rows[0]["evidence_paths"] = ["tests/absent.py"]
    elif mutation == "gap_marker":
        gaps[0]["roadmap_marker"] = "foreign"
    elif mutation == "duplicate_gap":
        gaps[1]["pointer"] = gaps[0]["pointer"]
    elif mutation == "missing_gap":
        gaps.pop()
    else:
        gaps[-1]["pointer"] = "DIFF-OPEN-99"
    result = validate_differentiable_reviewer_evidence_payload(payload)
    assert not result.passed
    assert expected in "\n".join(result.errors)


@pytest.mark.parametrize(
    ("command", "expected"),
    [
        ("pytest tests/test_phase_vqe.py", "must start with python"),
        ("python -m pytest -q tests/test_phase_vqe.py && echo bad", "shell-control"),
        ("python -m pytest -q", "only explicit test files"),
        ("python -m pytest -q docs/guide.py", "not a scoped test module"),
        ("python -m pytest -q tests/missing.py", "does not resolve to a file"),
        ("python tools/differentiable_support_matrix_page.py --write", "must use --check"),
        ("python tools/missing.py --check", "does not resolve to a file"),
        ("python -c pass", "outside the scoped command grammar"),
        ("python 'unterminated", "cannot be parsed"),
    ],
)
def test_payload_validation_rejects_unscoped_commands(
    command: str,
    expected: str,
) -> None:
    """Row validation rejects shell control, broad tests, and non-check tools."""
    payload = _payload()
    _rows(payload)[0]["commands"] = [command]
    result = validate_differentiable_reviewer_evidence_payload(payload)
    assert not result.passed
    assert expected in "\n".join(result.errors)


def test_payload_validation_reports_unreadable_sources(tmp_path: Path) -> None:
    """Missing changelog and roadmap inputs are reported without masking row errors."""
    missing = tmp_path / "missing.md"
    result = validate_differentiable_reviewer_evidence_payload(
        _payload(),
        changelog_path=missing,
        roadmap_path=missing,
    )
    joined = "\n".join(result.errors)
    assert "cannot read changelog" in joined
    assert "cannot read public roadmap" in joined


def test_payload_validation_rejects_symlink_escape(tmp_path: Path) -> None:
    """Evidence paths cannot escape the repository through a symbolic link."""
    repo_root = tmp_path / "repo"
    repo_root.mkdir()
    outside = tmp_path / "outside.md"
    outside.write_text("outside\n", encoding="utf-8")
    (repo_root / "linked-evidence.md").symlink_to(outside)
    payload = _payload()
    _rows(payload)[0]["evidence_paths"] = ["linked-evidence.md"]

    result = validate_differentiable_reviewer_evidence_payload(
        payload,
        repo_root=repo_root,
    )

    assert not result.passed
    assert "escapes the repository root" in "\n".join(result.errors)


def test_renderer_emits_all_rows_gaps_boundaries_and_escaped_text() -> None:
    """The public page renders both tables, all IDs, commands, gaps, and safe text."""
    payload = _payload()
    rows = _rows(payload)
    rows[0]["evidence_summary"] = "line one\npipe | tick `"
    rendered = render_differentiable_reviewer_evidence_page(payload)
    assert "# Differentiable Reviewer Evidence" in rendered
    assert "## DP-015 reviewer criticisms" in rendered
    assert "## DP-030 evidence package" in rendered
    assert "## Public open-gap pointers" in rendered
    assert all(row_id in rendered for row_id in REQUIRED_ROW_IDS)
    assert all(gap.pointer in rendered for gap in OPEN_GAPS)
    assert "line one pipe \\| tick \\`" in rendered
    assert "repository-wide local test runs remain" in rendered


def test_renderer_rejects_invalid_payload_and_render_shapes() -> None:
    """Rendering never bypasses validation or accepts malformed list fields."""
    payload = _payload()
    payload["schema"] = "foreign"
    with pytest.raises(ValueError, match="unexpected schema"):
        render_differentiable_reviewer_evidence_page(payload)

    valid = _payload()
    _rows(valid)[0]["commands"] = cast(list[str], [1])
    with pytest.raises(ValueError, match="commands must be"):
        render_differentiable_reviewer_evidence_page(valid)


def test_committed_page_is_current_and_manifest_aligned() -> None:
    """The committed page equals a fresh rendering from every validated source."""
    assert audit_differentiable_reviewer_evidence_page() == ()
    payload = build_differentiable_reviewer_evidence_payload()
    assert DEFAULT_PAGE_PATH.read_text(encoding="utf-8") == (
        render_differentiable_reviewer_evidence_page(payload)
    )


def test_page_audit_reports_missing_stale_and_invalid_inputs(tmp_path: Path) -> None:
    """The public audit reports missing/stale pages and invalid source artefacts."""
    missing = tmp_path / "missing.md"
    assert "is missing" in audit_differentiable_reviewer_evidence_page(page_path=missing)[0]
    stale = tmp_path / "stale.md"
    stale.write_text("stale\n", encoding="utf-8")
    assert "is stale" in audit_differentiable_reviewer_evidence_page(page_path=stale)[0]
    invalid_manifest = tmp_path / "manifest.json"
    invalid_manifest.write_text("not-json\n", encoding="utf-8")
    assert (
        "audit failed"
        in audit_differentiable_reviewer_evidence_page(manifest_path=invalid_manifest)[0]
    )
    invalid_manifest.write_text("{}\n", encoding="utf-8")
    assert (
        "schema_version"
        in audit_differentiable_reviewer_evidence_page(manifest_path=invalid_manifest)[0]
    )
    invalid_support = tmp_path / "support.md"
    invalid_support.write_text("bad\n", encoding="utf-8")
    assert (
        "audit failed"
        in audit_differentiable_reviewer_evidence_page(support_matrix_path=invalid_support)[0]
    )


def test_capability_manifest_loader_rejects_non_object_json(tmp_path: Path) -> None:
    """Manifest loading accepts objects and rejects all non-object roots."""
    manifest = tmp_path / "manifest.json"
    manifest.write_text('{"schema_version": "x"}', encoding="utf-8")
    assert load_capability_manifest(manifest)["schema_version"] == "x"
    manifest.write_text("[]", encoding="utf-8")
    with pytest.raises(ValueError, match="must be an object"):
        load_capability_manifest(manifest)


def test_cli_write_preview_check_and_failure_round_trip(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    """The CLI writes, previews, validates, detects drift, and fails bad inputs."""
    output = tmp_path / "reviewer.md"
    args = [
        "--output",
        str(output),
        "--manifest",
        str(DEFAULT_CAPABILITY_MANIFEST_PATH),
        "--support-matrix",
        str(DEFAULT_SUPPORT_MATRIX_PATH),
        "--changelog",
        str(DEFAULT_CHANGELOG_PATH),
        "--roadmap",
        str(DEFAULT_ROADMAP_PATH),
    ]
    assert main(["--write", *args]) == 0
    assert output.is_file()
    assert main(["--check", *args]) == 0
    assert "current" in capsys.readouterr().out
    output.write_text("stale\n", encoding="utf-8")
    assert main(["--check", *args]) == 1
    assert "is stale" in capsys.readouterr().err
    assert main(["--manifest", str(DEFAULT_CAPABILITY_MANIFEST_PATH)]) == 0
    assert "# Differentiable Reviewer Evidence" in capsys.readouterr().out
    bad_manifest = tmp_path / "bad.json"
    bad_manifest.write_text("{}", encoding="utf-8")
    assert main(["--write", "--manifest", str(bad_manifest), *args[:2]]) == 1
    assert "FAIL" in capsys.readouterr().err


def test_script_entry_point_executes_the_real_check() -> None:
    """Direct script execution runs the committed-page audit."""
    completed = subprocess.run(
        [sys.executable, str(TOOL_PATH), "--check"],
        check=False,
        capture_output=True,
        text=True,
    )
    assert completed.returncode == 0
    assert completed.stdout.strip() == "differentiable reviewer-evidence page: current"
    assert completed.stderr == ""
