# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# (c) Concepts 1996-2026 Miroslav Sotek. All rights reserved.
# (c) Code 2020-2026 Miroslav Sotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Quantum Control -- Paper 0 Layer 5 Active Inference spec tests
"""Tests for Paper 0 Layer 5 Active Inference spec promotion."""

from __future__ import annotations

from pathlib import Path

from scpn_quantum_control.paper0.spec_loader import load_l5_active_inference_validation_spec
from scripts.build_paper0_l5_active_inference_specs import (
    build_l5_active_inference_specs,
    build_validation_report,
    load_jsonl,
    write_outputs,
)

LEDGER_PATH = Path(
    "docs/internal/paper0_foundational_extraction/paper0_canonical_review_ledger_2026-05-13.jsonl"
)


def test_l5_active_inference_builder_consumes_complete_source_span() -> None:
    bundle = build_l5_active_inference_specs(load_jsonl(LEDGER_PATH))

    assert bundle.summary["source_record_count"] == 16
    assert bundle.summary["consumed_source_record_count"] == 16
    assert bundle.summary["coverage_match"] is True
    assert bundle.summary["source_ledger_span"] == ["P0R06434", "P0R06449"]
    assert bundle.summary["structural_source_ledger_ids"] == [
        "P0R06434",
        "P0R06436",
        "P0R06439",
        "P0R06441",
        "P0R06445",
        "P0R06449",
    ]
    assert bundle.summary["caption_source_ledger_ids"] == [
        "P0R06437",
        "P0R06440",
        "P0R06446",
    ]
    assert bundle.summary["spec_count"] == 4
    assert tuple(spec.key for spec in bundle.specs) == (
        "l5_active_inference.attractor_geometry",
        "l5_active_inference.hpc_triple_network_loop",
        "l5_active_inference.fep_perception_action_loop",
        "l5_active_inference.cosmic_prior_boundary",
    )


def test_l5_active_inference_specs_preserve_mechanisms_and_boundaries() -> None:
    bundle = build_l5_active_inference_specs(load_jsonl(LEDGER_PATH))
    specs = {spec.key: spec for spec in bundle.specs}

    assert specs["l5_active_inference.attractor_geometry"].source_mechanisms == (
        "integrated self is represented as a self-referential strange loop",
        "emotional qualia are bounded to attractor-manifold topology",
        "basins, loops, gradient flow, and saddle boundaries define qualitative regimes",
    )
    assert specs["l5_active_inference.hpc_triple_network_loop"].source_mechanisms == (
        "downward generative projection issues predictions",
        "upward inference flow propagates precision-weighted prediction error",
        "salience network/anterior insula biases CEN versus DMN mode dominance",
    )
    assert specs["l5_active_inference.fep_perception_action_loop"].source_formulae == (
        "variational free energy upper-bounds surprise",
        "prediction error epsilon is generated by sensory data minus predictions",
        "policy/action changes the environment to reduce future error",
    )
    assert specs["l5_active_inference.cosmic_prior_boundary"].claim_boundary.endswith(
        "speculative cosmological prior; not empirical evidence"
    )
    assert (
        "reject treating SEC/FEP identity as established physics"
        in specs["l5_active_inference.cosmic_prior_boundary"].null_controls
    )


def test_l5_active_inference_outputs_and_loader_round_trip(tmp_path: Path) -> None:
    json_path = tmp_path / "l5_active_inference_specs.json"
    report_path = tmp_path / "l5_active_inference_specs.md"
    bundle = build_l5_active_inference_specs(load_jsonl(LEDGER_PATH))

    write_outputs(bundle=bundle, output_path=json_path, report_path=report_path)
    loaded = load_l5_active_inference_validation_spec(
        "l5_active_inference.fep_perception_action_loop",
        spec_bundle_path=json_path,
    )
    report = build_validation_report(bundle)

    assert loaded["source_ledger_ids"] == [f"P0R{number:05d}" for number in range(6434, 6450)]
    assert loaded["hardware_status"] == "simulator_only_no_provider_submission"
    assert "not empirical evidence" in loaded["claim_boundary"]
    assert "# Paper 0 Layer 5 Active Inference Specs" in report
    assert json_path.exists()
    assert report_path.exists()
