#!/usr/bin/env python
# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# oscillatools — capability snapshot renderer
"""Snapshot the live oscillatools facade into a machine- and human-readable page.

The handbook narrates the toolkit; this tool records the exact public capability
surface — every group and every symbol the facade exposes at the recorded
version — so the documentation site carries a grep-able, diffable inventory that
moves in lockstep with the code. ``build_snapshot`` returns the structured
record; ``render_markdown`` formats it; ``main`` writes the committed page.
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path

import oscillatools as kuramoto

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "capabilities.md"


@dataclass(frozen=True)
class CapabilitySnapshot:
    """A version-stamped record of the public facade's capability surface."""

    version: str
    groups: Mapping[str, tuple[str, ...]]

    @property
    def total_symbols(self) -> int:
        """Return the total number of public symbols across every group."""

        return sum(len(symbols) for symbols in self.groups.values())

    @property
    def group_count(self) -> int:
        """Return the number of capability groups."""

        return len(self.groups)

    def to_json_dict(self) -> dict[str, object]:
        """Return a JSON-stable representation of the snapshot."""

        return {
            "version": self.version,
            "total_symbols": self.total_symbols,
            "group_count": self.group_count,
            "groups": {group: list(symbols) for group, symbols in self.groups.items()},
        }


def build_snapshot() -> CapabilitySnapshot:
    """Capture the live oscillatools facade capability surface."""

    capabilities = kuramoto.capabilities()
    groups = {group: tuple(symbols) for group, symbols in capabilities.items()}
    return CapabilitySnapshot(version=kuramoto.__version__, groups=groups)


def _symbol_list(symbols: Sequence[str]) -> str:
    """Format a stable comma-separated list of public symbols."""

    return ", ".join(f"`{symbol}`" for symbol in symbols)


def render_markdown(snapshot: CapabilitySnapshot) -> str:
    """Render the capability snapshot as a Markdown reference page."""

    lines: list[str] = [
        "<!--",
        "SPDX-License-Identifier: AGPL-3.0-or-later",
        "Commercial license available",
        "© Concepts 1996–2026 Miroslav Šotek. All rights reserved.",
        "© Code 2020–2026 Miroslav Šotek. All rights reserved.",
        "ORCID: 0009-0009-3560-0851",
        "Contact: www.anulum.li | protoscience@anulum.li",
        "Generated by tools/capability_snapshot.py — do not edit by hand.",
        "-->",
        "",
        "# Capability Snapshot",
        "",
        f"`oscillatools` {snapshot.version} exposes {snapshot.total_symbols} public",
        f"symbols across {snapshot.group_count} capability groups. This page is the",
        "exact inventory captured from the live facade, so it can be diffed against a",
        "prior release to see what the public surface gained or lost.",
        "",
        "| Group | Count |",
        "|---|--:|",
    ]
    for group, symbols in snapshot.groups.items():
        lines.append(f"| `{group}` | {len(symbols)} |")
    lines.append("")
    for group, symbols in snapshot.groups.items():
        lines.append(f"## `{group}` ({len(symbols)})")
        lines.append("")
        lines.append(_symbol_list(symbols))
        lines.append("")
    return "\n".join(lines)


def main(argv: Sequence[str] | None = None) -> int:
    """Render the capability snapshot page and write it to disk."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Markdown output path")
    args = parser.parse_args(list(sys.argv[1:] if argv is None else argv))

    document = render_markdown(build_snapshot())
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(document, encoding="utf-8")
    print(f"[snapshot] wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
