# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Quantum Control — Paper 0 source registers
"""Paper 0 source-anchored equation and validation registers."""

from .equation_register import (
    Paper0EquationRecord,
    get_paper0_equation_record,
    iter_paper0_equation_records,
    paper0_upde_records,
)
from .topology_schema import (
    Paper0AdaptiveParameterSet,
    Paper0FieldPort,
    Paper0InterLayerEdge,
    Paper0IntraLayerTopology,
    Paper0SyntheticControl,
    Paper0TopologyLayer,
    Paper0TopologySchema,
    Paper0TopologyValidationError,
    build_paper0_topology_schema,
    schema_to_s19_source_boundary,
    validate_paper0_topology_schema,
)
from .upde_validation import (
    AdaptiveCouplingConfig,
    AdaptiveCouplingRates,
    AdaptiveCouplingStep,
    AdaptiveCouplingValidationResult,
    BasePhaseValidationConfig,
    BasePhaseValidationResult,
    FieldCouplingConfig,
    FieldValidationResult,
    InterlayerCouplingConfig,
    InterlayerCouplingTerms,
    InterlayerValidationResult,
    NaturalGradientConfig,
    NaturalGradientValidationResult,
    adaptive_coupling_rates,
    apply_adaptive_coupling_step,
    circular_mean_phase,
    field_alignment_projection,
    field_coupling_term,
    finite_difference_negative_gradient,
    finite_difference_quadratic_gradient,
    interlayer_coupling_terms,
    kuramoto_phase_drift,
    load_upde_validation_spec,
    natural_gradient_flow,
    negative_cosine_potential,
    quadratic_free_energy,
    validate_upde_adaptive_coupling_fixture,
    validate_upde_base_phase_fixture,
    validate_upde_field_fixture,
    validate_upde_interlayer_fixture,
    validate_upde_natural_gradient_fixture,
)

__all__ = [
    "AdaptiveCouplingConfig",
    "AdaptiveCouplingRates",
    "AdaptiveCouplingStep",
    "AdaptiveCouplingValidationResult",
    "BasePhaseValidationConfig",
    "BasePhaseValidationResult",
    "FieldCouplingConfig",
    "FieldValidationResult",
    "InterlayerCouplingConfig",
    "InterlayerCouplingTerms",
    "InterlayerValidationResult",
    "NaturalGradientConfig",
    "NaturalGradientValidationResult",
    "Paper0EquationRecord",
    "Paper0AdaptiveParameterSet",
    "Paper0FieldPort",
    "Paper0InterLayerEdge",
    "Paper0IntraLayerTopology",
    "Paper0SyntheticControl",
    "Paper0TopologyLayer",
    "Paper0TopologySchema",
    "Paper0TopologyValidationError",
    "adaptive_coupling_rates",
    "apply_adaptive_coupling_step",
    "build_paper0_topology_schema",
    "circular_mean_phase",
    "field_alignment_projection",
    "field_coupling_term",
    "finite_difference_negative_gradient",
    "finite_difference_quadratic_gradient",
    "get_paper0_equation_record",
    "interlayer_coupling_terms",
    "iter_paper0_equation_records",
    "kuramoto_phase_drift",
    "load_upde_validation_spec",
    "natural_gradient_flow",
    "negative_cosine_potential",
    "paper0_upde_records",
    "quadratic_free_energy",
    "schema_to_s19_source_boundary",
    "validate_paper0_topology_schema",
    "validate_upde_adaptive_coupling_fixture",
    "validate_upde_base_phase_fixture",
    "validate_upde_field_fixture",
    "validate_upde_interlayer_fixture",
    "validate_upde_natural_gradient_fixture",
]
