#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# (c) Concepts 1996-2026 Miroslav Sotek. All rights reserved.
# (c) Code 2020-2026 Miroslav Sotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# scpn-quantum-control -- Paper 0 VII. Field Generation and Upward Causality (Topological Defects) spec builder
"""Promote Paper 0 VII. Field Generation and Upward Causality (Topological Defects) records."""

from __future__ import annotations

import argparse
import json
from collections import Counter
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXTRACTION_DIR = REPO_ROOT / "docs" / "internal" / "paper0_foundational_extraction"
DEFAULT_LEDGER_PATH = DEFAULT_EXTRACTION_DIR / "paper0_canonical_review_ledger_2026-05-13.jsonl"

SOURCE_LEDGER_IDS = (
    "P0R03250",
    "P0R03251",
    "P0R03252",
    "P0R03253",
    "P0R03254",
    "P0R03255",
    "P0R03256",
    "P0R03257",
    "P0R03258",
    "P0R03259",
)
CLAIM_BOUNDARY = "source-bounded vii field generation and upward causality topological defects source-accounting bridge; not validation evidence"
HARDWARE_STATUS = "source_methodology_no_experiment"

SPEC_CONTENT: dict[str, dict[str, tuple[str, ...] | str]] = {
    "vii_field_generation_and_upward_causality_topological_defects.vii_field_generation_and_upward_causality_topological_defects": {
        "context_id": "vii_field_generation_and_upward_causality_topological_defects",
        "validation_protocol": "paper0.vii_field_generation_and_upward_causality_topological_defects.vii_field_generation_and_upward_causality_topological_defects",
        "canonical_statement": "The source-bounded component 'VII. Field Generation and Upward Causality (Topological Defects)' preserves Paper 0 records P0R03250-P0R03252 without empirical validation claims.",
        "source_equation_ids": (
            "P0R03250:vii_field_generation_and_upward_causality_topological_defects",
            "P0R03251:vii_field_generation_and_upward_causality_topological_defects",
            "P0R03252:vii_field_generation_and_upward_causality_topological_defects",
        ),
        "source_formulae": (
            "P0R03250: VII. Field Generation and Upward Causality (Topological Defects)",
            "P0R03251: Upward causality is formalised using Topological Quantum Field Theory (TQFT).",
            "P0R03252: Mechanism: Complex physical configurations (L1-4) act as Topological Defects (e.g., vortices) within the Psi-field. | Field Generation: These defects source the higher-order fields. The emergence of the Self (L5) is the formation of a stable topological defect (soliton) generated by biological coherence (L4).",
        ),
        "test_protocols": (
            "preserve VII. Field Generation and Upward Causality (Topological Defects) source-accounting boundary",
        ),
        "null_results": (
            "VII. Field Generation and Upward Causality (Topological Defects) is not empirical validation evidence",
        ),
        "variables": ("vii_field_generation_and_upward_causality_topological_defects",),
        "validation_targets": ("preserve records P0R03250-P0R03252",),
        "null_controls": (
            "vii_field_generation_and_upward_causality_topological_defects must remain source-bounded accounting",
        ),
    },
    "vii_field_generation_and_upward_causality_topological_defects.viii_the_combination_problem_and_panpsychist_fusion_quantum_mereology": {
        "context_id": "viii_the_combination_problem_and_panpsychist_fusion_quantum_mereology",
        "validation_protocol": "paper0.vii_field_generation_and_upward_causality_topological_defects.viii_the_combination_problem_and_panpsychist_fusion_quantum_mereology",
        "canonical_statement": "The source-bounded component 'VIII. The Combination Problem and Panpsychist Fusion (Quantum Mereology)' preserves Paper 0 records P0R03253-P0R03255 without empirical validation claims.",
        "source_equation_ids": (
            "P0R03253:viii_the_combination_problem_and_panpsychist_fusion_quantum_mereology",
            "P0R03254:viii_the_combination_problem_and_panpsychist_fusion_quantum_mereology",
            "P0R03255:viii_the_combination_problem_and_panpsychist_fusion_quantum_mereology",
        ),
        "source_formulae": (
            "P0R03253: VIII. The Combination Problem and Panpsychist Fusion (Quantum Mereology)",
            "P0R03254: The Combination Problem is resolved via Panpsychist Fusion, formalised using Quantum Mereology.",
            "P0R03255: Fusion Condition: Two systems fuse into a unified whole (SAB) when entanglement and Integrated Information () exceed the sum of their parts: AB>A+B. | Mechanism: The Psi-field (Gauge Field) mediates the entanglement required for fusion, facilitated by UPDE synchronisation.",
        ),
        "test_protocols": (
            "preserve VIII. The Combination Problem and Panpsychist Fusion (Quantum Mereology) source-accounting boundary",
        ),
        "null_results": (
            "VIII. The Combination Problem and Panpsychist Fusion (Quantum Mereology) is not empirical validation evidence",
        ),
        "variables": ("viii_the_combination_problem_and_panpsychist_fusion_quantum_mereology",),
        "validation_targets": ("preserve records P0R03253-P0R03255",),
        "null_controls": (
            "viii_the_combination_problem_and_panpsychist_fusion_quantum_mereology must remain source-bounded accounting",
        ),
    },
    "vii_field_generation_and_upward_causality_topological_defects.integrative_mechanisms_in_short": {
        "context_id": "integrative_mechanisms_in_short",
        "validation_protocol": "paper0.vii_field_generation_and_upward_causality_topological_defects.integrative_mechanisms_in_short",
        "canonical_statement": "The source-bounded component 'Integrative Mechanisms in short' preserves Paper 0 records P0R03256-P0R03256 without empirical validation claims.",
        "source_equation_ids": ("P0R03256:integrative_mechanisms_in_short",),
        "source_formulae": ("P0R03256: Integrative Mechanisms in short",),
        "test_protocols": ("preserve Integrative Mechanisms in short source-accounting boundary",),
        "null_results": ("Integrative Mechanisms in short is not empirical validation evidence",),
        "variables": ("integrative_mechanisms_in_short",),
        "validation_targets": ("preserve records P0R03256-P0R03256",),
        "null_controls": (
            "integrative_mechanisms_in_short must remain source-bounded accounting",
        ),
    },
    "vii_field_generation_and_upward_causality_topological_defects.i_the_unifying_computational_principle_hpc": {
        "context_id": "i_the_unifying_computational_principle_hpc",
        "validation_protocol": "paper0.vii_field_generation_and_upward_causality_topological_defects.i_the_unifying_computational_principle_hpc",
        "canonical_statement": "The source-bounded component 'I. The Unifying Computational Principle (HPC)' preserves Paper 0 records P0R03257-P0R03259 without empirical validation claims.",
        "source_equation_ids": (
            "P0R03257:i_the_unifying_computational_principle_hpc",
            "P0R03258:i_the_unifying_computational_principle_hpc",
            "P0R03259:i_the_unifying_computational_principle_hpc",
        ),
        "source_formulae": (
            "P0R03257: I. The Unifying Computational Principle (HPC)",
            "P0R03258: The SCPN is unified by Hierarchical Predictive Coding (HPC), minimising Variational Free Energy (F).",
            'P0R03259: "Concretely, in the UPDE, the inter-layer term sin(theta_{L+1} theta_L) encodes prediction error; phase-locking (theta_{L+1} theta_L) is the physical signature of error suppression / free-energy minimisation under HPC."',
        ),
        "test_protocols": (
            "preserve I. The Unifying Computational Principle (HPC) source-accounting boundary",
        ),
        "null_results": (
            "I. The Unifying Computational Principle (HPC) is not empirical validation evidence",
        ),
        "variables": ("i_the_unifying_computational_principle_hpc",),
        "validation_targets": ("preserve records P0R03257-P0R03259",),
        "null_controls": (
            "i_the_unifying_computational_principle_hpc must remain source-bounded accounting",
        ),
    },
}


@dataclass(frozen=True, slots=True)
class ViiFieldGenerationAndUpwardCausalityTopologicalDefectsSpec:
    """Spec promoted from Paper 0 source records."""

    key: str
    context_id: str
    validation_protocol: str
    manuscript: str
    section_path: str
    canonical_statement: str
    source_equation_ids: tuple[str, ...]
    source_ledger_ids: tuple[str, ...]
    source_record_ids: tuple[str, ...]
    source_block_indices: tuple[int, ...]
    source_formulae: tuple[str, ...]
    test_protocols: tuple[str, ...]
    null_results: tuple[str, ...]
    variables: tuple[str, ...]
    validation_targets: tuple[str, ...]
    executable_validation_targets: tuple[str, ...]
    null_controls: tuple[str, ...]
    claim_boundary: str
    implementation_status: str
    domain_review_status: str
    hardware_status: str


@dataclass(frozen=True, slots=True)
class ViiFieldGenerationAndUpwardCausalityTopologicalDefectsSpecBundle:
    """Specs plus source coverage summary."""

    specs: tuple[ViiFieldGenerationAndUpwardCausalityTopologicalDefectsSpec, ...]
    summary: dict[str, Any]


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    """Load a JSONL ledger into dictionaries."""
    records: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            stripped = line.strip()
            if not stripped:
                continue
            try:
                records.append(json.loads(stripped))
            except json.JSONDecodeError as exc:
                raise ValueError(f"invalid JSONL at {path}:{line_number}") from exc
    return records


def build_vii_field_generation_and_upward_causality_topological_defects_specs(
    source_records: list[dict[str, Any]],
) -> ViiFieldGenerationAndUpwardCausalityTopologicalDefectsSpecBundle:
    """Build source-covered specs."""
    records_by_ledger = {str(record["ledger_id"]): record for record in source_records}
    missing = sorted(set(SOURCE_LEDGER_IDS) - set(records_by_ledger))
    if missing:
        raise ValueError(f"missing required source ledger ids: {missing}")

    anchors = [records_by_ledger[ledger_id] for ledger_id in SOURCE_LEDGER_IDS]
    category_counts = Counter(
        str(record.get("canonical_category", "unknown")) for record in anchors
    )
    block_counts = Counter(str(record.get("block_type", "unknown")) for record in anchors)

    specs: list[ViiFieldGenerationAndUpwardCausalityTopologicalDefectsSpec] = []
    for key, metadata in SPEC_CONTENT.items():
        specs.append(
            ViiFieldGenerationAndUpwardCausalityTopologicalDefectsSpec(
                key=key,
                context_id=str(metadata["context_id"]),
                validation_protocol=str(metadata["validation_protocol"]),
                manuscript="Paper 0 foundational extraction",
                section_path=str(anchors[0]["section_path"]),
                canonical_statement=str(metadata["canonical_statement"]),
                source_equation_ids=tuple(metadata["source_equation_ids"]),
                source_ledger_ids=SOURCE_LEDGER_IDS,
                source_record_ids=tuple(str(record["source_record_id"]) for record in anchors),
                source_block_indices=tuple(
                    int(record["source_block_index"]) for record in anchors
                ),
                source_formulae=tuple(metadata["source_formulae"]),
                test_protocols=tuple(metadata["test_protocols"]),
                null_results=tuple(metadata["null_results"]),
                variables=tuple(metadata["variables"]),
                validation_targets=tuple(metadata["validation_targets"]),
                executable_validation_targets=tuple(metadata["validation_targets"]),
                null_controls=tuple(metadata["null_controls"]),
                claim_boundary=CLAIM_BOUNDARY,
                implementation_status="promoted_source_accounting_fixture",
                domain_review_status="source_bounded_no_empirical_validation",
                hardware_status=HARDWARE_STATUS,
            )
        )

    consumed = sorted({ledger_id for spec in specs for ledger_id in spec.source_ledger_ids})
    summary = {
        "title": "Paper 0 "
        + "VII. Field Generation and Upward Causality (Topological Defects)"
        + " Specs",
        "source_ledger_span": [SOURCE_LEDGER_IDS[0], SOURCE_LEDGER_IDS[-1]],
        "source_record_count": len(SOURCE_LEDGER_IDS),
        "consumed_source_record_count": len(consumed),
        "coverage_match": tuple(consumed) == SOURCE_LEDGER_IDS,
        "unconsumed_source_ledger_ids": sorted(set(SOURCE_LEDGER_IDS) - set(consumed)),
        "spec_count": len(specs),
        "spec_keys": [spec.key for spec in specs],
        "category_counts": dict(sorted(category_counts.items())),
        "block_type_counts": dict(sorted(block_counts.items())),
        "math_ids": sorted(
            {math_id for record in anchors for math_id in record.get("math_ids", [])}
        ),
        "image_ids": sorted(
            {image_id for record in anchors for image_id in record.get("image_ids", [])}
        ),
        "table_ids": sorted(
            {str(record["table_id"]) for record in anchors if record.get("table_id") is not None}
        ),
        "claim_boundary": CLAIM_BOUNDARY,
        "hardware_status": HARDWARE_STATUS,
        "next_source_boundary": "P0R03260",
    }
    return ViiFieldGenerationAndUpwardCausalityTopologicalDefectsSpecBundle(
        specs=tuple(specs), summary=summary
    )


def build_from_ledger(
    ledger_path: Path = DEFAULT_LEDGER_PATH,
) -> ViiFieldGenerationAndUpwardCausalityTopologicalDefectsSpecBundle:
    """Build specs from the canonical Paper 0 review ledger."""
    return build_vii_field_generation_and_upward_causality_topological_defects_specs(
        load_jsonl(ledger_path)
    )


def _json_ready(value: Any) -> Any:
    if isinstance(value, tuple):
        return [_json_ready(item) for item in value]
    if isinstance(value, list):
        return [_json_ready(item) for item in value]
    if isinstance(value, dict):
        return {str(key): _json_ready(item) for key, item in value.items()}
    return value


def render_report(bundle: ViiFieldGenerationAndUpwardCausalityTopologicalDefectsSpecBundle) -> str:
    """Render a Markdown source-accounting report."""
    lines = [
        "# Paper 0 "
        + "VII. Field Generation and Upward Causality (Topological Defects)"
        + " Specs",
        "",
        f"- Source span: {bundle.summary['source_ledger_span'][0]} - {bundle.summary['source_ledger_span'][1]}",
        f"- Source records: {bundle.summary['source_record_count']}",
        f"- Consumed source records: {bundle.summary['consumed_source_record_count']}",
        f"- Coverage match: {bundle.summary['coverage_match']}",
        f"- Spec count: {bundle.summary['spec_count']}",
        f"- Claim boundary: {bundle.summary['claim_boundary']}",
        f"- Hardware status: {bundle.summary['hardware_status']}",
        f"- Next source boundary: {bundle.summary['next_source_boundary']}",
        "",
        "## Specs",
    ]
    for spec in bundle.specs:
        lines.extend(
            [
                f"### `{spec.key}`",
                "",
                spec.canonical_statement,
                "",
                f"- Context: `{spec.context_id}`",
                f"- Protocol: `{spec.validation_protocol}`",
                f"- Source equations: {', '.join(spec.source_equation_ids)}",
                f"- Null controls: {', '.join(spec.null_controls)}",
                "",
            ]
        )
    return "\n".join(lines)


def write_outputs(
    bundle: ViiFieldGenerationAndUpwardCausalityTopologicalDefectsSpecBundle,
    *,
    output_dir: Path = DEFAULT_EXTRACTION_DIR,
    date_tag: str = "2026-05-17",
) -> dict[str, Path]:
    """Write JSON and Markdown artefacts for the spec bundle."""
    output_dir.mkdir(parents=True, exist_ok=True)
    json_path = (
        output_dir
        / f"paper0_vii_field_generation_and_upward_causality_topological_defects_validation_specs_{date_tag}.json"
    )
    report_path = (
        output_dir
        / f"paper0_vii_field_generation_and_upward_causality_topological_defects_validation_specs_{date_tag}.md"
    )
    payload = {
        "specs": [_json_ready(asdict(spec)) for spec in bundle.specs],
        "summary": _json_ready(bundle.summary),
    }
    json_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    report_path.write_text(render_report(bundle) + "\n", encoding="utf-8")
    return {"json": json_path, "report": report_path}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ledger", type=Path, default=DEFAULT_LEDGER_PATH)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_EXTRACTION_DIR)
    parser.add_argument("--date-tag", default="2026-05-17")
    args = parser.parse_args()
    outputs = write_outputs(
        build_from_ledger(args.ledger), output_dir=args.output_dir, date_tag=args.date_tag
    )
    print(outputs["json"])
    print(outputs["report"])


if __name__ == "__main__":
    main()
