#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# (c) Concepts 1996-2026 Miroslav Sotek. All rights reserved.
# (c) Code 2020-2026 Miroslav Sotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# scpn-quantum-control -- Paper 0 The Information-Geometric Coarse-Graining Lemma: Constructing the Macrostates Manifold spec builder
"""Promote Paper 0 The Information-Geometric Coarse-Graining Lemma: Constructing the Macrostates Manifold records."""

from __future__ import annotations

import argparse
import json
from collections import Counter
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXTRACTION_DIR = (
    REPO_ROOT
    / "paper"
    / "gotm_scpn_master_publications"
    / "gotm-scpn_paper-00_the_foundational_framework"
    / "source_validation_artifacts"
)
DEFAULT_LEDGER_PATH = DEFAULT_EXTRACTION_DIR / "paper0_canonical_review_ledger_2026-05-13.jsonl"

SOURCE_LEDGER_IDS = (
    "P0R04151",
    "P0R04152",
    "P0R04153",
    "P0R04154",
    "P0R04155",
    "P0R04156",
    "P0R04157",
    "P0R04158",
    "P0R04159",
    "P0R04160",
    "P0R04161",
    "P0R04162",
    "P0R04163",
    "P0R04164",
    "P0R04165",
    "P0R04166",
    "P0R04167",
)
CLAIM_BOUNDARY = "source-bounded the information geometric coarse graining lemma constructing the macrost source-accounting bridge; not validation evidence"
HARDWARE_STATUS = "source_methodology_no_experiment"

SPEC_CONTENT: dict[str, dict[str, tuple[str, ...] | str]] = {
    "the_information_geometric_coarse_graining_lemma_constructing_the_macrost.the_information_geometric_coarse_graining_lemma_constructing_the_macrost": {
        "context_id": "the_information_geometric_coarse_graining_lemma_constructing_the_macrost",
        "validation_protocol": "paper0.the_information_geometric_coarse_graining_lemma_constructing_the_macrost.the_information_geometric_coarse_graining_lemma_constructing_the_macrost",
        "canonical_statement": "The source-bounded component 'The Information-Geometric Coarse-Graining Lemma: Constructing the Macrostates Manifold' preserves Paper 0 records P0R04151-P0R04167 without empirical validation claims.",
        "source_equation_ids": (
            "P0R04151:the_information_geometric_coarse_graining_lemma_constructing_the_macrost",
            "P0R04152:the_information_geometric_coarse_graining_lemma_constructing_the_macrost",
            "P0R04153:the_information_geometric_coarse_graining_lemma_constructing_the_macrost",
            "P0R04154:the_information_geometric_coarse_graining_lemma_constructing_the_macrost",
            "P0R04155:the_information_geometric_coarse_graining_lemma_constructing_the_macrost",
            "P0R04156:the_information_geometric_coarse_graining_lemma_constructing_the_macrost",
            "P0R04157:the_information_geometric_coarse_graining_lemma_constructing_the_macrost",
            "P0R04158:the_information_geometric_coarse_graining_lemma_constructing_the_macrost",
            "P0R04159:the_information_geometric_coarse_graining_lemma_constructing_the_macrost",
            "P0R04160:the_information_geometric_coarse_graining_lemma_constructing_the_macrost",
            "P0R04161:the_information_geometric_coarse_graining_lemma_constructing_the_macrost",
            "P0R04162:the_information_geometric_coarse_graining_lemma_constructing_the_macrost",
            "P0R04163:the_information_geometric_coarse_graining_lemma_constructing_the_macrost",
            "P0R04164:the_information_geometric_coarse_graining_lemma_constructing_the_macrost",
            "P0R04165:the_information_geometric_coarse_graining_lemma_constructing_the_macrost",
            "P0R04166:the_information_geometric_coarse_graining_lemma_constructing_the_macrost",
            "P0R04167:the_information_geometric_coarse_graining_lemma_constructing_the_macrost",
        ),
        "source_formulae": (
            "P0R04151: The Information-Geometric Coarse-Graining Lemma: Constructing the Macrostates Manifold",
            "P0R04152: P0R04152",
            'P0R04153: This lemma proves that the macroscopic "Consciousness Manifold" is a low-dimensional, emergent geometric object generated by the Renormalization Group (RG) flow of Layer 4, saving the Ricci curvature from blowing up to infinity.',
            "P0R04154: A critical mathematical subtlety arises when proposing that the qualitative character of experience is defined by the Ricci scalar curvature ($R$) and topological Betti numbers ($b_k$) of the Consciousness Manifold ($\\mathcal{M}$). The foundational statistical manifold of the human brain encompasses $\\sim 10^{11}$ neuronal degrees of freedom. The microscopic Fisher Information Metric ($g_{ij}^{micro}$) for this raw state space, $\\mathcal{X}_{micro}$, is hyper-dimensional. Attempting to calculate the Ricci curvature directly on $g_{ij}^{micro}$ is formally divergent and computationally intractable due to microscopic stochasticity. Continuous differential geometry cannot be naively applied to the raw $2^{10^{11}}$ phase space.",
            "P0R04155: To resolve this dimensionality curse, the SCPN framework posits that the Consciousness Manifold ($\\mathcal{M}_{macro}$) is not the microscopic state space, but a low-dimensional, emergent geometric structure. It is generated by a formal Information-Geometric Coarse-Graining process, driven by the Renormalization Group (RG) flow of the Layer 4 Unified Phase Dynamics Equation (UPDE).",
            "P0R04156: 1. The Projection via UPDE Synchrony",
            "P0R04157: As the Layer 4 UPDE drives local neuronal ensembles into phase-locked synchrony, the microscopic degrees of freedom collapse into a vastly smaller set of macroscopic order parameters (e.g., regional phase coherences, $\\phi^\\mu$). This physical synchronization acts as a mathematical projection map, $\\pi_{RG}$, from the microscopic state space to the macroscopic manifold:",
            "P0R04158: $$\\pi_{RG}: \\mathcal{X}_{micro} \\to \\mathcal{M}_{macro}$$",
            "P0R04159: 2. The Effective Macroscopic Metric",
            "P0R04160: The geometry of the Consciousness Manifold is defined by the effective Fisher Information Metric ($g_{\\mu\\nu}^{macro}$) evaluated exclusively on these macroscopic order parameters. By treating the microscopic fluctuations as a thermal bath that is integrated out during the RG flow, the effective metric is obtained via the pushforward of the microscopic metric:",
            "P0R04161: $$g_{\\mu\\nu}^{macro} = \\sum_{i,j} \\frac{\\partial \\theta^i}{\\partial \\phi^\\mu} g_{ij}^{micro} \\frac{\\partial \\theta^j}{\\partial \\phi^\\nu}$$",
            "P0R04162: where $\\theta^i$ represents the microscopic parameters and $\\phi^\\mu$ represents the emergent macroscopic parameters.",
            "P0R04163: 3. Resolving Divergence",
            "P0R04164: Because the dimension of $\\phi^\\mu$ is many orders of magnitude smaller than $\\theta^i$ (representing large-scale brain network states rather than individual neurons), the effective metric $g_{\\mu\\nu}^{macro}$ is smooth, finite, and computationally tractable.",
            "P0R04165: It is strictly on this low-dimensional, emergent manifold $\\mathcal{M}_{macro}$ that the subjective qualities of consciousness manifest. Therefore, the Ricci scalar ($R$) representing emotional valence, and the Betti numbers ($b_k$) representing qualia richness, are mathematically well-defined:",
            "P0R04166: $$R_{macro} = g_{macro}^{\\mu\\nu} R_{\\mu\\nu}^{macro}$$",
            "P0R04167: This Information-Geometric Coarse-Graining Lemma ensures that the framework's topological and geometric claims are shielded from microscopic infinities. It formally justifies the use of macroscopic neuroimaging techniques (such as EEG or fMRI) as valid boundary data for Topological Data Analysis (TDA), because the sensors are measuring the exact macroscopic order parameters ($\\phi^\\mu$) that define the geometry of the effective Consciousness Manifold.",
        ),
        "test_protocols": (
            "preserve The Information-Geometric Coarse-Graining Lemma: Constructing the Macrostates Manifold source-accounting boundary",
        ),
        "null_results": (
            "The Information-Geometric Coarse-Graining Lemma: Constructing the Macrostates Manifold is not empirical validation evidence",
        ),
        "variables": ("the_information_geometric_coarse_graining_lemma_constructing_the_macrost",),
        "validation_targets": ("preserve records P0R04151-P0R04167",),
        "null_controls": (
            "the_information_geometric_coarse_graining_lemma_constructing_the_macrost must remain source-bounded accounting",
        ),
    }
}


@dataclass(frozen=True, slots=True)
class TheInformationGeometricCoarseGrainingLemmaConstructingTheMacrostSpec:
    """Spec promoted from Paper 0 source records."""

    key: str
    context_id: str
    validation_protocol: str
    manuscript: str
    section_path: str
    canonical_statement: str
    source_equation_ids: tuple[str, ...]
    source_ledger_ids: tuple[str, ...]
    source_record_ids: tuple[str, ...]
    source_block_indices: tuple[int, ...]
    source_formulae: tuple[str, ...]
    test_protocols: tuple[str, ...]
    null_results: tuple[str, ...]
    variables: tuple[str, ...]
    validation_targets: tuple[str, ...]
    executable_validation_targets: tuple[str, ...]
    null_controls: tuple[str, ...]
    claim_boundary: str
    implementation_status: str
    domain_review_status: str
    hardware_status: str


@dataclass(frozen=True, slots=True)
class TheInformationGeometricCoarseGrainingLemmaConstructingTheMacrostSpecBundle:
    """Specs plus source coverage summary."""

    specs: tuple[TheInformationGeometricCoarseGrainingLemmaConstructingTheMacrostSpec, ...]
    summary: dict[str, Any]


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    """Load a JSONL ledger into dictionaries."""
    records: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            stripped = line.strip()
            if not stripped:
                continue
            try:
                records.append(json.loads(stripped))
            except json.JSONDecodeError as exc:
                raise ValueError(f"invalid JSONL at {path}:{line_number}") from exc
    return records


def build_the_information_geometric_coarse_graining_lemma_constructing_the_macrost_specs(
    source_records: list[dict[str, Any]],
) -> TheInformationGeometricCoarseGrainingLemmaConstructingTheMacrostSpecBundle:
    """Build source-covered specs."""
    records_by_ledger = {str(record["ledger_id"]): record for record in source_records}
    missing = sorted(set(SOURCE_LEDGER_IDS) - set(records_by_ledger))
    if missing:
        raise ValueError(f"missing required source ledger ids: {missing}")

    anchors = [records_by_ledger[ledger_id] for ledger_id in SOURCE_LEDGER_IDS]
    category_counts = Counter(
        str(record.get("canonical_category", "unknown")) for record in anchors
    )
    block_counts = Counter(str(record.get("block_type", "unknown")) for record in anchors)

    specs: list[TheInformationGeometricCoarseGrainingLemmaConstructingTheMacrostSpec] = []
    for key, metadata in SPEC_CONTENT.items():
        specs.append(
            TheInformationGeometricCoarseGrainingLemmaConstructingTheMacrostSpec(
                key=key,
                context_id=str(metadata["context_id"]),
                validation_protocol=str(metadata["validation_protocol"]),
                manuscript="Paper 0 foundational extraction",
                section_path=str(anchors[0]["section_path"]),
                canonical_statement=str(metadata["canonical_statement"]),
                source_equation_ids=tuple(metadata["source_equation_ids"]),
                source_ledger_ids=SOURCE_LEDGER_IDS,
                source_record_ids=tuple(str(record["source_record_id"]) for record in anchors),
                source_block_indices=tuple(
                    int(record["source_block_index"]) for record in anchors
                ),
                source_formulae=tuple(metadata["source_formulae"]),
                test_protocols=tuple(metadata["test_protocols"]),
                null_results=tuple(metadata["null_results"]),
                variables=tuple(metadata["variables"]),
                validation_targets=tuple(metadata["validation_targets"]),
                executable_validation_targets=tuple(metadata["validation_targets"]),
                null_controls=tuple(metadata["null_controls"]),
                claim_boundary=CLAIM_BOUNDARY,
                implementation_status="promoted_source_accounting_fixture",
                domain_review_status="source_bounded_no_empirical_validation",
                hardware_status=HARDWARE_STATUS,
            )
        )

    consumed = sorted({ledger_id for spec in specs for ledger_id in spec.source_ledger_ids})
    summary = {
        "title": "Paper 0 "
        + "The Information-Geometric Coarse-Graining Lemma: Constructing the Macrostates Manifold"
        + " Specs",
        "source_ledger_span": [SOURCE_LEDGER_IDS[0], SOURCE_LEDGER_IDS[-1]],
        "source_record_count": len(SOURCE_LEDGER_IDS),
        "consumed_source_record_count": len(consumed),
        "coverage_match": tuple(consumed) == SOURCE_LEDGER_IDS,
        "unconsumed_source_ledger_ids": sorted(set(SOURCE_LEDGER_IDS) - set(consumed)),
        "spec_count": len(specs),
        "spec_keys": [spec.key for spec in specs],
        "category_counts": dict(sorted(category_counts.items())),
        "block_type_counts": dict(sorted(block_counts.items())),
        "math_ids": sorted(
            {math_id for record in anchors for math_id in record.get("math_ids", [])}
        ),
        "image_ids": sorted(
            {image_id for record in anchors for image_id in record.get("image_ids", [])}
        ),
        "table_ids": sorted(
            {str(record["table_id"]) for record in anchors if record.get("table_id") is not None}
        ),
        "claim_boundary": CLAIM_BOUNDARY,
        "hardware_status": HARDWARE_STATUS,
        "next_source_boundary": "P0R04168",
    }
    return TheInformationGeometricCoarseGrainingLemmaConstructingTheMacrostSpecBundle(
        specs=tuple(specs), summary=summary
    )


def build_from_ledger(
    ledger_path: Path = DEFAULT_LEDGER_PATH,
) -> TheInformationGeometricCoarseGrainingLemmaConstructingTheMacrostSpecBundle:
    """Build specs from the canonical Paper 0 review ledger."""
    return build_the_information_geometric_coarse_graining_lemma_constructing_the_macrost_specs(
        load_jsonl(ledger_path)
    )


def _json_ready(value: Any) -> Any:
    if isinstance(value, tuple):
        return [_json_ready(item) for item in value]
    if isinstance(value, list):
        return [_json_ready(item) for item in value]
    if isinstance(value, dict):
        return {str(key): _json_ready(item) for key, item in value.items()}
    return value


def render_report(
    bundle: TheInformationGeometricCoarseGrainingLemmaConstructingTheMacrostSpecBundle,
) -> str:
    """Render a Markdown source-accounting report."""
    lines = [
        "# Paper 0 "
        + "The Information-Geometric Coarse-Graining Lemma: Constructing the Macrostates Manifold"
        + " Specs",
        "",
        f"- Source span: {bundle.summary['source_ledger_span'][0]} - {bundle.summary['source_ledger_span'][1]}",
        f"- Source records: {bundle.summary['source_record_count']}",
        f"- Consumed source records: {bundle.summary['consumed_source_record_count']}",
        f"- Coverage match: {bundle.summary['coverage_match']}",
        f"- Spec count: {bundle.summary['spec_count']}",
        f"- Claim boundary: {bundle.summary['claim_boundary']}",
        f"- Hardware status: {bundle.summary['hardware_status']}",
        f"- Next source boundary: {bundle.summary['next_source_boundary']}",
        "",
        "## Specs",
    ]
    for spec in bundle.specs:
        lines.extend(
            [
                f"### `{spec.key}`",
                "",
                spec.canonical_statement,
                "",
                f"- Context: `{spec.context_id}`",
                f"- Protocol: `{spec.validation_protocol}`",
                f"- Source equations: {', '.join(spec.source_equation_ids)}",
                f"- Null controls: {', '.join(spec.null_controls)}",
                "",
            ]
        )
    return "\n".join(lines)


def write_outputs(
    bundle: TheInformationGeometricCoarseGrainingLemmaConstructingTheMacrostSpecBundle,
    *,
    output_dir: Path = DEFAULT_EXTRACTION_DIR,
    date_tag: str = "2026-05-17",
) -> dict[str, Path]:
    """Write JSON and Markdown artefacts for the spec bundle."""
    output_dir.mkdir(parents=True, exist_ok=True)
    json_path = (
        output_dir
        / f"paper0_the_information_geometric_coarse_graining_lemma_constructing_the_macrost_validation_specs_{date_tag}.json"
    )
    report_path = (
        output_dir
        / f"paper0_the_information_geometric_coarse_graining_lemma_constructing_the_macrost_validation_specs_{date_tag}.md"
    )
    payload = {
        "specs": [_json_ready(asdict(spec)) for spec in bundle.specs],
        "summary": _json_ready(bundle.summary),
    }
    json_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    report_path.write_text(render_report(bundle) + "\n", encoding="utf-8")
    return {"json": json_path, "report": report_path}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ledger", type=Path, default=DEFAULT_LEDGER_PATH)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_EXTRACTION_DIR)
    parser.add_argument("--date-tag", default="2026-05-17")
    args = parser.parse_args()
    outputs = write_outputs(
        build_from_ledger(args.ledger), output_dir=args.output_dir, date_tag=args.date_tag
    )
    print(outputs["json"])
    print(outputs["report"])


if __name__ == "__main__":
    main()
