#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# (c) Concepts 1996-2026 Miroslav Sotek. All rights reserved.
# (c) Code 2020-2026 Miroslav Sotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# scpn-quantum-control -- Paper 0 Layer 5 Active Inference spec builder
"""Promote Paper 0 Layer 5 Active Inference records into validation specs."""

from __future__ import annotations

import argparse
import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXTRACTION_DIR = REPO_ROOT / "docs" / "internal" / "paper0_foundational_extraction"
DEFAULT_LEDGER_PATH = DEFAULT_EXTRACTION_DIR / "paper0_canonical_review_ledger_2026-05-13.jsonl"

SOURCE_LEDGER_IDS = tuple(f"P0R{number:05d}" for number in range(6434, 6450))
STRUCTURAL_SOURCE_LEDGER_IDS = (
    "P0R06434",
    "P0R06436",
    "P0R06439",
    "P0R06441",
    "P0R06445",
    "P0R06449",
)
CAPTION_SOURCE_LEDGER_IDS = ("P0R06437", "P0R06440", "P0R06446")

MECHANISMS_BY_SPEC = {
    "l5_active_inference.attractor_geometry": (
        (),
        (),
        (
            "integrated self is represented as a self-referential strange loop",
            "emotional qualia are bounded to attractor-manifold topology",
            "basins, loops, gradient flow, and saddle boundaries define qualitative regimes",
        ),
    ),
    "l5_active_inference.hpc_triple_network_loop": (
        (),
        (),
        (
            "downward generative projection issues predictions",
            "upward inference flow propagates precision-weighted prediction error",
            "salience network/anterior insula biases CEN versus DMN mode dominance",
        ),
    ),
    "l5_active_inference.fep_perception_action_loop": (
        ("P0R06442:variational_free_energy", "P0R06446:prediction_error_epsilon"),
        (
            "variational free energy upper-bounds surprise",
            "prediction error epsilon is generated by sensory data minus predictions",
            "policy/action changes the environment to reduce future error",
        ),
        (),
    ),
    "l5_active_inference.cosmic_prior_boundary": (
        ("P0R06447:SEC_prior_identity", "P0R06448:cosmic_active_inference_prior"),
        (
            "SEC is identified with the ultimate prior belief of the cosmic generative model",
            "global free-energy minimisation is framed as a 15-layer stack imperative",
        ),
        (
            "cosmic-scale Active Inference is retained as a speculative source claim",
            "ethical coherence is bounded to a proposed prior, not established physics",
            "meaningful-existence prior must not be treated as measured evidence",
        ),
    ),
}

SPEC_METADATA: dict[str, dict[str, tuple[str, ...] | str]] = {
    "l5_active_inference.attractor_geometry": {
        "validation_protocol": "paper0.l5_active_inference.attractor_geometry",
        "canonical_statement": (
            "Layer 5 frames integrated selfhood and emotional qualia as topology over "
            "attractor manifolds, with qualitative regimes separated by saddle boundaries."
        ),
        "variables": ("basins", "loops", "gradient_flow", "saddle_boundaries"),
        "validation_targets": (
            "preserve attractor-manifold topology",
            "preserve basin, loop, gradient-flow, and saddle-boundary language",
            "reject qualia topology as direct empirical measurement",
        ),
        "null_controls": (
            "missing-saddle-boundary control must be rejected",
            "missing-loop-topology control must be rejected",
            "measured-qualia-evidence control must be rejected",
        ),
    },
    "l5_active_inference.hpc_triple_network_loop": {
        "validation_protocol": "paper0.l5_active_inference.hpc_triple_network_loop",
        "canonical_statement": (
            "The Layer 5 loop combines downward generative prediction, upward "
            "prediction-error propagation, Salience Network/anterior-insula precision "
            "weighting, and CEN/DMN mode biasing."
        ),
        "variables": ("prediction", "prediction_error", "salience_network", "CEN", "DMN"),
        "validation_targets": (
            "preserve downward and upward HPC flow directions",
            "preserve salience/anterior-insula precision weighting",
            "preserve CEN versus DMN mode-dominance biasing",
        ),
        "null_controls": (
            "missing-salience-gate control must be rejected",
            "missing-upward-error-flow control must be rejected",
            "single-network-loop control must be rejected",
        ),
    },
    "l5_active_inference.fep_perception_action_loop": {
        "validation_protocol": "paper0.l5_active_inference.fep_perception_action_loop",
        "canonical_statement": (
            "The FEP framing is bounded to variational free energy as an upper bound "
            "on surprise, with perception as belief update and action as policy-driven "
            "environmental change that reduces future prediction error."
        ),
        "variables": ("free_energy", "surprise", "prediction_error", "policy", "belief"),
        "validation_targets": (
            "preserve free-energy upper-bound wording",
            "preserve prediction-error, action, and belief-update terms",
            "reject incomplete perception-action loops",
        ),
        "null_controls": (
            "missing-free-energy-bound control must be rejected",
            "missing-action-policy control must be rejected",
            "missing-belief-update control must be rejected",
        ),
    },
    "l5_active_inference.cosmic_prior_boundary": {
        "validation_protocol": "paper0.l5_active_inference.cosmic_prior_boundary",
        "canonical_statement": (
            "The SEC/FEP cosmic-prior identification is retained as a speculative "
            "manuscript boundary condition requiring separate falsification; it is not "
            "promoted as established empirical physics."
        ),
        "variables": ("SEC", "ethical_functional", "cosmic_prior", "global_free_energy"),
        "validation_targets": (
            "preserve SEC-as-prior wording",
            "preserve 15-layer global free-energy framing",
            "reject treating SEC/FEP identity as established physics",
        ),
        "null_controls": (
            "reject treating SEC/FEP identity as established physics",
            "cosmic-prior empirical-claim control must be rejected",
            "missing-speculative-boundary control must be rejected",
        ),
    },
}


@dataclass(frozen=True, slots=True)
class L5ActiveInferenceValidationSpec:
    """Validation spec promoted from Paper 0 Layer 5 Active Inference records."""

    key: str
    validation_protocol: str
    manuscript: str
    section_path: str
    canonical_statement: str
    source_equation_ids: tuple[str, ...]
    source_formulae: tuple[str, ...]
    source_mechanisms: tuple[str, ...]
    source_ledger_ids: tuple[str, ...]
    source_record_ids: tuple[str, ...]
    source_block_indices: tuple[int, ...]
    anchor_math_ids: tuple[str, ...]
    image_ledger_ids: tuple[str, ...]
    caption_ledger_ids: tuple[str, ...]
    variables: tuple[str, ...]
    validation_targets: tuple[str, ...]
    executable_validation_targets: tuple[str, ...]
    null_controls: tuple[str, ...]
    claim_boundary: str
    implementation_status: str
    domain_review_status: str
    hardware_status: str


@dataclass(frozen=True, slots=True)
class L5ActiveInferenceValidationSpecBundle:
    """Layer 5 Active Inference validation specs plus coverage summary."""

    specs: tuple[L5ActiveInferenceValidationSpec, ...]
    summary: dict[str, Any]


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    """Load a JSONL ledger into dictionaries."""
    records: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            stripped = line.strip()
            if not stripped:
                continue
            try:
                records.append(json.loads(stripped))
            except json.JSONDecodeError as exc:
                raise ValueError(f"invalid JSONL at {path}:{line_number}") from exc
    return records


def build_l5_active_inference_specs(
    source_records: list[dict[str, Any]],
) -> L5ActiveInferenceValidationSpecBundle:
    """Build source-covered validation specs for Layer 5 Active Inference records."""
    records_by_ledger = {str(record["ledger_id"]): record for record in source_records}
    missing = sorted(set(SOURCE_LEDGER_IDS) - set(records_by_ledger))
    if missing:
        raise ValueError(f"missing required source ledger ids: {missing}")

    anchors = [records_by_ledger[ledger_id] for ledger_id in SOURCE_LEDGER_IDS]
    specs: list[L5ActiveInferenceValidationSpec] = []
    for key, (equation_ids, formulae, mechanisms) in MECHANISMS_BY_SPEC.items():
        metadata = SPEC_METADATA[key]
        claim_boundary = (
            "source-bounded Layer 5 Active Inference simulator contract; "
            "speculative cosmological prior; not empirical evidence"
            if key == "l5_active_inference.cosmic_prior_boundary"
            else "source-bounded Layer 5 Active Inference simulator contract; not empirical evidence"
        )
        specs.append(
            L5ActiveInferenceValidationSpec(
                key=key,
                validation_protocol=str(metadata["validation_protocol"]),
                manuscript="Paper 0 - The Foundational Framework",
                section_path=str(anchors[0]["section_path"]),
                canonical_statement=str(metadata["canonical_statement"]),
                source_equation_ids=tuple(equation_ids),
                source_formulae=tuple(formulae),
                source_mechanisms=tuple(mechanisms),
                source_ledger_ids=SOURCE_LEDGER_IDS,
                source_record_ids=tuple(str(record["source_record_id"]) for record in anchors),
                source_block_indices=tuple(
                    int(record["source_block_index"]) for record in anchors
                ),
                anchor_math_ids=tuple(
                    math_id for record in anchors for math_id in tuple(record.get("math_ids", ()))
                ),
                image_ledger_ids=tuple(
                    record["ledger_id"]
                    for record in anchors
                    if record["ledger_id"] in STRUCTURAL_SOURCE_LEDGER_IDS
                    and record.get("image_ids")
                ),
                caption_ledger_ids=CAPTION_SOURCE_LEDGER_IDS,
                variables=tuple(metadata["variables"]),
                validation_targets=tuple(metadata["validation_targets"]),
                executable_validation_targets=tuple(metadata["validation_targets"]),
                null_controls=tuple(metadata["null_controls"]),
                claim_boundary=claim_boundary,
                implementation_status="implemented",
                domain_review_status="source_promoted_requires_empirical_review",
                hardware_status="simulator_only_no_provider_submission",
            )
        )

    summary: dict[str, Any] = {
        "title": "Paper 0 Layer 5 Active Inference Specs",
        "source_ledger_span": [SOURCE_LEDGER_IDS[0], SOURCE_LEDGER_IDS[-1]],
        "source_record_count": len(SOURCE_LEDGER_IDS),
        "consumed_source_record_count": len(anchors),
        "coverage_match": len(anchors) == len(SOURCE_LEDGER_IDS),
        "structural_source_ledger_ids": list(STRUCTURAL_SOURCE_LEDGER_IDS),
        "caption_source_ledger_ids": list(CAPTION_SOURCE_LEDGER_IDS),
        "spec_count": len(specs),
        "spec_keys": [spec.key for spec in specs],
        "hardware_status": "simulator_only_no_provider_submission",
        "claim_boundary": "source-bounded Layer 5 Active Inference simulator contract; not empirical evidence",
    }
    return L5ActiveInferenceValidationSpecBundle(specs=tuple(specs), summary=summary)


def build_validation_report(bundle: L5ActiveInferenceValidationSpecBundle) -> str:
    """Render a compact Markdown report for human audit."""
    lines = [
        "# Paper 0 Layer 5 Active Inference Specs",
        "",
        f"- Source span: {bundle.summary['source_ledger_span'][0]} - {bundle.summary['source_ledger_span'][1]}",
        f"- Source records consumed: {bundle.summary['consumed_source_record_count']}",
        f"- Coverage match: {bundle.summary['coverage_match']}",
        f"- Hardware status: {bundle.summary['hardware_status']}",
        f"- Claim boundary: {bundle.summary['claim_boundary']}",
        "",
        "## Specs",
    ]
    for spec in bundle.specs:
        lines.extend(
            [
                "",
                f"### {spec.key}",
                "",
                spec.canonical_statement,
                "",
                "Validation targets:",
                *[f"- {target}" for target in spec.validation_targets],
                "",
                "Null controls:",
                *[f"- {control}" for control in spec.null_controls],
            ]
        )
    return "\n".join(lines) + "\n"


def write_outputs(
    *,
    bundle: L5ActiveInferenceValidationSpecBundle,
    output_path: Path,
    report_path: Path,
) -> None:
    """Write JSON and Markdown artefacts."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(
            {
                "summary": bundle.summary,
                "specs": [asdict(spec) for spec in bundle.specs],
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    report_path.write_text(build_validation_report(bundle), encoding="utf-8")


def main() -> int:
    """Build the default Layer 5 Active Inference validation-spec artefacts."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ledger", type=Path, default=DEFAULT_LEDGER_PATH)
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_EXTRACTION_DIR
        / "paper0_l5_active_inference_validation_specs_2026-05-13.json",
    )
    parser.add_argument(
        "--report",
        type=Path,
        default=DEFAULT_EXTRACTION_DIR
        / "paper0_l5_active_inference_validation_specs_report_2026-05-13.md",
    )
    args = parser.parse_args()

    bundle = build_l5_active_inference_specs(load_jsonl(args.ledger))
    write_outputs(bundle=bundle, output_path=args.output, report_path=args.report)
    print(json.dumps(bundle.summary, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
