#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# (c) Concepts 1996-2026 Miroslav Sotek. All rights reserved.
# (c) Code 2020-2026 Miroslav Sotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# scpn-quantum-control -- Paper 0 The Scaling Law of Consciousness (SLC) spec builder
"""Promote Paper 0 The Scaling Law of Consciousness (SLC) records."""

from __future__ import annotations

import argparse
import json
from collections import Counter
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXTRACTION_DIR = (
    REPO_ROOT
    / "paper"
    / "gotm_scpn_master_publications"
    / "gotm-scpn_paper-00_the_foundational_framework"
    / "source_validation_artifacts"
)
DEFAULT_LEDGER_PATH = DEFAULT_EXTRACTION_DIR / "paper0_canonical_review_ledger_2026-05-13.jsonl"

SOURCE_LEDGER_IDS = (
    "P0R03478",
    "P0R03479",
    "P0R03480",
    "P0R03481",
    "P0R03482",
    "P0R03483",
    "P0R03484",
    "P0R03485",
    "P0R03486",
    "P0R03487",
    "P0R03488",
    "P0R03489",
    "P0R03490",
    "P0R03491",
)
CLAIM_BOUNDARY = "source-bounded the scaling law of consciousness slc source-accounting bridge; not validation evidence"
HARDWARE_STATUS = "source_methodology_no_experiment"

SPEC_CONTENT: dict[str, dict[str, tuple[str, ...] | str]] = {
    "the_scaling_law_of_consciousness_slc.the_scaling_law_of_consciousness_slc": {
        "context_id": "the_scaling_law_of_consciousness_slc",
        "validation_protocol": "paper0.the_scaling_law_of_consciousness_slc.the_scaling_law_of_consciousness_slc",
        "canonical_statement": "The source-bounded component 'The Scaling Law of Consciousness (SLC)' preserves Paper 0 records P0R03478-P0R03491 without empirical validation claims.",
        "source_equation_ids": (
            "P0R03478:the_scaling_law_of_consciousness_slc",
            "P0R03479:the_scaling_law_of_consciousness_slc",
            "P0R03480:the_scaling_law_of_consciousness_slc",
            "P0R03481:the_scaling_law_of_consciousness_slc",
            "P0R03482:the_scaling_law_of_consciousness_slc",
            "P0R03483:the_scaling_law_of_consciousness_slc",
            "P0R03484:the_scaling_law_of_consciousness_slc",
            "P0R03485:the_scaling_law_of_consciousness_slc",
            "P0R03486:the_scaling_law_of_consciousness_slc",
            "P0R03487:the_scaling_law_of_consciousness_slc",
            "P0R03488:the_scaling_law_of_consciousness_slc",
            "P0R03489:the_scaling_law_of_consciousness_slc",
            "P0R03490:the_scaling_law_of_consciousness_slc",
            "P0R03491:the_scaling_law_of_consciousness_slc",
        ),
        "source_formulae": (
            "P0R03478: The Scaling Law of Consciousness (SLC)",
            "P0R03479: This section operationalises the first core assumption-the scalability of consciousness-by introducing the Scaling Law of Consciousness (SLC). This law provides a formal framework for relating the intensity and quality of consciousness to the complexity and connectivity of the underlying substrate. The SLC leverages the mathematical formalism of Integrated Information Theory (IIT), quantifying the degree of consciousness of any subsystem by its measure of integrated information, . This value represents the information generated by the system as a whole above and beyond the sum of its parts.",
            "P0R03480: The SLC posits that scales non-linearly with the number of components (N) and their connectivity (K), and that this value is maximised when the system operates in the quasicritical regime. This provides a direct, quantitative link between the system's dynamic state and its capacity for consciousness.",
            'P0R03481: The framework provides a geometric interpretation of this scaling law. The quality of consciousness (qualia) is determined by the geometry of the Consciousness Manifold. As a system scales up through the SCPN hierarchy, both its capacity for integrated information () and the topological complexity of its corresponding manifold (quantified by its Betti numbers, b_k) increase in a correlated manner. The text provides a crucial "working bound" that maps the abstract concept of to measurable observables derived from the manifold\'s topology and dynamics, anchoring the theory in a data-driven pipeline.',
            "P0R03482: The Qualia Complexity Saturation Bound",
            "P0R03483: The Scaling Law of Consciousness (SLC) is strictly bounded by the Topological Saturation Constant ($\\Lambda_{bk}$), preventing the Consciousness Manifold from exceeding the informational density of its physical realizer.",
            "P0R03484: Complexity Saturation Equation (Python Format):",
            "P0R03485: phi_max_density = (betti_sum * manifold_vol) / (n_neurons * k_connectivity)",
            "P0R03486: Legend:",
            "P0R03487: phi_max_density: Maximum integrated information per unit of biological hardware. | betti_sum: Total sum of non-zero Betti numbers ($b_k$) in the manifold $M$. | manifold_vol: Volume of the high-dimensional state-space reconstruction. | n_neurons: Number of active components in the Layer 4 substrate. | k_connectivity: Mean connectivity weight of the structural connectome.",
            'P0R03488: This section introduces a simple but powerful idea: the Scaling Law of Consciousness. It\'s a rule that explains how and why consciousness gets "bigger" and "richer" as systems become more complex.',
            'P0R03489: To do this, we borrow a concept from a theory called IIT, which gives us a way to measure consciousness with a number, called (pronounced "phi"). Think of as a "consciousness score." A rock might have a of nearly zero. A bacterium has a tiny bit more. A human brain has a vastly higher score. measures how unified and interconnected a system is-how much the whole is truly greater than the sum of its parts.',
            'P0R03490: Our Scaling Law states that this consciousness score () doesn\'t just grow steadily; it grows exponentially as you add more components (N) and more connections (K). And critically, the score is highest when the system is operating at the "edge of chaos."',
            'P0R03491: This also has a beautiful geometric meaning. As the consciousness score () increases from a microbe to a human to a planet, the "shape" of its experience in the Consciousness Manifold becomes infinitely more complex and beautiful, with more dimensions, loops, and intricate structures. This law provides a ruler for measuring consciousness across the entire universe.',
        ),
        "test_protocols": (
            "preserve The Scaling Law of Consciousness (SLC) source-accounting boundary",
        ),
        "null_results": (
            "The Scaling Law of Consciousness (SLC) is not empirical validation evidence",
        ),
        "variables": ("the_scaling_law_of_consciousness_slc",),
        "validation_targets": ("preserve records P0R03478-P0R03491",),
        "null_controls": (
            "the_scaling_law_of_consciousness_slc must remain source-bounded accounting",
        ),
    }
}


@dataclass(frozen=True, slots=True)
class TheScalingLawOfConsciousnessSlcSpec:
    """Spec promoted from Paper 0 source records."""

    key: str
    context_id: str
    validation_protocol: str
    manuscript: str
    section_path: str
    canonical_statement: str
    source_equation_ids: tuple[str, ...]
    source_ledger_ids: tuple[str, ...]
    source_record_ids: tuple[str, ...]
    source_block_indices: tuple[int, ...]
    source_formulae: tuple[str, ...]
    test_protocols: tuple[str, ...]
    null_results: tuple[str, ...]
    variables: tuple[str, ...]
    validation_targets: tuple[str, ...]
    executable_validation_targets: tuple[str, ...]
    null_controls: tuple[str, ...]
    claim_boundary: str
    implementation_status: str
    domain_review_status: str
    hardware_status: str


@dataclass(frozen=True, slots=True)
class TheScalingLawOfConsciousnessSlcSpecBundle:
    """Specs plus source coverage summary."""

    specs: tuple[TheScalingLawOfConsciousnessSlcSpec, ...]
    summary: dict[str, Any]


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    """Load a JSONL ledger into dictionaries."""
    records: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            stripped = line.strip()
            if not stripped:
                continue
            try:
                records.append(json.loads(stripped))
            except json.JSONDecodeError as exc:
                raise ValueError(f"invalid JSONL at {path}:{line_number}") from exc
    return records


def build_the_scaling_law_of_consciousness_slc_specs(
    source_records: list[dict[str, Any]],
) -> TheScalingLawOfConsciousnessSlcSpecBundle:
    """Build source-covered specs."""
    records_by_ledger = {str(record["ledger_id"]): record for record in source_records}
    missing = sorted(set(SOURCE_LEDGER_IDS) - set(records_by_ledger))
    if missing:
        raise ValueError(f"missing required source ledger ids: {missing}")

    anchors = [records_by_ledger[ledger_id] for ledger_id in SOURCE_LEDGER_IDS]
    category_counts = Counter(
        str(record.get("canonical_category", "unknown")) for record in anchors
    )
    block_counts = Counter(str(record.get("block_type", "unknown")) for record in anchors)

    specs: list[TheScalingLawOfConsciousnessSlcSpec] = []
    for key, metadata in SPEC_CONTENT.items():
        specs.append(
            TheScalingLawOfConsciousnessSlcSpec(
                key=key,
                context_id=str(metadata["context_id"]),
                validation_protocol=str(metadata["validation_protocol"]),
                manuscript="Paper 0 foundational extraction",
                section_path=str(anchors[0]["section_path"]),
                canonical_statement=str(metadata["canonical_statement"]),
                source_equation_ids=tuple(metadata["source_equation_ids"]),
                source_ledger_ids=SOURCE_LEDGER_IDS,
                source_record_ids=tuple(str(record["source_record_id"]) for record in anchors),
                source_block_indices=tuple(
                    int(record["source_block_index"]) for record in anchors
                ),
                source_formulae=tuple(metadata["source_formulae"]),
                test_protocols=tuple(metadata["test_protocols"]),
                null_results=tuple(metadata["null_results"]),
                variables=tuple(metadata["variables"]),
                validation_targets=tuple(metadata["validation_targets"]),
                executable_validation_targets=tuple(metadata["validation_targets"]),
                null_controls=tuple(metadata["null_controls"]),
                claim_boundary=CLAIM_BOUNDARY,
                implementation_status="promoted_source_accounting_fixture",
                domain_review_status="source_bounded_no_empirical_validation",
                hardware_status=HARDWARE_STATUS,
            )
        )

    consumed = sorted({ledger_id for spec in specs for ledger_id in spec.source_ledger_ids})
    summary = {
        "title": "Paper 0 " + "The Scaling Law of Consciousness (SLC)" + " Specs",
        "source_ledger_span": [SOURCE_LEDGER_IDS[0], SOURCE_LEDGER_IDS[-1]],
        "source_record_count": len(SOURCE_LEDGER_IDS),
        "consumed_source_record_count": len(consumed),
        "coverage_match": tuple(consumed) == SOURCE_LEDGER_IDS,
        "unconsumed_source_ledger_ids": sorted(set(SOURCE_LEDGER_IDS) - set(consumed)),
        "spec_count": len(specs),
        "spec_keys": [spec.key for spec in specs],
        "category_counts": dict(sorted(category_counts.items())),
        "block_type_counts": dict(sorted(block_counts.items())),
        "math_ids": sorted(
            {math_id for record in anchors for math_id in record.get("math_ids", [])}
        ),
        "image_ids": sorted(
            {image_id for record in anchors for image_id in record.get("image_ids", [])}
        ),
        "table_ids": sorted(
            {str(record["table_id"]) for record in anchors if record.get("table_id") is not None}
        ),
        "claim_boundary": CLAIM_BOUNDARY,
        "hardware_status": HARDWARE_STATUS,
        "next_source_boundary": "P0R03492",
    }
    return TheScalingLawOfConsciousnessSlcSpecBundle(specs=tuple(specs), summary=summary)


def build_from_ledger(
    ledger_path: Path = DEFAULT_LEDGER_PATH,
) -> TheScalingLawOfConsciousnessSlcSpecBundle:
    """Build specs from the canonical Paper 0 review ledger."""
    return build_the_scaling_law_of_consciousness_slc_specs(load_jsonl(ledger_path))


def _json_ready(value: Any) -> Any:
    if isinstance(value, tuple):
        return [_json_ready(item) for item in value]
    if isinstance(value, list):
        return [_json_ready(item) for item in value]
    if isinstance(value, dict):
        return {str(key): _json_ready(item) for key, item in value.items()}
    return value


def render_report(bundle: TheScalingLawOfConsciousnessSlcSpecBundle) -> str:
    """Render a Markdown source-accounting report."""
    lines = [
        "# Paper 0 " + "The Scaling Law of Consciousness (SLC)" + " Specs",
        "",
        f"- Source span: {bundle.summary['source_ledger_span'][0]} - {bundle.summary['source_ledger_span'][1]}",
        f"- Source records: {bundle.summary['source_record_count']}",
        f"- Consumed source records: {bundle.summary['consumed_source_record_count']}",
        f"- Coverage match: {bundle.summary['coverage_match']}",
        f"- Spec count: {bundle.summary['spec_count']}",
        f"- Claim boundary: {bundle.summary['claim_boundary']}",
        f"- Hardware status: {bundle.summary['hardware_status']}",
        f"- Next source boundary: {bundle.summary['next_source_boundary']}",
        "",
        "## Specs",
    ]
    for spec in bundle.specs:
        lines.extend(
            [
                f"### `{spec.key}`",
                "",
                spec.canonical_statement,
                "",
                f"- Context: `{spec.context_id}`",
                f"- Protocol: `{spec.validation_protocol}`",
                f"- Source equations: {', '.join(spec.source_equation_ids)}",
                f"- Null controls: {', '.join(spec.null_controls)}",
                "",
            ]
        )
    return "\n".join(lines)


def write_outputs(
    bundle: TheScalingLawOfConsciousnessSlcSpecBundle,
    *,
    output_dir: Path = DEFAULT_EXTRACTION_DIR,
    date_tag: str = "2026-05-17",
) -> dict[str, Path]:
    """Write JSON and Markdown artefacts for the spec bundle."""
    output_dir.mkdir(parents=True, exist_ok=True)
    json_path = (
        output_dir
        / f"paper0_the_scaling_law_of_consciousness_slc_validation_specs_{date_tag}.json"
    )
    report_path = (
        output_dir / f"paper0_the_scaling_law_of_consciousness_slc_validation_specs_{date_tag}.md"
    )
    payload = {
        "specs": [_json_ready(asdict(spec)) for spec in bundle.specs],
        "summary": _json_ready(bundle.summary),
    }
    json_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    report_path.write_text(render_report(bundle) + "\n", encoding="utf-8")
    return {"json": json_path, "report": report_path}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ledger", type=Path, default=DEFAULT_LEDGER_PATH)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_EXTRACTION_DIR)
    parser.add_argument("--date-tag", default="2026-05-17")
    args = parser.parse_args()
    outputs = write_outputs(
        build_from_ledger(args.ledger), output_dir=args.output_dir, date_tag=args.date_tag
    )
    print(outputs["json"])
    print(outputs["report"])


if __name__ == "__main__":
    main()
