#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Quantum Control — RL research-governance evidence runner
"""Generate or verify deterministic RL research-governance evidence."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from scpn_quantum_control.analysis import (
    build_rl_research_evidence_report,
    render_rl_research_evidence_markdown,
)

DEFAULT_JSON = Path("data/rl_research_governance/evidence.json")
DEFAULT_MARKDOWN = Path("data/rl_research_governance/evidence.md")


def _parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", type=Path, default=DEFAULT_JSON, dest="json_path")
    parser.add_argument("--markdown", type=Path, default=DEFAULT_MARKDOWN)
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare generated bytes with existing files instead of writing",
    )
    return parser


def _expected_bytes() -> tuple[bytes, bytes]:
    """Return canonical JSON and Markdown evidence bytes."""
    report = build_rl_research_evidence_report()
    json_bytes = (
        json.dumps(report.as_dict(), indent=2, sort_keys=True, ensure_ascii=False) + "\n"
    ).encode("utf-8")
    markdown_bytes = render_rl_research_evidence_markdown(report).encode("utf-8")
    return json_bytes, markdown_bytes


def _check_bytes(path: Path, expected: bytes) -> None:
    """Fail closed when committed evidence is missing or stale."""
    if not path.is_file():
        raise SystemExit(f"missing RL research evidence file: {path}")
    if path.read_bytes() != expected:
        raise SystemExit(f"stale RL research evidence file: {path}")


def main(argv: list[str] | None = None) -> int:
    """Write evidence files or verify their exact deterministic bytes."""
    args = _parser().parse_args(argv)
    json_bytes, markdown_bytes = _expected_bytes()
    if args.check:
        _check_bytes(args.json_path, json_bytes)
        _check_bytes(args.markdown, markdown_bytes)
        return 0
    args.json_path.parent.mkdir(parents=True, exist_ok=True)
    args.markdown.parent.mkdir(parents=True, exist_ok=True)
    args.json_path.write_bytes(json_bytes)
    args.markdown.write_bytes(markdown_bytes)
    return 0


if __name__ == "__main__":  # pragma: no cover - exercised by subprocess checks.
    raise SystemExit(main())
