# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Quantum Control — Hardware Backends
"""Hardware backend layer: classical exact solvers, IBM Quantum runner,
noise models, trapped-ion transpilation, and experiment definitions.
"""

from .aggregators import (
    AggregatorProviderRoute,
    ResolvedAggregatorProviderRoute,
    aggregator_provider_routes_for,
    built_in_aggregator_provider_routes,
    resolve_aggregator_provider_route,
)
from .analog_kuramoto import (
    AnalogBackendCapabilities,
    AnalogCouplingTerm,
    AnalogDriveTerm,
    AnalogFeedbackTerm,
    AnalogKuramotoBackend,
    AnalogKuramotoBackendProtocol,
    AnalogKuramotoPlatform,
    AnalogKuramotoProgram,
    AnalogProviderTarget,
    ProviderAnalogExecutionPlan,
    ProviderAnalogPayload,
    analog_kuramoto_factory,
    compile_analog_kuramoto,
    export_provider_payload,
    prepare_provider_execution_plan,
)
from .analog_native_readiness import (
    ANALOG_NATIVE_SCHEMA,
    AnalogNativePrimitiveComparison,
    AnalogNativeReadinessConfig,
    AnalogProviderReadinessRow,
    analog_native_markdown,
    analog_native_payload,
    compare_native_to_digital_primitives,
    provider_readiness_rows,
)
from .async_runner import AsyncHardwareRunner, AsyncJobHandle
from .backends import (
    BackendProtocol,
    BackendRegistrationError,
    BackendRegistry,
    QuantumBackendDescriptor,
    describe_backend,
    describe_hal_backend_profile,
    discover_backends,
    get_backend,
    get_registry,
    list_backends,
    list_hal_backend_descriptors,
    list_quantum_backends,
    register_backend,
    unregister_backend,
)
from .classical import (
    bloch_vectors_from_json,
    classical_brute_mpc,
    classical_exact_diag,
    classical_exact_evolution,
    classical_kuramoto_reference,
)
from .experiments import (
    ALL_EXPERIMENTS,
    ansatz_comparison_hw_experiment,
    bell_test_4q_experiment,
    correlator_4q_experiment,
    decoherence_scaling_experiment,
    kuramoto_4osc_experiment,
    kuramoto_4osc_trotter2_experiment,
    kuramoto_4osc_zne_experiment,
    kuramoto_8osc_experiment,
    kuramoto_8osc_zne_experiment,
    noise_baseline_experiment,
    qaoa_mpc_4_experiment,
    qkd_qber_4q_experiment,
    sync_threshold_experiment,
    upde_16_dd_experiment,
    upde_16_snapshot_experiment,
    vqe_4q_experiment,
    vqe_8q_experiment,
    vqe_8q_hardware_experiment,
    vqe_landscape_experiment,
    zne_higher_order_experiment,
)
from .feedback_capability_probe import (
    BackendCapabilitySnapshot,
    FeedbackCapabilityDecision,
    assess_feedback_backend_capability,
    assess_feedback_backend_fleet,
    required_s1_dynamic_features,
)
from .feedback_dryrun import (
    FeedbackDryRunPayload,
    build_analog_native_review_payload,
    build_ibm_runtime_dry_run,
    build_openqasm3_gate_dry_run,
    build_s1_feedback_dry_run_bundle,
)
from .feedback_hardware_scheduler import (
    ApprovalGatedFeedbackHardwareScheduler,
    HardwareApprovalRecord,
    HardwareSubmissionRecord,
    hash_package_manifest,
)
from .feedback_loop import (
    FeedbackCommand,
    FeedbackLoopConfig,
    FeedbackObserver,
    FeedbackResult,
    FeedbackRunner,
    FeedbackScheduler,
    FeedbackStepRecord,
    ProportionalMetricObserver,
    RealtimeControllerScheduler,
)
from .feedback_provider_metadata import (
    snapshot_from_generic_metadata,
    snapshot_from_qiskit_backend,
)
from .feedback_submission import (
    FeedbackBudgetEstimate,
    FeedbackCircuitSummary,
    FeedbackPlatformCapability,
    FeedbackSubmissionPackage,
    PlatformReadiness,
    assess_platform_readiness,
    build_s1_feedback_submission_package,
    default_s1_platforms,
    summarise_feedback_circuit,
)
from .hal import (
    BackendCapabilities,
    BackendProfile,
    HardwareAbstractionLayer,
    LocalDeterministicSimulator,
    QuantumBackend,
    QuantumJobRef,
    QuantumJobResult,
    QuantumWorkload,
    built_in_backend_profiles,
)
from .hal_azure import AzureQuantumHALAdapter, azure_openqasm3_to_workload
from .hal_braket import (
    BraketAwsHALAdapter,
    BraketLocalHALAdapter,
    braket_circuit_to_workload,
)
from .hal_cirq import CirqLocalHALAdapter, cirq_circuit_workload
from .hal_dwave import DWaveLeapHALAdapter, dwave_bqm_workload
from .hal_ionq import IonQCloudHALAdapter, ionq_qis_workload
from .hal_iqm import IQMHALAdapter, iqm_qiskit_workload
from .hal_oqc import OQCHALAdapter, oqc_openqasm3_workload
from .hal_pasqal import PasqalPulserHALAdapter, pulser_sequence_workload
from .hal_pennylane import PennyLaneDeviceHALAdapter, pennylane_gate_workload
from .hal_qbraid import QbraidRuntimeHALAdapter, qbraid_program_to_workload
from .hal_qiskit import (
    QiskitAerHALAdapter,
    QiskitRuntimeHALAdapter,
    qiskit_circuit_to_qasm3_workload,
    qiskit_circuit_to_workload,
)
from .hal_quandela import QuandelaPercevalHALAdapter, quandela_perceval_workload
from .hal_quantinuum import QuantinuumCloudHALAdapter, quantinuum_tket_workload
from .hal_quera_bloqade import QuEraBloqadeHALAdapter, bloqade_ahs_workload
from .hal_rigetti import RigettiQCSHALAdapter, rigetti_quil_workload
from .hal_strangeworks import (
    StrangeworksComputeHALAdapter,
    strangeworks_program_to_workload,
)
from .hybrid_digital_analog import (
    HybridCouplingAssignment,
    HybridCouplingPartition,
    HybridDigitalAnalogBackend,
    HybridDigitalAnalogBackendProtocol,
    HybridDigitalAnalogProgram,
    HybridRoute,
    compile_hybrid_digital_analog,
    hybrid_digital_analog_factory,
    partition_kuramoto_couplings,
)
from .iqm_backend import (
    IQMBackendConfig,
    IQMQuantumBackend,
    IQMRunResult,
    iqm_factory,
    is_iqm_available,
)
from .job_dossier import HardwareJobDossier, build_s1_feedback_job_dossier
from .noise_model import heron_r2_noise_model
from .provider_capability_discovery import (
    CapabilityDecisionStatus,
    ProviderCapabilityDecision,
    ProviderCapabilitySnapshot,
    ProviderMetadataProbe,
    assess_provider_capability_snapshot,
    probe_aggregator_provider_capability,
    snapshot_from_azure_target,
    snapshot_from_braket_device,
    snapshot_from_ionq_backend,
    snapshot_from_iqm_backend,
    snapshot_from_oqc_target,
    snapshot_from_qbraid_device,
    snapshot_from_qiskit_runtime_backend,
    snapshot_from_quantinuum_backend,
    snapshot_from_quera_bloqade,
    snapshot_from_rigetti_qcs,
    snapshot_from_strangeworks_backend,
)
from .provider_smoke import (
    AggregatorProviderOptionalDependencyRow,
    ProviderOptionalDependencyRow,
    aggregator_provider_optional_dependency_matrix,
    provider_optional_dependency_matrix,
)
from .qubit_mapper import (
    ExecutionRegion,
    QubitMappingResult,
    build_calibration_graph,
    detect_execution_regions,
    dynq_initial_layout,
    select_best_region,
)
from .runner import HardwareRunner, JobResult
from .trapped_ion import transpile_for_trapped_ion, trapped_ion_noise_model

__all__ = [
    "AsyncHardwareRunner",
    "AsyncJobHandle",
    "AnalogBackendCapabilities",
    "AnalogCouplingTerm",
    "AnalogDriveTerm",
    "AnalogFeedbackTerm",
    "AnalogKuramotoBackend",
    "AnalogKuramotoBackendProtocol",
    "AnalogKuramotoPlatform",
    "AnalogKuramotoProgram",
    "AnalogProviderTarget",
    "ProviderAnalogExecutionPlan",
    "ProviderAnalogPayload",
    "analog_kuramoto_factory",
    "compile_analog_kuramoto",
    "export_provider_payload",
    "prepare_provider_execution_plan",
    "ANALOG_NATIVE_SCHEMA",
    "AnalogNativePrimitiveComparison",
    "AnalogNativeReadinessConfig",
    "AnalogProviderReadinessRow",
    "analog_native_markdown",
    "analog_native_payload",
    "compare_native_to_digital_primitives",
    "provider_readiness_rows",
    "AggregatorProviderRoute",
    "ResolvedAggregatorProviderRoute",
    "aggregator_provider_routes_for",
    "built_in_aggregator_provider_routes",
    "resolve_aggregator_provider_route",
    "HybridCouplingAssignment",
    "HybridCouplingPartition",
    "HybridDigitalAnalogBackend",
    "HybridDigitalAnalogBackendProtocol",
    "HybridDigitalAnalogProgram",
    "HybridRoute",
    "FeedbackCommand",
    "FeedbackLoopConfig",
    "FeedbackObserver",
    "FeedbackResult",
    "FeedbackRunner",
    "FeedbackScheduler",
    "FeedbackStepRecord",
    "ProportionalMetricObserver",
    "RealtimeControllerScheduler",
    "FeedbackBudgetEstimate",
    "FeedbackCircuitSummary",
    "FeedbackPlatformCapability",
    "FeedbackSubmissionPackage",
    "PlatformReadiness",
    "CapabilityDecisionStatus",
    "ProviderCapabilityDecision",
    "ProviderCapabilitySnapshot",
    "ProviderMetadataProbe",
    "AggregatorProviderOptionalDependencyRow",
    "ProviderOptionalDependencyRow",
    "assess_provider_capability_snapshot",
    "assess_platform_readiness",
    "aggregator_provider_optional_dependency_matrix",
    "build_s1_feedback_submission_package",
    "default_s1_platforms",
    "probe_aggregator_provider_capability",
    "provider_optional_dependency_matrix",
    "snapshot_from_azure_target",
    "snapshot_from_braket_device",
    "snapshot_from_iqm_backend",
    "snapshot_from_ionq_backend",
    "snapshot_from_oqc_target",
    "snapshot_from_qiskit_runtime_backend",
    "snapshot_from_qbraid_device",
    "snapshot_from_quantinuum_backend",
    "snapshot_from_quera_bloqade",
    "snapshot_from_rigetti_qcs",
    "snapshot_from_strangeworks_backend",
    "summarise_feedback_circuit",
    "FeedbackDryRunPayload",
    "build_analog_native_review_payload",
    "build_ibm_runtime_dry_run",
    "build_openqasm3_gate_dry_run",
    "build_s1_feedback_dry_run_bundle",
    "AzureQuantumHALAdapter",
    "azure_openqasm3_to_workload",
    "BraketAwsHALAdapter",
    "BraketLocalHALAdapter",
    "braket_circuit_to_workload",
    "CirqLocalHALAdapter",
    "cirq_circuit_workload",
    "DWaveLeapHALAdapter",
    "dwave_bqm_workload",
    "IonQCloudHALAdapter",
    "ionq_qis_workload",
    "IQMHALAdapter",
    "iqm_qiskit_workload",
    "OQCHALAdapter",
    "oqc_openqasm3_workload",
    "PasqalPulserHALAdapter",
    "pulser_sequence_workload",
    "PennyLaneDeviceHALAdapter",
    "pennylane_gate_workload",
    "QbraidRuntimeHALAdapter",
    "StrangeworksComputeHALAdapter",
    "QuandelaPercevalHALAdapter",
    "quandela_perceval_workload",
    "QuEraBloqadeHALAdapter",
    "QuantinuumCloudHALAdapter",
    "RigettiQCSHALAdapter",
    "bloqade_ahs_workload",
    "qbraid_program_to_workload",
    "quantinuum_tket_workload",
    "rigetti_quil_workload",
    "strangeworks_program_to_workload",
    "BackendCapabilities",
    "BackendProfile",
    "HardwareAbstractionLayer",
    "LocalDeterministicSimulator",
    "QuantumBackend",
    "QuantumJobRef",
    "QuantumJobResult",
    "QuantumWorkload",
    "built_in_backend_profiles",
    "QiskitAerHALAdapter",
    "QiskitRuntimeHALAdapter",
    "qiskit_circuit_to_qasm3_workload",
    "qiskit_circuit_to_workload",
    "ApprovalGatedFeedbackHardwareScheduler",
    "HardwareApprovalRecord",
    "HardwareSubmissionRecord",
    "hash_package_manifest",
    "BackendCapabilitySnapshot",
    "FeedbackCapabilityDecision",
    "assess_feedback_backend_capability",
    "assess_feedback_backend_fleet",
    "required_s1_dynamic_features",
    "snapshot_from_generic_metadata",
    "snapshot_from_qiskit_backend",
    "HardwareJobDossier",
    "build_s1_feedback_job_dossier",
    "compile_hybrid_digital_analog",
    "hybrid_digital_analog_factory",
    "partition_kuramoto_couplings",
    "IQMBackendConfig",
    "IQMQuantumBackend",
    "IQMRunResult",
    "iqm_factory",
    "is_iqm_available",
    "BackendProtocol",
    "BackendRegistrationError",
    "BackendRegistry",
    "QuantumBackendDescriptor",
    "HardwareRunner",
    "describe_hal_backend_profile",
    "describe_backend",
    "discover_backends",
    "get_backend",
    "get_registry",
    "list_hal_backend_descriptors",
    "list_backends",
    "list_quantum_backends",
    "register_backend",
    "unregister_backend",
    "heron_r2_noise_model",
    "ALL_EXPERIMENTS",
    "ansatz_comparison_hw_experiment",
    "decoherence_scaling_experiment",
    "kuramoto_4osc_experiment",
    "kuramoto_4osc_trotter2_experiment",
    "kuramoto_4osc_zne_experiment",
    "kuramoto_8osc_experiment",
    "kuramoto_8osc_zne_experiment",
    "noise_baseline_experiment",
    "qaoa_mpc_4_experiment",
    "sync_threshold_experiment",
    "upde_16_dd_experiment",
    "upde_16_snapshot_experiment",
    "vqe_4q_experiment",
    "vqe_8q_experiment",
    "vqe_8q_hardware_experiment",
    "vqe_landscape_experiment",
    "zne_higher_order_experiment",
    "bell_test_4q_experiment",
    "correlator_4q_experiment",
    "qkd_qber_4q_experiment",
    "classical_kuramoto_reference",
    "classical_exact_diag",
    "classical_brute_mpc",
    "bloch_vectors_from_json",
    "classical_exact_evolution",
    "JobResult",
    "trapped_ion_noise_model",
    "transpile_for_trapped_ion",
    "ExecutionRegion",
    "QubitMappingResult",
    "build_calibration_graph",
    "detect_execution_regions",
    "dynq_initial_layout",
    "select_best_region",
]
