# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Quantum Control — Hardware Backends
"""Hardware backend layer: classical exact solvers, IBM Quantum runner,
noise models, trapped-ion transpilation, and experiment definitions.
"""

from .analog_kuramoto import (
    AnalogBackendCapabilities,
    AnalogCouplingTerm,
    AnalogDriveTerm,
    AnalogFeedbackTerm,
    AnalogKuramotoBackend,
    AnalogKuramotoBackendProtocol,
    AnalogKuramotoPlatform,
    AnalogKuramotoProgram,
    AnalogProviderTarget,
    ProviderAnalogExecutionPlan,
    ProviderAnalogPayload,
    analog_kuramoto_factory,
    compile_analog_kuramoto,
    export_provider_payload,
    prepare_provider_execution_plan,
)
from .async_runner import AsyncHardwareRunner, AsyncJobHandle
from .backends import (
    BackendProtocol,
    BackendRegistrationError,
    BackendRegistry,
    discover_backends,
    get_backend,
    get_registry,
    list_backends,
    register_backend,
    unregister_backend,
)
from .classical import (
    bloch_vectors_from_json,
    classical_brute_mpc,
    classical_exact_diag,
    classical_exact_evolution,
    classical_kuramoto_reference,
)
from .experiments import (
    ALL_EXPERIMENTS,
    ansatz_comparison_hw_experiment,
    bell_test_4q_experiment,
    correlator_4q_experiment,
    decoherence_scaling_experiment,
    kuramoto_4osc_experiment,
    kuramoto_4osc_trotter2_experiment,
    kuramoto_4osc_zne_experiment,
    kuramoto_8osc_experiment,
    kuramoto_8osc_zne_experiment,
    noise_baseline_experiment,
    qaoa_mpc_4_experiment,
    qkd_qber_4q_experiment,
    sync_threshold_experiment,
    upde_16_dd_experiment,
    upde_16_snapshot_experiment,
    vqe_4q_experiment,
    vqe_8q_experiment,
    vqe_8q_hardware_experiment,
    vqe_landscape_experiment,
    zne_higher_order_experiment,
)
from .feedback_loop import (
    FeedbackCommand,
    FeedbackLoopConfig,
    FeedbackObserver,
    FeedbackResult,
    FeedbackRunner,
    FeedbackScheduler,
    FeedbackStepRecord,
    ProportionalMetricObserver,
    RealtimeControllerScheduler,
)
from .feedback_submission import (
    FeedbackBudgetEstimate,
    FeedbackCircuitSummary,
    FeedbackPlatformCapability,
    FeedbackSubmissionPackage,
    PlatformReadiness,
    assess_platform_readiness,
    build_s1_feedback_submission_package,
    default_s1_platforms,
    summarise_feedback_circuit,
)
from .hybrid_digital_analog import (
    HybridCouplingAssignment,
    HybridCouplingPartition,
    HybridDigitalAnalogBackend,
    HybridDigitalAnalogBackendProtocol,
    HybridDigitalAnalogProgram,
    HybridRoute,
    compile_hybrid_digital_analog,
    hybrid_digital_analog_factory,
    partition_kuramoto_couplings,
)
from .job_dossier import HardwareJobDossier, build_s1_feedback_job_dossier
from .noise_model import heron_r2_noise_model
from .qubit_mapper import (
    ExecutionRegion,
    QubitMappingResult,
    build_calibration_graph,
    detect_execution_regions,
    dynq_initial_layout,
    select_best_region,
)
from .runner import HardwareRunner, JobResult
from .trapped_ion import transpile_for_trapped_ion, trapped_ion_noise_model

__all__ = [
    "AsyncHardwareRunner",
    "AsyncJobHandle",
    "AnalogBackendCapabilities",
    "AnalogCouplingTerm",
    "AnalogDriveTerm",
    "AnalogFeedbackTerm",
    "AnalogKuramotoBackend",
    "AnalogKuramotoBackendProtocol",
    "AnalogKuramotoPlatform",
    "AnalogKuramotoProgram",
    "AnalogProviderTarget",
    "ProviderAnalogExecutionPlan",
    "ProviderAnalogPayload",
    "analog_kuramoto_factory",
    "compile_analog_kuramoto",
    "export_provider_payload",
    "prepare_provider_execution_plan",
    "HybridCouplingAssignment",
    "HybridCouplingPartition",
    "HybridDigitalAnalogBackend",
    "HybridDigitalAnalogBackendProtocol",
    "HybridDigitalAnalogProgram",
    "HybridRoute",
    "FeedbackCommand",
    "FeedbackLoopConfig",
    "FeedbackObserver",
    "FeedbackResult",
    "FeedbackRunner",
    "FeedbackScheduler",
    "FeedbackStepRecord",
    "ProportionalMetricObserver",
    "RealtimeControllerScheduler",
    "FeedbackBudgetEstimate",
    "FeedbackCircuitSummary",
    "FeedbackPlatformCapability",
    "FeedbackSubmissionPackage",
    "PlatformReadiness",
    "assess_platform_readiness",
    "build_s1_feedback_submission_package",
    "default_s1_platforms",
    "summarise_feedback_circuit",
    "HardwareJobDossier",
    "build_s1_feedback_job_dossier",
    "compile_hybrid_digital_analog",
    "hybrid_digital_analog_factory",
    "partition_kuramoto_couplings",
    "BackendProtocol",
    "BackendRegistrationError",
    "BackendRegistry",
    "HardwareRunner",
    "discover_backends",
    "get_backend",
    "get_registry",
    "list_backends",
    "register_backend",
    "unregister_backend",
    "heron_r2_noise_model",
    "ALL_EXPERIMENTS",
    "ansatz_comparison_hw_experiment",
    "decoherence_scaling_experiment",
    "kuramoto_4osc_experiment",
    "kuramoto_4osc_trotter2_experiment",
    "kuramoto_4osc_zne_experiment",
    "kuramoto_8osc_experiment",
    "kuramoto_8osc_zne_experiment",
    "noise_baseline_experiment",
    "qaoa_mpc_4_experiment",
    "sync_threshold_experiment",
    "upde_16_dd_experiment",
    "upde_16_snapshot_experiment",
    "vqe_4q_experiment",
    "vqe_8q_experiment",
    "vqe_8q_hardware_experiment",
    "vqe_landscape_experiment",
    "zne_higher_order_experiment",
    "bell_test_4q_experiment",
    "correlator_4q_experiment",
    "qkd_qber_4q_experiment",
    "classical_kuramoto_reference",
    "classical_exact_diag",
    "classical_brute_mpc",
    "bloch_vectors_from_json",
    "classical_exact_evolution",
    "JobResult",
    "trapped_ion_noise_model",
    "transpile_for_trapped_ion",
    "ExecutionRegion",
    "QubitMappingResult",
    "build_calibration_graph",
    "detect_execution_regions",
    "dynq_initial_layout",
    "select_best_region",
]
