# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Quantum Control — versioned contract custody corpus
"""Build the accept/reject corpus for versioned record custody.

Two kinds of case live here and they must never be quoted as one another.

An **executed** case names a production reader that exists today and is invoked
with real inputs; its expected outcome is the outcome that reader produces. A
**design vector** is a concrete proposed input for the semantic companion record
that is specified but not built; its expected semantics are stated and nothing
is executed. Labelling a design vector as executed would be the same overclaim
as citing an import as conformance.

Fixtures are generated by calling the producers rather than hand-written,
because a digest recorded without the bytes it describes cannot be checked
afterwards. The corpus is written once, checked in, and re-derived by its owner
tests so that producer drift surfaces as a failure instead of a surprise.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Final

from scpn_quantum_control import stable_core_product as scp
from tools import contract_custody_design_vectors as vectors

CORPUS_SCHEMA: Final[str] = "contract_custody_corpus.v1"
"""Schema of the manifest this module writes."""

SUPERSEDED_CORPUS_SCHEMAS: Final = frozenset({"core_g02_contract_corpus.v1"})
"""Manifest schemas that must be refused rather than read.

The first corpus schema encoded an internal planning identifier, which the
descriptive-naming directive forbids on any public or serialised surface. A
reader that silently accepted the old name would keep that identifier alive in
stored artefacts, so it is refused by name.
"""

COMPANION_MODULE: Final[str] = "scpn_quantum_control.semantic_record"
"""Planned owner of the semantic companion; absent from source today."""

EXECUTED: Final[str] = "executed"
"""A production reader was invoked and its outcome is the expected outcome."""

DESIGN_VECTOR: Final[str] = "design_vector"
"""A concrete proposed input, specified and deliberately not executed."""


@dataclass(frozen=True)
class CustodyCase:
    """One accept/reject case with its reader and its evidence class.

    Parameters
    ----------
    case_id
        Stable identifier, used as the fixture filename stem.
    family
        Which mapped contract family the case exercises.
    producer
        Module-qualified identity of the producing type or callable.
    reader
        Module-qualified reader whose behaviour the case pins. For a design
        vector this is the proposed reader, which does not exist yet.
    expectation
        ``accept`` or ``reject``.
    status
        :data:`EXECUTED` or :data:`DESIGN_VECTOR`.
    rationale
        Why this case exists, in one sentence.
    payload
        The fixture body, or ``None`` when the case pins behaviour rather than
        bytes.

    """

    case_id: str
    family: str
    producer: str
    reader: str
    expectation: str
    status: str
    rationale: str
    payload: Mapping[str, Any] | None


def raw_experiment_record() -> dict[str, Any]:
    """Return the serialised demonstration experiment envelope.

    Returns
    -------
    dict
        The v2 envelope exactly as the production serialiser emits it.

    """
    return scp.serialise_experiment(scp.build_demo_experiment())


def _with_companion_key() -> dict[str, Any]:
    """Return a v2 envelope with a companion key wrongly added inside it.

    Returns
    -------
    dict
        An envelope the v2 reader must refuse as key drift.

    """
    envelope = raw_experiment_record()
    envelope["scientific_semantics"] = {"schema": vectors.COMPANION_SCHEMA}
    return envelope


def _with_unknown_model_major() -> dict[str, Any]:
    """Return a v2 envelope carrying an unreadable model schema version.

    Returns
    -------
    dict
        An envelope whose model major the reader cannot know.

    """
    envelope = raw_experiment_record()
    envelope["schema_version"] = "stable_core.experiment_model.v3"
    return envelope


def _with_mismatched_kind() -> dict[str, Any]:
    """Return an experiment envelope relabelled as a problem.

    Returns
    -------
    dict
        An envelope whose kind contradicts its body.

    """
    envelope = raw_experiment_record()
    envelope["kind"] = "problem"
    return envelope


def _executed_cases() -> tuple[CustodyCase, ...]:
    """Return the cases a production reader answers today.

    Returns
    -------
    tuple
        Cases whose expected outcome was obtained by invoking real code.

    """
    reader = "scpn_quantum_control.stable_core_product.deserialise_experiment"
    serialiser = "scpn_quantum_control.stable_core_product.serialise_experiment"
    return (
        CustodyCase(
            case_id="raw_round_trip_preserves_digest",
            family="Result/evidence",
            producer=serialiser,
            reader="scpn_quantum_control.stable_core_product.round_trip_experiment",
            expectation="accept",
            status=EXECUTED,
            rationale=(
                "A legacy consumer round-trips unchanged raw v2 and recovers the "
                "original digest, with no companion anywhere in the path."
            ),
            payload=raw_experiment_record(),
        ),
        CustodyCase(
            case_id="raw_digest_excludes_surrounding_document",
            family="Result/evidence",
            producer=serialiser,
            reader="scpn_quantum_control.stable_core_product.digest_stable_core_payload",
            expectation="accept",
            status=EXECUTED,
            rationale=(
                "Embedding the raw record in a larger document must leave the raw "
                "digest untouched while the surrounding document digests differently."
            ),
            payload=raw_experiment_record(),
        ),
        CustodyCase(
            case_id="raw_readable_without_companion",
            family="Result/evidence",
            producer=serialiser,
            reader=reader,
            expectation="accept",
            status=EXECUTED,
            rationale=(
                "Absent semantic qualification never makes a previously readable "
                "raw record unreadable; unavailable is not failure."
            ),
            payload=raw_experiment_record(),
        ),
        CustodyCase(
            case_id="companion_key_inside_raw_envelope_refused",
            family="Result/evidence",
            producer=serialiser,
            reader=reader,
            expectation="reject",
            status=EXECUTED,
            rationale=(
                "The companion is held alongside, never added as a v2 key, and the "
                "existing reader already refuses this as envelope key drift."
            ),
            payload=_with_companion_key(),
        ),
        CustodyCase(
            case_id="unknown_raw_model_major_refused",
            family="Result/evidence",
            producer=serialiser,
            reader=reader,
            expectation="reject",
            status=EXECUTED,
            rationale=(
                "An unknown stable-core model major refuses rather than being read "
                "optimistically. This is the raw major, not the companion major."
            ),
            payload=_with_unknown_model_major(),
        ),
        CustodyCase(
            case_id="mismatched_raw_record_kind_refused",
            family="Result/evidence",
            producer=serialiser,
            reader=reader,
            expectation="reject",
            status=EXECUTED,
            rationale="A wrong kind binding refuses before qualification or persistence.",
            payload=_with_mismatched_kind(),
        ),
        CustodyCase(
            case_id="captured_record_survives_later_mutation",
            family="Result/evidence",
            producer=serialiser,
            reader="scpn_quantum_control.stable_core_product.canonical_json_bytes",
            expectation="accept",
            status=EXECUTED,
            rationale=(
                "Mutating the source after capture leaves the captured bytes and "
                "their digest unchanged. This is raw byte custody; companion "
                "snapshot ownership is a separate design vector."
            ),
            payload=raw_experiment_record(),
        ),
        CustodyCase(
            case_id="planner_preserves_null_request_beside_default",
            family="Execution plan",
            producer=(
                "scpn_quantum_control.phase.gradient_backend.explain_quantum_gradient_method"
            ),
            reader=("scpn_quantum_control.phase.gradient_backend.explain_quantum_gradient_method"),
            expectation="accept",
            status=EXECUTED,
            rationale=(
                "The real planner keeps a null caller request distinguishable from "
                "the backend default it supplied, and records why."
            ),
            payload=vectors.planning_policy_source(),
        ),
        CustodyCase(
            case_id="fisher_observed_and_expected_routes_stay_distinct",
            family="Fidelity",
            producer=(
                "scpn_quantum_control.phase.qnode_circuit_differentiation."
                "phase_qnode_computational_basis_fisher_information"
            ),
            reader=(
                "scpn_quantum_control.phase.qnode_circuit_differentiation."
                "phase_qnode_computational_basis_fisher_information"
            ),
            expectation="accept",
            status=EXECUTED,
            rationale=(
                "The real producer labels observed replay and expected-count "
                "analysis differently and retains the raw counts only for the "
                "observed route, so equal shot counts cannot conflate them."
            ),
            payload=None,
        ),
        CustodyCase(
            case_id="non_count_route_carries_no_measurement_mapping",
            family="Backend observation",
            producer=(
                "scpn_quantum_control.phase.qnode_circuit_differentiation."
                "phase_qnode_computational_basis_fisher_information"
            ),
            reader=(
                "scpn_quantum_control.phase.qnode_circuit_contracts."
                "PhaseQNodeClassicalFisherResult"
            ),
            expectation="accept",
            status=EXECUTED,
            rationale=(
                "Without observed counts the real producer leaves the measurement "
                "mapping absent rather than padding a count vector into existence."
            ),
            payload=None,
        ),
        CustodyCase(
            case_id="same_named_problem_types_remain_separable",
            family="Problem identity",
            producer=vectors.CORE_PROBLEM_IDENTITY,
            reader=vectors.BENCHMARK_PROBLEM_IDENTITY,
            expectation="accept",
            status=EXECUTED,
            rationale=(
                "Both types exist with disjoint fields under one bare name. This is "
                "the source fact the producer-identity design vector rests on; no "
                "production reader binds producer identity yet."
            ),
            payload=None,
        ),
    )


def _design_vector_cases() -> tuple[CustodyCase, ...]:
    """Return the proposed-companion cases, none of them executed.

    Returns
    -------
    tuple
        Cases carrying concrete bytes and stated expected semantics.

    """
    digest = scp.digest_stable_core_payload(raw_experiment_record())
    proposed = f"{COMPANION_MODULE}.validate_semantic_binding"
    rows: tuple[tuple[str, str, str, str, Mapping[str, Any]], ...] = (
        (
            "companion_positive_base",
            "Semantic support",
            "accept",
            "The positive base, so a matrix of refusals cannot be satisfied by "
            "refusing everything.",
            vectors.valid_companion(digest),
        ),
        (
            "companion_unknown_major_refused",
            "Semantic support",
            "reject",
            "An unreadable companion major must refuse; this is the companion "
            "version, distinct from the raw model version.",
            vectors.unknown_companion_major(digest),
        ),
        (
            "companion_bound_to_wrong_raw_digest_refused",
            "Result/evidence",
            "reject",
            "A companion pointing at bytes it does not describe must refuse "
            "before qualification or persistence.",
            vectors.wrong_raw_digest(digest),
        ),
        (
            "companion_bound_to_wrong_record_kind_refused",
            "Result/evidence",
            "reject",
            "A kind that contradicts the referenced record must refuse.",
            vectors.wrong_record_kind(digest),
        ),
        (
            "frequency_unit_changed_without_conversion_refused",
            "Semantic support",
            "reject",
            "Hz against rad/s differ by two pi; no existing contract carries a "
            "unit for this family, so nothing today catches a silent re-uniting.",
            vectors.hertz_against_radians(digest),
        ),
        (
            "declared_shape_and_dtype_cannot_hold_data_refused",
            "Derivative request",
            "reject",
            "A coupling matrix declared as a short integer vector must refuse "
            "rather than be coerced.",
            vectors.mismatched_shape_and_dtype(digest),
        ),
        (
            "parameter_order_and_tangent_change_refused",
            "Derivative request",
            "reject",
            "Reordering parameters or swapping the tangent convention silently "
            "relabels a gradient component.",
            vectors.reordered_parameters_and_tangent(digest),
        ),
        (
            "effective_setting_contradicts_request_refused",
            "Execution plan",
            "reject",
            "A hundred requested against two hundred effective, with no recorded "
            "accepted transformation, is an unexplained substitution.",
            vectors.unauthorised_shot_change(digest),
        ),
        (
            "null_request_with_recorded_default_accepted",
            "Execution plan",
            "accept",
            "A null request beside a defaulted effective value and its origin is "
            "the provenance shape that must survive the companion.",
            vectors.null_request_with_recorded_default(digest),
        ),
        (
            "non_count_modality_declines_bit_mapping",
            "Backend observation",
            "accept",
            "A non-count modality states that bit mapping is not applicable "
            "rather than padding counts.",
            vectors.not_applicable_measurement_mapping(digest),
        ),
        (
            "cross_bound_producer_identity_refused",
            "Problem identity",
            "reject",
            "Binding a core record to the same-named benchmark type must refuse; "
            "identity is module-qualified, never a bare class name.",
            vectors.cross_bound_producer_identity(digest),
        ),
    )
    return tuple(
        CustodyCase(
            case_id=case_id,
            family=family,
            producer=vectors.COMPANION_SCHEMA,
            reader=proposed,
            expectation=expectation,
            status=DESIGN_VECTOR,
            rationale=rationale,
            payload=payload,
        )
        for case_id, family, expectation, rationale, payload in rows
    )


def build_cases() -> tuple[CustodyCase, ...]:
    """Return every case, executed ones first.

    Returns
    -------
    tuple
        The whole corpus.

    """
    return _executed_cases() + _design_vector_cases()


def case_manifest_entry(case: CustodyCase) -> dict[str, Any]:
    """Return the manifest row for one case.

    Parameters
    ----------
    case
        The case to describe.

    Returns
    -------
    dict
        Manifest fields, including the fixture digest when the case has bytes.

    """
    entry: dict[str, Any] = {
        "case_id": case.case_id,
        "family": case.family,
        "producer": case.producer,
        "reader": case.reader,
        "expectation": case.expectation,
        "status": case.status,
        "rationale": case.rationale,
    }
    if case.payload is None:
        entry["fixture"] = None
        entry["fixture_sha256"] = None
    else:
        entry["fixture"] = f"{case.case_id}.json"
        entry["fixture_sha256"] = scp.digest_stable_core_payload(case.payload)
    return entry


def build_manifest(cases: tuple[CustodyCase, ...]) -> dict[str, Any]:
    """Return the full corpus manifest.

    Parameters
    ----------
    cases
        Cases to describe.

    Returns
    -------
    dict
        The manifest, cases in the given order.

    """
    return {
        "schema": CORPUS_SCHEMA,
        "companion_schema": vectors.COMPANION_SCHEMA,
        "companion_module": COMPANION_MODULE,
        "model_schema_version": scp.STABLE_CORE_MODEL_SCHEMA_VERSION,
        "design_vectors_are_unexecuted": True,
        "cases": [case_manifest_entry(case) for case in cases],
    }


def validate_manifest_schema(manifest: Mapping[str, Any]) -> str:
    """Return the manifest schema, refusing a superseded coded name.

    Parameters
    ----------
    manifest
        A parsed corpus manifest.

    Returns
    -------
    str
        The accepted schema identifier.

    Raises
    ------
    ValueError
        If the schema is a superseded internally-coded name, or is unknown.

    """
    schema = manifest.get("schema")
    if schema in SUPERSEDED_CORPUS_SCHEMAS:
        raise ValueError(
            f"corpus schema {schema!r} encodes an internal planning identifier and is "
            f"superseded by {CORPUS_SCHEMA!r}; regenerate the corpus"
        )
    if schema != CORPUS_SCHEMA:
        raise ValueError(f"unknown corpus schema {schema!r}; expected {CORPUS_SCHEMA!r}")
    return CORPUS_SCHEMA


def write_corpus(destination: Path) -> dict[str, Any]:
    """Write fixtures and manifest under ``destination``.

    Parameters
    ----------
    destination
        Directory to populate; created if absent.

    Returns
    -------
    dict
        The manifest that was written.

    """
    destination.mkdir(parents=True, exist_ok=True)
    cases = build_cases()
    for case in cases:
        if case.payload is None:
            continue
        body = scp.canonical_json_bytes(case.payload)
        (destination / f"{case.case_id}.json").write_bytes(body)
    manifest = build_manifest(cases)
    (destination / "manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return manifest


def main(argv: list[str] | None = None) -> int:
    """Write the corpus to the requested directory.

    Parameters
    ----------
    argv
        Command-line arguments; defaults to :data:`sys.argv`.

    Returns
    -------
    int
        Process exit status, zero on success.

    """
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("destination", type=Path)
    arguments = parser.parse_args(argv)
    manifest = write_corpus(arguments.destination)
    sys.stdout.write(f"{len(manifest['cases'])} cases written\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
