# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Quantum Control — versioned contract custody corpus
"""Build the accept/reject corpus for versioned record custody.

Three kinds of case live here and they must never be quoted as one another.

An **executed** case names a production reader that exists today and is invoked
with real inputs; its expected outcome is the outcome that reader produces. A
**design vector** is a concrete proposed input for the semantic companion record
that is specified but not built; its expected semantics are stated and nothing
is executed. A **source_fact** records inspected type metadata without claiming
a reader invocation. Neither source facts nor design vectors are executed
binding conformance.

Design payloads are either proposed companion records or lifecycle test
scenarios with separate inputs and expected_outcome. A scenario wrapper is
not passed to the proposed reader as a companion wire record. Mutation steps
describe later caller actions; checking their consistency does not execute
the as-yet-unimplemented capture lifecycle.

Fixtures are generated by calling the producers rather than hand-written,
because a digest recorded without the bytes it describes cannot be checked
afterwards. The corpus is written once, checked in, and re-derived by its owner
tests so that producer drift surfaces as a failure instead of a surprise.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Final, Literal

from scpn_quantum_control import stable_core_product as scp
from scpn_quantum_control.phase.qnode_circuit_contracts import PauliTerm, PhaseQNodeCircuit
from scpn_quantum_control.phase.qnode_circuit_differentiation import (
    phase_qnode_computational_basis_fisher_information,
)
from tools import contract_custody_design_vectors as vectors
from tools.contract_custody_derivative_source import derivative_evidence_source
from tools.contract_custody_hal_source import hal_evidence_source, non_count_qualification_proposal
from tools.contract_custody_problem_source import benchmark_problem_source
from tools.contract_custody_registry_source import registry_evidence_source
from tools.contract_custody_result_source import stable_result_evidence_source

CORPUS_SCHEMA: Final[str] = "contract_custody_corpus.v1"
"""Schema of the manifest this module writes."""

SUPERSEDED_CORPUS_SCHEMAS: Final = frozenset({"core_g02_contract_corpus.v1"})
"""Manifest schemas that must be refused rather than read.

The first corpus schema encoded an internal planning identifier, which the
descriptive-naming directive forbids on any public or serialised surface. A
reader that silently accepted the old name would keep that identifier alive in
stored artefacts, so it is refused by name.
"""

COMPANION_MODULE: Final[str] = "scpn_quantum_control.semantic_record"
"""Planned owner of the semantic companion; absent from source today."""

EXECUTED: Final[str] = "executed"
"""A production reader was invoked and its outcome is the expected outcome."""

DESIGN_VECTOR: Final[str] = "design_vector"
"""A concrete proposed input, specified and deliberately not executed."""

SOURCE_FACT: Final[str] = "source_fact"
"""Inspected source metadata, not an executed reader or qualified binding."""


@dataclass(frozen=True)
class CustodyCase:
    """One accept/reject case with its reader and its evidence class.

    Parameters
    ----------
    case_id
        Stable identifier, used as the fixture filename stem.
    family
        Which mapped contract family the case exercises.
    producer
        Module-qualified identity of the producing type or callable.
    reader
        Module-qualified reader whose behaviour the case pins. For a design
        vector this is the proposed reader, which does not exist yet. Source
        facts have no reader and record None.
    expectation
        ``accept`` or ``reject``.
    status
        :data:`EXECUTED`, :data:`DESIGN_VECTOR` or :data:`SOURCE_FACT`.
    rationale
        Why this case exists, in one sentence.
    payload
        The fixture body, or ``None`` when the case pins behaviour rather than
        bytes.

    """

    case_id: str
    family: str
    producer: str
    reader: str | None
    expectation: str
    status: str
    rationale: str
    payload: Mapping[str, Any] | None


def raw_experiment_record() -> dict[str, Any]:
    """Return the serialised demonstration experiment envelope.

    Returns
    -------
    dict
        The v2 envelope exactly as the production serialiser emits it.

    """
    return scp.serialise_experiment(scp.build_demo_experiment())


def _with_companion_key() -> dict[str, Any]:
    """Return a v2 envelope with a companion key wrongly added inside it.

    Returns
    -------
    dict
        An envelope the v2 reader must refuse as key drift.

    """
    envelope = raw_experiment_record()
    envelope["scientific_semantics"] = {"schema": vectors.COMPANION_SCHEMA}
    return envelope


def _with_unknown_model_major() -> dict[str, Any]:
    """Return a v2 envelope carrying an unreadable model schema version.

    Returns
    -------
    dict
        An envelope whose model major the reader cannot know.

    """
    envelope = raw_experiment_record()
    envelope["schema_version"] = "stable_core.experiment_model.v3"
    return envelope


def _with_mismatched_kind() -> dict[str, Any]:
    """Return an experiment envelope relabelled as a problem.

    Returns
    -------
    dict
        An envelope whose kind contradicts its body.

    """
    envelope = raw_experiment_record()
    envelope["kind"] = "problem"
    return envelope


def fisher_evidence_source() -> dict[str, Any]:
    """Capture full public Fisher output for expected and supplied-count routes.

    Returns
    -------
    dict
        Explicit circuit and callable inputs, public result records and their
        original digests. Counts are a deterministic local test input, not
        acquired hardware measurements. No companion binding is executed.

    """
    observable = PauliTerm(1.0, ((0, "z"),))
    operations = (("ry", (0,), 0),)
    circuit = PhaseQNodeCircuit(n_qubits=1, operations=operations, observable=observable)
    routes: dict[str, Any] = {}
    for route, counts, wires in (
        ("expected", None, None),
        ("observed", {"0": 300, "1": 212}, [0]),
    ):
        inputs = {
            "parameters": [0.7],
            "min_probability": 1e-15,
            "shot_count": 512,
            "observed_counts": counts,
            "observed_count_wires": wires,
            "confidence_level": 0.95,
            "confidence_z": 1.959963984540054,
        }
        result = phase_qnode_computational_basis_fisher_information(
            circuit,
            [0.7],
            min_probability=1e-15,
            shot_count=512,
            observed_counts=counts,
            observed_count_wires=wires,
            confidence_level=0.95,
            confidence_z=1.959963984540054,
        ).to_dict()
        routes[route] = {
            "inputs": inputs,
            "result": result,
            "result_sha256": scp.digest_stable_core_payload(result),
        }
    return {
        "producer": (
            "scpn_quantum_control.phase.qnode_circuit_differentiation."
            "phase_qnode_computational_basis_fisher_information"
        ),
        "circuit": {
            "n_qubits": circuit.n_qubits,
            "operations": [
                [name, list(qubits), parameter] for name, qubits, parameter in operations
            ],
            "observable": observable.to_dict(),
        },
        "routes": routes,
        "claim_boundary": (
            "local reference and uncertainty calculation using deterministic test inputs; "
            "supplied counts are not acquired hardware evidence; no semantic companion binding"
        ),
    }


def _executed_cases() -> tuple[CustodyCase, ...]:
    """Return the cases a production reader answers today.

    Returns
    -------
    tuple
        Cases whose expected outcome was obtained by invoking real code.

    """
    reader = "scpn_quantum_control.stable_core_product.deserialise_experiment"
    serialiser = "scpn_quantum_control.stable_core_product.serialise_experiment"
    return (
        CustodyCase(
            case_id="raw_round_trip_preserves_digest",
            family="Result/evidence",
            producer=serialiser,
            reader="scpn_quantum_control.stable_core_product.round_trip_experiment",
            expectation="accept",
            status=EXECUTED,
            rationale=(
                "A legacy consumer round-trips unchanged raw v2 and recovers the "
                "original digest, with no companion anywhere in the path."
            ),
            payload=raw_experiment_record(),
        ),
        CustodyCase(
            case_id="raw_digest_excludes_surrounding_document",
            family="Result/evidence",
            producer=serialiser,
            reader="scpn_quantum_control.stable_core_product.digest_stable_core_payload",
            expectation="accept",
            status=EXECUTED,
            rationale=(
                "Embedding the raw record in a larger document must leave the raw "
                "digest untouched while the surrounding document digests differently."
            ),
            payload=raw_experiment_record(),
        ),
        CustodyCase(
            case_id="raw_readable_without_companion",
            family="Result/evidence",
            producer=serialiser,
            reader=reader,
            expectation="accept",
            status=EXECUTED,
            rationale=(
                "Absent semantic qualification never makes a previously readable "
                "raw record unreadable; unavailable is not failure."
            ),
            payload=raw_experiment_record(),
        ),
        CustodyCase(
            case_id="companion_key_inside_raw_envelope_refused",
            family="Result/evidence",
            producer=serialiser,
            reader=reader,
            expectation="reject",
            status=EXECUTED,
            rationale=(
                "The companion is held alongside, never added as a v2 key, and the "
                "existing reader already refuses this as envelope key drift."
            ),
            payload=_with_companion_key(),
        ),
        CustodyCase(
            case_id="unknown_raw_model_major_refused",
            family="Result/evidence",
            producer=serialiser,
            reader=reader,
            expectation="reject",
            status=EXECUTED,
            rationale=(
                "An unknown stable-core model major refuses rather than being read "
                "optimistically. This is the raw major, not the companion major."
            ),
            payload=_with_unknown_model_major(),
        ),
        CustodyCase(
            case_id="mismatched_raw_record_kind_refused",
            family="Result/evidence",
            producer=serialiser,
            reader=reader,
            expectation="reject",
            status=EXECUTED,
            rationale="A wrong kind binding refuses before qualification or persistence.",
            payload=_with_mismatched_kind(),
        ),
        CustodyCase(
            case_id="captured_record_survives_later_mutation",
            family="Result/evidence",
            producer=serialiser,
            reader="scpn_quantum_control.stable_core_product.canonical_json_bytes",
            expectation="accept",
            status=EXECUTED,
            rationale=(
                "Mutating the source after capture leaves the captured bytes and "
                "their digest unchanged. This is raw byte custody only; "
                "companion snapshot ownership is not covered by this case."
            ),
            payload=raw_experiment_record(),
        ),
        CustodyCase(
            case_id="planner_preserves_null_request_beside_default",
            family="Execution plan",
            producer=(
                "scpn_quantum_control.phase.gradient_backend.explain_quantum_gradient_method"
            ),
            reader=("scpn_quantum_control.phase.gradient_backend.explain_quantum_gradient_method"),
            expectation="accept",
            status=EXECUTED,
            rationale=(
                "The real planner keeps a null caller request distinguishable from "
                "the backend default it supplied, and records why."
            ),
            payload=vectors.planning_policy_source(),
        ),
        CustodyCase(
            case_id="fisher_observed_and_expected_routes_stay_distinct",
            family="Fidelity",
            producer=(
                "scpn_quantum_control.phase.qnode_circuit_differentiation."
                "phase_qnode_computational_basis_fisher_information"
            ),
            reader=(
                "scpn_quantum_control.phase.qnode_circuit_differentiation."
                "phase_qnode_computational_basis_fisher_information"
            ),
            expectation="accept",
            status=EXECUTED,
            rationale=(
                "The real producer labels observed replay and expected-count "
                "analysis differently and retains the raw counts only for the "
                "observed route, so equal shot counts cannot conflate them."
            ),
            payload=fisher_evidence_source(),
        ),
        CustodyCase(
            case_id="non_count_route_carries_no_measurement_mapping",
            family="Fidelity",
            producer=(
                "scpn_quantum_control.phase.qnode_circuit_differentiation."
                "phase_qnode_computational_basis_fisher_information"
            ),
            reader=(
                "scpn_quantum_control.phase.qnode_circuit_differentiation."
                "phase_qnode_computational_basis_fisher_information"
            ),
            expectation="accept",
            status=EXECUTED,
            rationale=(
                "Without observed counts the real producer leaves the measurement "
                "mapping absent rather than padding a count vector into existence."
            ),
            payload=None,
        ),
    )


def _source_fact_cases() -> tuple[CustodyCase, ...]:
    """Return inspected type facts without inventing a reader invocation.

    Returns
    -------
    tuple
        Source metadata observations, not executed binding conformance.

    """
    return (
        CustodyCase(
            case_id="same_named_problem_types_remain_separable",
            family="Problem identity",
            producer=vectors.CORE_PROBLEM_IDENTITY,
            reader=None,
            expectation="accept",
            status=SOURCE_FACT,
            rationale=(
                "Both types exist with disjoint fields under one bare name. This is "
                "the source fact the producer-identity design vector rests on; no "
                "production reader binds producer identity yet."
            ),
            payload=None,
        ),
    )


def _design_vector_cases() -> tuple[CustodyCase, ...]:
    """Return the proposed-companion cases, none of them executed.

    Returns
    -------
    tuple
        Cases carrying concrete bytes and stated expected semantics.

    """
    digest = scp.digest_stable_core_payload(raw_experiment_record())
    proposed = f"{COMPANION_MODULE}.validate_semantic_binding"
    rows: tuple[tuple[str, str, str, str, Mapping[str, Any]], ...] = (
        (
            "companion_positive_base",
            "Semantic support",
            "accept",
            "The positive base, so a matrix of refusals cannot be satisfied by "
            "refusing everything.",
            vectors.valid_companion(digest),
        ),
        (
            "companion_unknown_major_refused",
            "Semantic support",
            "reject",
            "An unreadable companion major must refuse; this is the companion "
            "version, distinct from the raw model version.",
            vectors.unknown_companion_major(digest),
        ),
        (
            "companion_bound_to_wrong_raw_digest_refused",
            "Result/evidence",
            "reject",
            "A companion pointing at bytes it does not describe must refuse "
            "before qualification or persistence.",
            vectors.wrong_raw_digest(digest),
        ),
        (
            "companion_bound_to_wrong_record_kind_refused",
            "Result/evidence",
            "reject",
            "A kind that contradicts the referenced record must refuse.",
            vectors.wrong_record_kind(digest),
        ),
        (
            "frequency_unit_changed_without_conversion_refused",
            "Semantic support",
            "reject",
            "Hz against rad/s differ by two pi; no existing contract carries a "
            "unit for this family, so nothing today catches a silent re-uniting.",
            vectors.hertz_against_radians(digest),
        ),
        (
            "declared_shape_and_dtype_cannot_hold_data_refused",
            "Derivative request",
            "reject",
            "A coupling matrix declared as a short integer vector must refuse "
            "rather than be coerced.",
            vectors.mismatched_shape_and_dtype(digest),
        ),
        (
            "parameter_order_and_tangent_change_refused",
            "Derivative request",
            "reject",
            "Reordering parameters or swapping the tangent convention silently "
            "relabels a gradient component.",
            vectors.reordered_parameters_and_tangent(digest),
        ),
        (
            "effective_setting_contradicts_request_refused",
            "Execution plan",
            "reject",
            "A hundred requested against two hundred effective, with no recorded "
            "accepted transformation, is an unexplained substitution.",
            vectors.unauthorised_shot_change(digest),
        ),
        (
            "null_request_with_recorded_default_accepted",
            "Execution plan",
            "accept",
            "A null request beside a defaulted effective value and its origin is "
            "the provenance shape that must survive the companion.",
            vectors.null_request_with_recorded_default(digest),
        ),
        (
            "non_count_modality_declines_bit_mapping",
            "Backend observation",
            "accept",
            "A non-count modality states that bit mapping is not applicable "
            "rather than padding counts.",
            vectors.not_applicable_measurement_mapping(digest),
        ),
        (
            "cross_bound_producer_identity_refused",
            "Problem identity",
            "reject",
            "Binding a core record to the same-named benchmark type must refuse; "
            "identity is module-qualified, never a bare class name.",
            vectors.cross_bound_producer_identity(digest),
        ),
    )
    isolated = vectors.isolated_companions(digest)
    isolation_metadata = (
        (
            "companion_bound_to_wrong_raw_schema_refused",
            "Result/evidence",
            "The referenced raw schema alone disagrees; digest and kind stay unchanged.",
        ),
        (
            "coupling_shape_mismatch_refused",
            "Derivative request",
            "Only matrix shape changes; a correct dtype cannot hide shape validation.",
        ),
        (
            "coupling_dtype_mismatch_refused",
            "Derivative request",
            "Only dtype changes; source fractional couplings cannot be preserved as int32.",
        ),
        (
            "parameter_order_mismatch_refused",
            "Derivative request",
            "Only parameter order changes; the unchanged tangent cannot mask mislabelling.",
        ),
        (
            "tangent_convention_mismatch_refused",
            "Derivative request",
            "Only tangent convention changes; unchanged parameter order cannot mask it.",
        ),
        (
            "trainable_mask_length_mismatch_refused",
            "Derivative request",
            "Only mask length changes; every declared parameter still needs a mask entry.",
        ),
        (
            "effective_shots_contradict_source_refused",
            "Execution plan",
            "Only effective shots change; the retained source policy contradicts that value.",
        ),
    )
    rows += tuple(
        (case_id, family, "reject", rationale, isolated[case_id])
        for case_id, family, rationale in isolation_metadata
    )
    rows += (
        (
            "explicit_shot_request_preserves_source_plan",
            "Execution plan",
            "accept",
            "The actual100-shot request retains the source100-shot plan and origins; "
            "this is a proposed binding, not observed execution.",
            vectors.valid_companion(digest, shots=100),
        ),
    )
    scenarios = vectors.companion_custody_scenarios(raw_experiment_record())
    rows += (
        (
            "missing_companion_qualification_unavailable",
            "Result/evidence",
            "reject",
            "Proposed qualification must remain unavailable without a companion, "
            "while the existing raw record remains readable; no qualified persistence.",
            scenarios["missing_companion_qualification_unavailable"],
        ),
        (
            "companion_capture_survives_source_mutation",
            "Result/evidence",
            "accept",
            "Proposed captured raw and companion snapshots/digests survive named "
            "source mutations; this scenario is not executed capture conformance.",
            scenarios["companion_capture_survives_source_mutation"],
        ),
    )
    return tuple(
        CustodyCase(
            case_id=case_id,
            family=family,
            producer=vectors.COMPANION_SCHEMA,
            reader=proposed,
            expectation=expectation,
            status=DESIGN_VECTOR,
            rationale=rationale,
            payload=payload,
        )
        for case_id, family, expectation, rationale, payload in rows
    )


def _registry_source_cases() -> tuple[CustodyCase, ...]:
    """Return actual registry support and missing-contract report cases.

    Returns
    -------
    tuple
        Executed metadata reports, not compiled or numerical qualification.

    """
    reader = (
        "scpn_quantum_control.program_ad_registry.program_ad_registry_dispatch_coverage_report"
    )
    return tuple(
        CustodyCase(
            case_id=case_id,
            family="Semantic support",
            producer=reader,
            reader=reader,
            expectation="reject" if empty else "accept",
            status=EXECUTED,
            rationale="Actual registry report preserves declared support and missing-contract blockers; not executable lowering evidence.",
            payload=registry_evidence_source(empty=empty),
        )
        for case_id, empty in (
            ("registry_dispatch_preserves_declared_support", False),
            ("registry_dispatch_refuses_missing_contracts", True),
        )
    )


def _derivative_source_cases() -> tuple[CustodyCase, ...]:
    """Capture native derivative requests and finite-shot uncertainty sources."""
    rows: tuple[
        tuple[str, Literal["forward_mode", "reverse_mode", "parameter_shift"], str], ...
    ] = (
        ("forward_gradient_preserves_request_and_result", "forward_mode", "Derivative request"),
        ("reverse_gradient_preserves_request_and_result", "reverse_mode", "Derivative request"),
        ("stochastic_gradient_preserves_uncertainty_source", "parameter_shift", "Fidelity"),
    )
    cases: list[CustodyCase] = []
    for case_id, method, family in rows:
        payload = derivative_evidence_source(method)
        cases.append(
            CustodyCase(
                case_id=case_id,
                family=family,
                producer=payload["producer"],
                reader=payload["producer"],
                expectation="accept",
                status=EXECUTED,
                rationale="Actual native derivative request/result with source provenance; not hardware or companion binding conformance.",
                payload=payload,
            )
        )
    return tuple(cases)


def _problem_source_cases() -> tuple[CustodyCase, ...]:
    """Capture the actual benchmark problem and explicit projection-loss boundary."""
    payload = benchmark_problem_source()
    return (
        CustodyCase(
            case_id="benchmark_problem_preserves_distinct_identity",
            family="Problem identity",
            producer=payload["producer"],
            reader=payload["producer"],
            expectation="accept",
            status=EXECUTED,
            rationale="Actual seeded problem builders preserve distinct full identities; identity-binding refusal remains an unexecuted proposal.",
            payload=payload,
        ),
    )


def _offline_result_source_cases() -> tuple[CustodyCase, ...]:
    """Capture offline HAL/results without promoting unavailable non-count evidence."""
    hal = hal_evidence_source()
    result = stable_result_evidence_source()
    return (
        CustodyCase(
            case_id="offline_hal_preserves_native_result",
            family="Backend observation",
            producer=hal["producer"],
            reader=hal["producer"],
            expectation="accept",
            status=EXECUTED,
            payload=hal,
            rationale="Actual deterministic offline HAL routing and full native evidence; not physical simulation or QPU execution.",
        ),
        CustodyCase(
            case_id="stable_result_preserves_native_envelope",
            family="Result/evidence",
            producer=result["producer"],
            reader=result["reader"],
            expectation="accept",
            status=EXECUTED,
            payload=result,
            rationale="Actual stable Result codec roundtrip over an explicit test projection, not a shipped HAL adapter.",
        ),
        CustodyCase(
            case_id="count_only_hal_cannot_qualify_statevector",
            family="Backend observation",
            producer=vectors.COMPANION_SCHEMA,
            reader=f"{COMPANION_MODULE}.validate_semantic_binding",
            expectation="reject",
            status=DESIGN_VECTOR,
            payload=non_count_qualification_proposal(),
            rationale="Proposed refusal preserves actual count result; profile capability cannot invent missing amplitudes.",
        ),
    )


def build_cases() -> tuple[CustodyCase, ...]:
    """Return every case in stable catalogue order.

    Returns
    -------
    tuple
        The whole corpus.

    """
    return (
        _executed_cases()
        + _source_fact_cases()
        + _design_vector_cases()
        + _registry_source_cases()
        + _derivative_source_cases()
        + _problem_source_cases()
        + _offline_result_source_cases()
    )


def case_manifest_entry(case: CustodyCase) -> dict[str, Any]:
    """Return the manifest row for one case.

    Parameters
    ----------
    case
        The case to describe.

    Returns
    -------
    dict
        Manifest fields, including the fixture digest when the case has bytes.

    """
    entry: dict[str, Any] = {
        "case_id": case.case_id,
        "family": case.family,
        "producer": case.producer,
        "reader": case.reader,
        "expectation": case.expectation,
        "status": case.status,
        "rationale": case.rationale,
    }
    if case.payload is None:
        entry["fixture"] = None
        entry["fixture_sha256"] = None
    else:
        entry["fixture"] = f"{case.case_id}.json"
        entry["fixture_sha256"] = scp.digest_stable_core_payload(case.payload)
    return entry


def build_manifest(cases: tuple[CustodyCase, ...]) -> dict[str, Any]:
    """Return the full corpus manifest.

    Parameters
    ----------
    cases
        Cases to describe.

    Returns
    -------
    dict
        The manifest, cases in the given order.

    """
    return {
        "schema": CORPUS_SCHEMA,
        "companion_schema": vectors.COMPANION_SCHEMA,
        "companion_module": COMPANION_MODULE,
        "model_schema_version": scp.STABLE_CORE_MODEL_SCHEMA_VERSION,
        "design_vectors_are_unexecuted": True,
        "cases": [case_manifest_entry(case) for case in cases],
    }


def validate_manifest_schema(manifest: Mapping[str, Any]) -> str:
    """Return the manifest schema, refusing a superseded coded name.

    Parameters
    ----------
    manifest
        A parsed corpus manifest.

    Returns
    -------
    str
        The accepted schema identifier.

    Raises
    ------
    ValueError
        If the schema is a superseded internally-coded name, or is unknown.

    """
    schema = manifest.get("schema")
    if schema in SUPERSEDED_CORPUS_SCHEMAS:
        raise ValueError(
            f"corpus schema {schema!r} encodes an internal planning identifier and is "
            f"superseded by {CORPUS_SCHEMA!r}; regenerate the corpus"
        )
    if schema != CORPUS_SCHEMA:
        raise ValueError(f"unknown corpus schema {schema!r}; expected {CORPUS_SCHEMA!r}")
    return CORPUS_SCHEMA


def write_corpus(destination: Path) -> dict[str, Any]:
    """Write fixtures and manifest under ``destination``.

    Parameters
    ----------
    destination
        Directory to populate; created if absent.

    Returns
    -------
    dict
        The manifest that was written.

    """
    destination.mkdir(parents=True, exist_ok=True)
    cases = build_cases()
    for case in cases:
        if case.payload is None:
            continue
        body = scp.canonical_json_bytes(case.payload)
        (destination / f"{case.case_id}.json").write_bytes(body)
    manifest = build_manifest(cases)
    (destination / "manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return manifest


def main(argv: list[str] | None = None) -> int:
    """Write the corpus to the requested directory.

    Parameters
    ----------
    argv
        Command-line arguments; defaults to :data:`sys.argv`.

    Returns
    -------
    int
        Process exit status, zero on success.

    """
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("destination", type=Path)
    arguments = parser.parse_args(argv)
    manifest = write_corpus(arguments.destination)
    sys.stdout.write(f"{len(manifest['cases'])} cases written\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
