# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Quantum Control — generated differentiable reviewer-evidence page
"""Generate and audit the public differentiable reviewer-evidence page.

Every DP-015 criticism and DP-030 evidence-package row must name a scoped
runnable command or a public open-gap pointer. Rendering fails closed when a
repository path, command, changelog marker, support-matrix count, roadmap
marker, or capability-manifest surface drifts.

The output is documentation and governance evidence. It does not execute a
provider job, run an isolated benchmark, promote a compiler route, or add a
numerical compute kernel.
"""

from __future__ import annotations

import argparse
import json
import re
import shlex
import sys
from collections.abc import Mapping, Sequence
from importlib import import_module
from pathlib import Path
from typing import TYPE_CHECKING, Final, cast

if TYPE_CHECKING:
    from tools.differentiable_reviewer_evidence_catalog import (
        CAPABILITY_MANIFEST_SCHEMA,
        GENERATED_BY,
        OPEN_GAPS,
        REQUIRED_PACKAGE_EXPORTS,
        REQUIRED_PUBLIC_PAGES,
        REQUIRED_ROW_IDS,
        REQUIRED_SOURCE_MODULES,
        REQUIRED_TEST_FILES,
        REVIEWER_EVIDENCE_PAGE_SCHEMA,
        REVIEWER_EVIDENCE_ROWS,
        ReviewerEvidenceValidation,
        SupportMatrixSummary,
    )
else:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    _catalogue = import_module("tools.differentiable_reviewer_evidence_catalog")
    CAPABILITY_MANIFEST_SCHEMA = _catalogue.CAPABILITY_MANIFEST_SCHEMA
    GENERATED_BY = _catalogue.GENERATED_BY
    OPEN_GAPS = _catalogue.OPEN_GAPS
    REQUIRED_PACKAGE_EXPORTS = _catalogue.REQUIRED_PACKAGE_EXPORTS
    REQUIRED_PUBLIC_PAGES = _catalogue.REQUIRED_PUBLIC_PAGES
    REQUIRED_ROW_IDS = _catalogue.REQUIRED_ROW_IDS
    REQUIRED_SOURCE_MODULES = _catalogue.REQUIRED_SOURCE_MODULES
    REQUIRED_TEST_FILES = _catalogue.REQUIRED_TEST_FILES
    REVIEWER_EVIDENCE_PAGE_SCHEMA = _catalogue.REVIEWER_EVIDENCE_PAGE_SCHEMA
    REVIEWER_EVIDENCE_ROWS = _catalogue.REVIEWER_EVIDENCE_ROWS
    ReviewerEvidenceValidation = _catalogue.ReviewerEvidenceValidation
    SupportMatrixSummary = _catalogue.SupportMatrixSummary

REPO_ROOT: Final[Path] = Path(__file__).resolve().parents[1]
DEFAULT_PAGE_PATH: Final[Path] = REPO_ROOT / "docs/differentiable_reviewer_evidence.md"
DEFAULT_CAPABILITY_MANIFEST_PATH: Final[Path] = (
    REPO_ROOT / "docs/_generated/capability_manifest.json"
)
DEFAULT_SUPPORT_MATRIX_PATH: Final[Path] = REPO_ROOT / "docs/differentiable_support_matrix.md"
DEFAULT_CHANGELOG_PATH: Final[Path] = REPO_ROOT / "CHANGELOG.md"
DEFAULT_ROADMAP_PATH: Final[Path] = REPO_ROOT / "docs/differentiable_roadmap.md"

_SUPPORT_GENERATOR_MARKER: Final[str] = (
    "<!-- Generated by tools/differentiable_support_matrix_page.py; do not edit by hand. -->"
)
_SUPPORT_REVIEWER_LINK: Final[str] = "[Differentiable Reviewer Evidence]"
_REGISTRY_SUMMARY_RE: Final[re.Pattern[str]] = re.compile(
    r"\| Program AD registry \| `(?P<covered>\d+)/(?P<total>\d+)` complete \|"
)
_PLANNER_SUMMARY_RE: Final[re.Pattern[str]] = re.compile(
    r"\| Quantum-gradient planner audit \| `(?P<supported>\d+)` supported / "
    r"`(?P<blocked>\d+)` fail-closed \|"
)
_ALLOWED_CATEGORIES: Final[frozenset[str]] = frozenset({"reviewer_criticism", "evidence_package"})
_ALLOWED_STATUSES: Final[frozenset[str]] = frozenset({"implemented", "bounded", "open"})
_FORBIDDEN_COMMAND_TOKENS: Final[frozenset[str]] = frozenset(
    {"&&", "||", "|", ";", ">", ">>", "<", "2>", "2>>"}
)


def load_support_matrix_summary(
    path: Path = DEFAULT_SUPPORT_MATRIX_PATH,
) -> SupportMatrixSummary:
    """Parse synchronized counts from the generated support page.

    Parameters
    ----------
    path
        Generated support-matrix Markdown path.

    Returns
    -------
    SupportMatrixSummary
        Parsed registry and planner counts.

    Raises
    ------
    OSError
        If the page cannot be read.
    ValueError
        If the generated marker, reviewer link, or summary rows are missing.

    """
    content = path.read_text(encoding="utf-8")
    if _SUPPORT_GENERATOR_MARKER not in content:
        raise ValueError("support matrix lacks its generated-file marker")
    if _SUPPORT_REVIEWER_LINK not in content:
        raise ValueError("support matrix does not link the reviewer-evidence page")
    registry_match = _REGISTRY_SUMMARY_RE.search(content)
    planner_match = _PLANNER_SUMMARY_RE.search(content)
    if registry_match is None:
        raise ValueError("support matrix lacks the registry summary row")
    if planner_match is None:
        raise ValueError("support matrix lacks the planner summary row")
    return SupportMatrixSummary(
        registry_covered=int(registry_match.group("covered")),
        registry_total=int(registry_match.group("total")),
        planner_supported=int(planner_match.group("supported")),
        planner_blocked=int(planner_match.group("blocked")),
    )


def build_differentiable_reviewer_evidence_payload(
    *,
    support_summary: SupportMatrixSummary | None = None,
) -> dict[str, object]:
    """Build the deterministic reviewer-evidence payload.

    Parameters
    ----------
    support_summary
        Optional injected support-matrix summary. The committed page is parsed
        when omitted.

    Returns
    -------
    dict[str, object]
        JSON-ready rows, gaps, requirements, and claim boundary.

    """
    summary = load_support_matrix_summary() if support_summary is None else support_summary
    return {
        "schema": REVIEWER_EVIDENCE_PAGE_SCHEMA,
        "generated_by": GENERATED_BY,
        "support_matrix": summary.to_dict(),
        "rows": [row.to_dict() for row in REVIEWER_EVIDENCE_ROWS],
        "open_gaps": [gap.to_dict() for gap in OPEN_GAPS],
        "capability_manifest_requirements": {
            "schema_version": CAPABILITY_MANIFEST_SCHEMA,
            "package_exports": list(REQUIRED_PACKAGE_EXPORTS),
            "python_source_modules": list(REQUIRED_SOURCE_MODULES),
            "test_files": list(REQUIRED_TEST_FILES),
            "public_pages": list(REQUIRED_PUBLIC_PAGES),
        },
        "evidence_boundary": (
            "Generated reviewer-response index over repository commands and artefacts. "
            "Implemented and bounded rows identify only their declared local evidence; "
            "open rows remain unpromoted, and no provider, hardware, universal-framework, "
            "compiler, isolated-performance, or superiority claim is implied."
        ),
    }


def load_capability_manifest(
    path: Path = DEFAULT_CAPABILITY_MANIFEST_PATH,
) -> dict[str, object]:
    """Load a capability manifest and reject a non-object JSON root.

    Parameters
    ----------
    path
        Capability-manifest JSON path.

    Returns
    -------
    dict[str, object]
        Parsed manifest with string keys.

    Raises
    ------
    OSError
        If the manifest cannot be read.
    ValueError
        If the JSON root is not a string-keyed object.

    """
    decoded: object = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(decoded, dict) or not all(isinstance(key, str) for key in decoded):
        raise ValueError("capability manifest must be an object with string keys")
    return cast(dict[str, object], decoded)


def validate_reviewer_evidence_capability_manifest(
    manifest: Mapping[str, object],
    *,
    payload: Mapping[str, object] | None = None,
) -> ReviewerEvidenceValidation:
    """Validate reviewer-page requirements against the capability manifest.

    Parameters
    ----------
    manifest
        Parsed committed capability manifest.
    payload
        Optional reviewer payload carrying the required surfaces.

    Returns
    -------
    ReviewerEvidenceValidation
        Pass/fail verdict with deterministic mismatch descriptions.

    """
    current = build_differentiable_reviewer_evidence_payload() if payload is None else payload
    errors: list[str] = []
    requirements = _optional_mapping(current.get("capability_manifest_requirements"))
    if requirements is None:
        return ReviewerEvidenceValidation(
            False,
            ("reviewer payload capability_manifest_requirements object is missing",),
        )
    if manifest.get("schema_version") != requirements.get("schema_version"):
        errors.append("capability manifest schema_version does not match the reviewer page")
    project = _optional_mapping(manifest.get("project"))
    if project is None or project.get("name") != "scpn-quantum-control":
        errors.append("capability manifest project.name is not scpn-quantum-control")
    generated_from = _optional_mapping(manifest.get("generated_from"))
    if generated_from is None or generated_from.get("generator") != (
        "tools/capability_manifest.py"
    ):
        errors.append("capability manifest generator identity is invalid")

    package_exports = _string_set(manifest.get("package_exports"))
    source_modules = _manifest_string_set(manifest, "models", "python_source_modules", errors)
    test_files = _manifest_string_set(manifest, "quality_gates", "test_files", errors)
    public_pages = _manifest_string_set(manifest, "documentation", "public_pages", errors)
    required_fields = (
        ("package export", "package_exports", package_exports),
        ("source module", "python_source_modules", source_modules),
        ("test file", "test_files", test_files),
        ("public page", "public_pages", public_pages),
    )
    for label, field, observed in required_fields:
        for item in _required_strings(requirements.get(field), field, errors):
            if item not in observed:
                errors.append(f"capability manifest is missing required {label}: {item}")

    counts = _optional_mapping(manifest.get("counts"))
    if counts is None:
        errors.append("capability manifest counts object is missing")
    else:
        expected_counts = {
            "public_api_exports": len(package_exports),
            "python_model_source_modules": len(source_modules),
            "test_files": len(test_files),
            "public_documentation_pages": len(public_pages),
        }
        for name, actual in expected_counts.items():
            if counts.get(name) != actual:
                errors.append(
                    f"capability manifest count {name} does not match its surface length"
                )
    return ReviewerEvidenceValidation(not errors, tuple(errors))


def validate_differentiable_reviewer_evidence_payload(
    payload: Mapping[str, object],
    *,
    repo_root: Path = REPO_ROOT,
    changelog_path: Path = DEFAULT_CHANGELOG_PATH,
    roadmap_path: Path = DEFAULT_ROADMAP_PATH,
) -> ReviewerEvidenceValidation:
    """Validate every reviewer-evidence row against repository sources.

    Parameters
    ----------
    payload
        Reviewer payload to validate.
    repo_root
        Repository root used for path-safety and existence checks.
    changelog_path
        Changelog whose exact markers must support the rows.
    roadmap_path
        Public roadmap containing every referenced open-gap marker.

    Returns
    -------
    ReviewerEvidenceValidation
        Pass/fail verdict with all detected contract errors.

    """
    errors: list[str] = []
    if payload.get("schema") != REVIEWER_EVIDENCE_PAGE_SCHEMA:
        errors.append("reviewer-evidence payload has an unexpected schema")
    if payload.get("generated_by") != GENERATED_BY:
        errors.append("reviewer-evidence payload has an unexpected generator command")
    rows = _mapping_rows(payload.get("rows"), "rows", errors)
    gaps = _mapping_rows(payload.get("open_gaps"), "open_gaps", errors)
    support = _optional_mapping(payload.get("support_matrix"))
    if support is None:
        errors.append("reviewer-evidence payload support_matrix object is missing")
    else:
        _validate_support_payload(support, errors)
    changelog = _read_validation_text(changelog_path, "changelog", errors)
    roadmap = _read_validation_text(roadmap_path, "public roadmap", errors)
    gap_refs = _validate_gap_rows(gaps, roadmap, errors)

    observed_ids: set[str] = set()
    for row in rows:
        row_id = _required_string(row, "row_id", "evidence row", errors)
        if row_id in observed_ids:
            errors.append(f"duplicate reviewer-evidence row_id: {row_id}")
        observed_ids.add(row_id)
        _validate_evidence_row(
            row,
            row_id=row_id,
            repo_root=repo_root,
            changelog=changelog,
            known_gap_refs=gap_refs,
            errors=errors,
        )
    for row_id in sorted(REQUIRED_ROW_IDS - observed_ids):
        errors.append(f"reviewer-evidence payload is missing required row: {row_id}")
    for row_id in sorted(observed_ids - REQUIRED_ROW_IDS):
        errors.append(f"reviewer-evidence payload has unexpected row: {row_id}")
    return ReviewerEvidenceValidation(not errors, tuple(errors))


def render_differentiable_reviewer_evidence_page(
    payload: Mapping[str, object],
    *,
    repo_root: Path = REPO_ROOT,
    changelog_path: Path = DEFAULT_CHANGELOG_PATH,
    roadmap_path: Path = DEFAULT_ROADMAP_PATH,
) -> str:
    """Render a validated reviewer-evidence payload as Markdown.

    Parameters
    ----------
    payload
        Payload from :func:`build_differentiable_reviewer_evidence_payload`.
    repo_root
        Repository root used for evidence validation.
    changelog_path
        Changelog used for marker validation.
    roadmap_path
        Public roadmap used for open-gap validation.

    Returns
    -------
    str
        Deterministic generated Markdown.

    Raises
    ------
    ValueError
        If any row or referenced repository surface is invalid.

    """
    validation = validate_differentiable_reviewer_evidence_payload(
        payload,
        repo_root=repo_root,
        changelog_path=changelog_path,
        roadmap_path=roadmap_path,
    )
    if not validation.passed:
        raise ValueError("; ".join(validation.errors))
    rows = cast(list[Mapping[str, object]], payload["rows"])
    gaps = cast(list[Mapping[str, object]], payload["open_gaps"])
    support = cast(Mapping[str, object], payload["support_matrix"])
    criticism_rows = [row for row in rows if row.get("category") == "reviewer_criticism"]
    package_rows = [row for row in rows if row.get("category") == "evidence_package"]
    lines = [
        "<!-- Generated by tools/differentiable_reviewer_evidence_page.py; do not edit by hand. -->",
        "",
        "# Differentiable Reviewer Evidence",
        "",
        "This page maps the bounded DP-015 reviewer criticisms and the DP-030 evidence",
        "package to real repository commands, artefacts, and explicit public gaps. It is",
        "an index into executable evidence, not a replacement for the tests or artefacts.",
        "",
        "Regenerate and validate it with:",
        "",
        "```bash",
        GENERATED_BY,
        "python tools/differentiable_reviewer_evidence_page.py --check",
        "```",
        "",
        "## Evidence boundary",
        "",
        str(payload.get("evidence_boundary")),
        "",
        "## Support-matrix synchronization",
        "",
        "The generated [Differentiable Support Matrix](differentiable_support_matrix.md)",
        "supplies the current registry and planner summary:",
        "",
        "| Generated surface | Current result |",
        "|---|---:|",
        f"| Program AD registry | `{support.get('registry_covered')}/{support.get('registry_total')}` complete |",
        (
            "| Quantum-gradient planner audit | "
            f"`{support.get('planner_supported')}` supported / "
            f"`{support.get('planner_blocked')}` fail-closed |"
        ),
        "",
        "## DP-015 reviewer criticisms",
        "",
        "| ID | Criticism | Status | Evidence and reproduction | Open gap | Boundary |",
        "|---|---|---|---|---|---|",
    ]
    lines.extend(_render_evidence_row(row) for row in criticism_rows)
    lines.extend(
        [
            "",
            "## DP-030 evidence package",
            "",
            "| ID | Requirement | Status | Evidence and reproduction | Open gap | Boundary |",
            "|---|---|---|---|---|---|",
        ]
    )
    lines.extend(_render_evidence_row(row) for row in package_rows)
    lines.extend(
        [
            "",
            "## Public open-gap pointers",
            "",
            "These identifiers resolve to the [open evidence work](differentiable_roadmap.md#open-evidence-work)",
            "section of the public roadmap. A row carrying one remains bounded or open even",
            "when its local command passes.",
            "",
            "| Pointer | Gap | Evidence still required |",
            "|---|---|---|",
        ]
    )
    lines.extend(
        f"| `{_markdown_text(gap.get('pointer'))}` | {_markdown_text(gap.get('title'))} | "
        f"{_markdown_text(gap.get('detail'))} |"
        for gap in gaps
    )
    lines.extend(
        [
            "",
            "## Reading the rows",
            "",
            "- `implemented` means the declared bounded contract has a runnable evidence route.",
            "- `bounded` means local evidence exists but a named promotion gap remains open.",
            "- `open` means existing artefacts are diagnostic or functional only and cannot",
            "  support the requested promoted claim.",
            "- Commands are deliberately module-scoped; repository-wide local test runs remain",
            "  outside this reproduction page.",
            "",
        ]
    )
    return "\n".join(lines)


def audit_differentiable_reviewer_evidence_page(
    *,
    page_path: Path = DEFAULT_PAGE_PATH,
    manifest_path: Path = DEFAULT_CAPABILITY_MANIFEST_PATH,
    support_matrix_path: Path = DEFAULT_SUPPORT_MATRIX_PATH,
    changelog_path: Path = DEFAULT_CHANGELOG_PATH,
    roadmap_path: Path = DEFAULT_ROADMAP_PATH,
    repo_root: Path = REPO_ROOT,
) -> tuple[str, ...]:
    """Return drift and source-alignment errors for the committed page.

    Parameters
    ----------
    page_path
        Generated reviewer-evidence Markdown path.
    manifest_path
        Capability-manifest JSON path.
    support_matrix_path
        Generated support-matrix Markdown path.
    changelog_path
        Changelog used for traceability markers.
    roadmap_path
        Public roadmap used for open-gap markers.
    repo_root
        Repository root used for path-safety checks.

    Returns
    -------
    tuple[str, ...]
        Empty on success; deterministic errors otherwise.

    """
    try:
        payload = build_differentiable_reviewer_evidence_payload(
            support_summary=load_support_matrix_summary(support_matrix_path)
        )
        manifest_validation = validate_reviewer_evidence_capability_manifest(
            load_capability_manifest(manifest_path),
            payload=payload,
        )
        if not manifest_validation.passed:
            return manifest_validation.errors
        rendered = render_differentiable_reviewer_evidence_page(
            payload,
            repo_root=repo_root,
            changelog_path=changelog_path,
            roadmap_path=roadmap_path,
        )
        if not page_path.is_file():
            return (f"generated reviewer-evidence page is missing: {page_path}",)
        if page_path.read_text(encoding="utf-8") != rendered:
            return (f"generated reviewer-evidence page is stale: run {GENERATED_BY}",)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        return (f"reviewer-evidence page audit failed: {exc}",)
    return ()


def main(argv: Sequence[str] | None = None) -> int:
    """Run preview, write, or committed-page drift validation.

    Parameters
    ----------
    argv
        Optional command-line argument sequence.

    Returns
    -------
    int
        Zero on success and one on validation or drift failure.

    """
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="write the generated page")
    mode.add_argument("--check", action="store_true", help="check committed page drift")
    parser.add_argument("--output", type=Path, default=DEFAULT_PAGE_PATH)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_CAPABILITY_MANIFEST_PATH)
    parser.add_argument("--support-matrix", type=Path, default=DEFAULT_SUPPORT_MATRIX_PATH)
    parser.add_argument("--changelog", type=Path, default=DEFAULT_CHANGELOG_PATH)
    parser.add_argument("--roadmap", type=Path, default=DEFAULT_ROADMAP_PATH)
    args = parser.parse_args(argv)
    if args.check:
        errors = audit_differentiable_reviewer_evidence_page(
            page_path=args.output,
            manifest_path=args.manifest,
            support_matrix_path=args.support_matrix,
            changelog_path=args.changelog,
            roadmap_path=args.roadmap,
        )
        if errors:
            for error in errors:
                print(f"differentiable reviewer-evidence page: FAIL: {error}", file=sys.stderr)
            return 1
        print("differentiable reviewer-evidence page: current")
        return 0
    try:
        payload = build_differentiable_reviewer_evidence_payload(
            support_summary=load_support_matrix_summary(args.support_matrix)
        )
        manifest_validation = validate_reviewer_evidence_capability_manifest(
            load_capability_manifest(args.manifest),
            payload=payload,
        )
        if not manifest_validation.passed:
            raise ValueError("; ".join(manifest_validation.errors))
        rendered = render_differentiable_reviewer_evidence_page(
            payload,
            changelog_path=args.changelog,
            roadmap_path=args.roadmap,
        )
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"differentiable reviewer-evidence page: FAIL: {exc}", file=sys.stderr)
        return 1
    if args.write:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered, encoding="utf-8")
        print(f"wrote {args.output}")
        return 0
    print(rendered, end="")
    return 0


def _optional_mapping(value: object) -> Mapping[str, object] | None:
    """Return a string-keyed mapping when the value has the required shape."""
    if not isinstance(value, dict) or not all(isinstance(key, str) for key in value):
        return None
    return cast(Mapping[str, object], value)


def _mapping_rows(
    value: object,
    label: str,
    errors: list[str],
) -> tuple[Mapping[str, object], ...]:
    """Parse an object-list field while accumulating shape errors."""
    if not isinstance(value, list):
        errors.append(f"{label} must be a list of objects")
        return ()
    rows: list[Mapping[str, object]] = []
    for index, row in enumerate(value):
        mapping = _optional_mapping(row)
        if mapping is None:
            errors.append(f"{label}[{index}] must be an object with string keys")
        else:
            rows.append(mapping)
    return tuple(rows)


def _string_set(value: object) -> set[str]:
    """Return string members from a manifest list."""
    if not isinstance(value, list):
        return set()
    return {item for item in value if isinstance(item, str)}


def _manifest_string_set(
    manifest: Mapping[str, object],
    section_name: str,
    field: str,
    errors: list[str],
) -> set[str]:
    """Read a nested manifest string list while recording malformed shapes."""
    section = _optional_mapping(manifest.get(section_name))
    if section is None:
        errors.append(f"capability manifest {section_name} object is missing")
        return set()
    value = section.get(field)
    if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
        errors.append(f"capability manifest {section_name}.{field} must be a string list")
        return set()
    return set(value)


def _required_strings(value: object, label: str, errors: list[str]) -> tuple[str, ...]:
    """Parse required non-blank strings while recording malformed shapes."""
    if not isinstance(value, list) or not all(
        isinstance(item, str) and item.strip() for item in value
    ):
        errors.append(f"reviewer payload {label} must be a non-blank string list")
        return ()
    return tuple(value)


def _read_validation_text(path: Path, label: str, errors: list[str]) -> str:
    """Read a validation source while recording I/O failures."""
    try:
        return path.read_text(encoding="utf-8")
    except OSError as exc:
        errors.append(f"cannot read {label}: {exc}")
        return ""


def _required_string(
    row: Mapping[str, object],
    field: str,
    label: str,
    errors: list[str],
) -> str:
    """Read one non-blank row string while recording malformed values."""
    value = row.get(field)
    if not isinstance(value, str) or not value.strip():
        errors.append(f"{label} {field} must be a non-blank string")
        return ""
    return value


def _row_string_tuple(
    row: Mapping[str, object],
    field: str,
    row_id: str,
    errors: list[str],
) -> tuple[str, ...]:
    """Read one row string-list field with uniqueness checks."""
    value = row.get(field)
    if not isinstance(value, list) or not all(
        isinstance(item, str) and item.strip() for item in value
    ):
        errors.append(f"{row_id} {field} must be a non-blank string list")
        return ()
    if len(set(value)) != len(value):
        errors.append(f"{row_id} {field} must not contain duplicates")
    return tuple(value)


def _validate_support_payload(
    support: Mapping[str, object],
    errors: list[str],
) -> None:
    """Validate generated support counts carried in the payload."""
    values: dict[str, int] = {}
    for field in (
        "registry_covered",
        "registry_total",
        "planner_supported",
        "planner_blocked",
    ):
        value = support.get(field)
        if not isinstance(value, int) or isinstance(value, bool) or value <= 0:
            errors.append(f"support_matrix.{field} must be a positive integer")
        else:
            values[field] = value
    if values.get("registry_covered") != values.get("registry_total"):
        errors.append("support_matrix registry coverage must be complete")


def _validate_gap_rows(
    gaps: Sequence[Mapping[str, object]],
    roadmap: str,
    errors: list[str],
) -> set[str]:
    """Validate public open-gap rows and return their pointers."""
    expected = {gap.pointer: gap.roadmap_marker for gap in OPEN_GAPS}
    observed: dict[str, str] = {}
    for gap in gaps:
        pointer = _required_string(gap, "pointer", "open gap", errors)
        marker = _required_string(gap, "roadmap_marker", pointer or "open gap", errors)
        _required_string(gap, "title", pointer or "open gap", errors)
        _required_string(gap, "detail", pointer or "open gap", errors)
        if pointer in observed:
            errors.append(f"duplicate open-gap pointer: {pointer}")
        observed[pointer] = marker
        if expected.get(pointer) != marker:
            errors.append(f"open-gap marker does not match the canonical definition: {pointer}")
        if marker and marker not in roadmap:
            errors.append(f"public roadmap is missing open-gap marker: {marker}")
    for pointer in sorted(set(expected) - set(observed)):
        errors.append(f"reviewer payload is missing required open gap: {pointer}")
    for pointer in sorted(set(observed) - set(expected)):
        errors.append(f"reviewer payload has unexpected open gap: {pointer}")
    return set(observed)


def _validate_evidence_row(
    row: Mapping[str, object],
    *,
    row_id: str,
    repo_root: Path,
    changelog: str,
    known_gap_refs: set[str],
    errors: list[str],
) -> None:
    """Validate one evidence row's classification, commands, paths, and markers."""
    label = row_id or "evidence row"
    category = _required_string(row, "category", label, errors)
    status = _required_string(row, "status", label, errors)
    for field in ("criticism", "evidence_summary", "claim_boundary"):
        _required_string(row, field, label, errors)
    if category not in _ALLOWED_CATEGORIES:
        errors.append(f"{row_id} has unsupported category: {category}")
    if status not in _ALLOWED_STATUSES:
        errors.append(f"{row_id} has unsupported status: {status}")
    prefix = "DP-015-" if category == "reviewer_criticism" else "DP-030-"
    if row_id and category in _ALLOWED_CATEGORIES and not row_id.startswith(prefix):
        errors.append(f"{row_id} does not match category prefix {prefix}")
    commands = _row_string_tuple(row, "commands", row_id, errors)
    paths = _row_string_tuple(row, "evidence_paths", row_id, errors)
    gap_refs = _row_string_tuple(row, "open_gap_refs", row_id, errors)
    markers = _row_string_tuple(row, "changelog_markers", row_id, errors)
    if not commands and not gap_refs:
        errors.append(f"{row_id} must name a runnable command or open-gap pointer")
    if status == "open" and not gap_refs:
        errors.append(f"open row {row_id} must name an open-gap pointer")
    if status == "implemented" and gap_refs:
        errors.append(f"implemented row {row_id} cannot carry open-gap pointers")
    if not paths:
        errors.append(f"{row_id} must name at least one evidence path")
    for command in commands:
        errors.extend(_validate_command(command, repo_root=repo_root, row_id=row_id))
    for path in paths:
        path_error = _validate_repository_path(path, repo_root=repo_root)
        if path_error is not None:
            errors.append(f"{row_id} evidence path {path_error}: {path}")
    for gap_ref in gap_refs:
        if gap_ref not in known_gap_refs:
            errors.append(f"{row_id} references unknown public open gap: {gap_ref}")
    for marker in markers:
        if marker not in changelog:
            errors.append(f"{row_id} changelog marker is missing: {marker}")


def _validate_command(command: str, *, repo_root: Path, row_id: str) -> tuple[str, ...]:
    """Validate one command as a scoped Python test or drift-check invocation."""
    try:
        tokens = shlex.split(command)
    except ValueError as exc:
        return (f"{row_id} command cannot be parsed: {exc}",)
    if not tokens or tokens[0] != "python":
        return (f"{row_id} command must start with python: {command}",)
    errors: list[str] = []
    if any(token in _FORBIDDEN_COMMAND_TOKENS for token in tokens):
        errors.append(f"{row_id} command contains a shell-control token: {command}")
    if tokens[1:4] == ["-m", "pytest", "-q"]:
        test_paths = tokens[4:]
        if not test_paths or not all(path.endswith(".py") for path in test_paths):
            errors.append(f"{row_id} pytest command must contain only explicit test files")
        for test_path in test_paths:
            if not test_path.startswith("tests/test_"):
                errors.append(f"{row_id} pytest path is not a scoped test module: {test_path}")
            path_error = _validate_repository_path(test_path, repo_root=repo_root)
            if path_error is not None:
                errors.append(f"{row_id} command path {path_error}: {test_path}")
        return tuple(errors)
    if len(tokens) == 3 and tokens[1].startswith("tools/") and tokens[1].endswith(".py"):
        if tokens[2] != "--check":
            errors.append(f"{row_id} tool command must use --check: {command}")
        path_error = _validate_repository_path(tokens[1], repo_root=repo_root)
        if path_error is not None:
            errors.append(f"{row_id} command path {path_error}: {tokens[1]}")
        return tuple(errors)
    return (f"{row_id} command is outside the scoped command grammar: {command}",)


def _validate_repository_path(path: str, *, repo_root: Path) -> str | None:
    """Return a path-safety/existence error or ``None`` for a valid path."""
    candidate = Path(path)
    if candidate.is_absolute() or ".." in candidate.parts:
        return "is absolute or contains parent traversal"
    root = repo_root.resolve()
    resolved = (root / candidate).resolve()
    if not resolved.is_relative_to(root):
        return "escapes the repository root"
    if not resolved.is_file():
        return "does not resolve to a file"
    return None


def _render_evidence_row(row: Mapping[str, object]) -> str:
    """Render one validated evidence row as a Markdown table line."""
    commands = cast(list[str], row["commands"])
    paths = cast(list[str], row["evidence_paths"])
    gaps = cast(list[str], row["open_gap_refs"])
    reproduction = [
        _markdown_text(row.get("evidence_summary")),
        "Commands: " + "<br>".join(f"`{_markdown_text(command)}`" for command in commands),
        "Paths: " + ", ".join(f"`{_markdown_text(path)}`" for path in paths),
    ]
    gap_text = ", ".join(f"`{_markdown_text(gap)}`" for gap in gaps) or "—"
    return (
        f"| `{_markdown_text(row.get('row_id'))}` | {_markdown_text(row.get('criticism'))} | "
        f"`{_markdown_text(row.get('status'))}` | {'<br>'.join(reproduction)} | "
        f"{gap_text} | {_markdown_text(row.get('claim_boundary'))} |"
    )


def _markdown_text(value: object) -> str:
    """Escape arbitrary scalar content for one Markdown table cell."""
    text = "n/a" if value is None else str(value)
    return text.replace("\n", " ").replace("|", "\\|").replace("`", "\\`")


if __name__ == "__main__":
    raise SystemExit(main())
