# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# scpn-quantum-control — independent-target task acceptance
"""Check source-group, causal-prefix and target-origin boundaries."""

from __future__ import annotations

from dataclasses import replace

import pytest

from scpn_quantum_control.experimental.llm_qpu.data.dedup import validate_source_families
from scpn_quantum_control.experimental.llm_qpu.data.splits import (
    build_memory_split,
    pilot_inputs,
)
from scpn_quantum_control.experimental.llm_qpu.data.tasks import (
    build_memory_task,
    generate_memory_records,
)

_BASE = "a" * 40
_REVISION = "b" * 40


def test_t04a_paraphrases_cannot_cross_source_groups() -> None:
    """A duplicated source or normalized prompt is one held-out group."""
    records = generate_memory_records(seed=73, source_count=6)
    with pytest.raises(ValueError, match="multiple groups"):
        validate_source_families(
            (*records, replace(records[0], sample_id="extra", group_id="other-group"))
        )
    with pytest.raises(ValueError, match="duplicated across"):
        validate_source_families(
            (
                *records,
                replace(
                    records[0], sample_id="extra", source_id="new-source", group_id="other-group"
                ),
            )
        )


def test_t04b_answer_suffix_cannot_enter_extraction_prefix() -> None:
    """The worker input ends before the answer generated by the evaluator."""
    record = generate_memory_records(seed=73, source_count=3)[0]
    with pytest.raises(ValueError, match="before generated answer"):
        replace(record, prefix_text=f"{record.prefix_text} {record.target_text}")


def test_t04c_deterministic_group_split_and_answer_free_pilot() -> None:
    """The same seeds freeze exact sources, labels, partitions and 16 prefixes."""
    records = generate_memory_records(seed=73)
    assert records == generate_memory_records(seed=73)
    split = build_memory_split(
        build_memory_task(base_repo_commit=_BASE, implementation_revision=_REVISION),
        records,
        seed=31,
        generation_seed=73,
        train_count=64,
        dev_count=32,
        test_count=32,
        base_repo_commit=_BASE,
        implementation_revision=_REVISION,
    )
    assert len(split.train_groups) == 64
    assert len(split.dev_groups) == len(split.test_groups) == 32
    assert split == build_memory_split(
        build_memory_task(base_repo_commit=_BASE, implementation_revision=_REVISION),
        records,
        seed=31,
        generation_seed=73,
        train_count=64,
        dev_count=32,
        test_count=32,
        base_repo_commit=_BASE,
        implementation_revision=_REVISION,
    )
    pilot = pilot_inputs(records, split)
    assert len(pilot) == 16
    assert all(
        "target_text" not in row and row["prefix_text"].endswith("Answer:") for row in pilot
    )
    replacement = "blue" if records[0].target_text != "blue" else "amber"
    with pytest.raises(ValueError, match="frozen split"):
        pilot_inputs((replace(records[0], target_text=replacement), *records[1:]), split)


def test_t04d_fixture_and_qpu_target_provenance_are_refused() -> None:
    """Transport fixtures and QPU-derived labels cannot claim this task target."""
    record = generate_memory_records(seed=73, source_count=3)[0]
    with pytest.raises(ValueError, match="classical generator"):
        replace(record, source_kind="fixture")
    with pytest.raises(ValueError, match="classical generator"):
        replace(record, target_origin="qpu_output")


def test_t04e_wrong_classical_label_fails_generator_binding() -> None:
    """A hand-edited label cannot enter a split under a valid generator claim."""
    records = generate_memory_records(seed=73, source_count=6)
    replacement = "blue" if records[0].target_text != "blue" else "amber"
    changed = (replace(records[0], target_text=replacement), *records[1:])
    with pytest.raises(ValueError, match="differ from independent"):
        build_memory_split(
            build_memory_task(base_repo_commit=_BASE, implementation_revision=_REVISION),
            changed,
            seed=31,
            generation_seed=73,
            train_count=2,
            dev_count=2,
            test_count=2,
            base_repo_commit=_BASE,
            implementation_revision=_REVISION,
        )
